  <langue>
		<url_domaine><?php echo URL_DOMAINE ?></url_domaine>
		<id_projet><?php echo $langue->getXML("id_projet")?></id_projet>
		<id_langue><?php echo $langue->getXML("id_langue")?></id_langue>
		<titre><?php echo $langue->getXML("titre")?></titre>
		<delimiteur><?php echo $langue->getXML("delimiteur")?></delimiteur>
		<boutons_annuler><?php echo $langue->getXML("boutons_annuler")?></boutons_annuler>
		<boutons_ok><?php echo $langue->getXML("boutons_ok")?></boutons_ok>
		<consignes_association><?php echo $langue->getXML("consignes_association")?></consignes_association>
		<consignes_choixmultiples><?php echo $langue->getXML("consignes_choixmultiples")?></consignes_choixmultiples>
		<consignes_classement><?php echo $langue->getXML("consignes_classement")?></consignes_classement>
		<consignes_damier_masquees><?php echo $langue->getXML("consignes_damier_masquees")?></consignes_damier_masquees>
		<consignes_damier_nonmasquees><?php echo $langue->getXML("consignes_damier_nonmasquees")?></consignes_damier_nonmasquees>
		<consignes_developpement><?php echo $langue->getXML("consignes_developpement")?></consignes_developpement>
		<consignes_dictee_debut><?php echo $langue->getXML("consignes_dictee_debut")?></consignes_dictee_debut>
		<consignes_dictee_majuscules><?php echo $langue->getXML("consignes_dictee_majuscules")?></consignes_dictee_majuscules>
		<consignes_dictee_ponctuation><?php echo $langue->getXML("consignes_dictee_ponctuation")?></consignes_dictee_ponctuation>
		<consignes_marquage><?php echo $langue->getXML("consignes_marquage")?></consignes_marquage>
		<consignes_ordre><?php echo $langue->getXML("consignes_ordre")?></consignes_ordre>
		<consignes_reponsebreve_debut><?php echo $langue->getXML("consignes_reponsebreve_debut")?></consignes_reponsebreve_debut>
		<consignes_reponsebreve_majuscules><?php echo $langue->getXML("consignes_reponsebreve_majuscules")?></consignes_reponsebreve_majuscules>
		<consignes_reponsebreve_ponctuation><?php echo $langue->getXML("consignes_reponsebreve_ponctuation")?></consignes_reponsebreve_ponctuation>
		<consignes_reponsesmultiples_unereponse><?php echo $langue->getXML("consignes_reponsesmultiples_unereponse")?></consignes_reponsesmultiples_unereponse>
		<consignes_reponsesmultiples_toutes><?php echo $langue->getXML("consignes_reponsesmultiples_toutes")?></consignes_reponsesmultiples_toutes>
		<consignes_lacunaire_menu><?php echo $langue->getXML("consignes_lacunaire_menu")?></consignes_lacunaire_menu>
		<consignes_lacunaire_glisser><?php echo $langue->getXML("consignes_lacunaire_glisser")?></consignes_lacunaire_glisser>
		<consignes_lacunaire_reponsebreve_debut><?php echo $langue->getXML("consignes_lacunaire_reponsebreve_debut")?></consignes_lacunaire_reponsebreve_debut>
		<consignes_lacunaire_reponsebreve_majuscules><?php echo $langue->getXML("consignes_lacunaire_reponsebreve_majuscules")?></consignes_lacunaire_reponsebreve_majuscules>
		<consignes_lacunaire_reponsebreve_ponctuation><?php echo $langue->getXML("consignes_lacunaire_reponsebreve_ponctuation")?></consignes_lacunaire_reponsebreve_ponctuation>
		<consignes_vraifaux><?php echo $langue->getXML("consignes_vraifaux")?></consignes_vraifaux>
		<consignes_zones><?php echo $langue->getXML("consignes_zones")?></consignes_zones>
		<fenetre_renseignements><?php echo $langue->getXML("fenetre_renseignements")?></fenetre_renseignements>
		<fenetre_nom><?php echo $langue->getXML("fenetre_nom")?></fenetre_nom>
		<fenetre_prenom><?php echo $langue->getXML("fenetre_prenom")?></fenetre_prenom>
		<fenetre_matricule><?php echo $langue->getXML("fenetre_matricule")?></fenetre_matricule>
		<fenetre_groupe><?php echo $langue->getXML("fenetre_groupe")?></fenetre_groupe>
		<fenetre_courriel><?php echo $langue->getXML("fenetre_courriel")?></fenetre_courriel>
		<fenetre_autre><?php echo $langue->getXML("fenetre_autre")?></fenetre_autre>
		<fenetre_envoi><?php echo $langue->getXML("fenetre_envoi")?></fenetre_envoi>
		<fenetre_courriel_destinataire><?php echo $langue->getXML("fenetre_courriel_destinataire")?></fenetre_courriel_destinataire>
		<fonctionnalites_commencer><?php echo $langue->getXML("fonctionnalites_commencer")?></fonctionnalites_commencer>
		<fonctionnalites_effacer><?php echo $langue->getXML("fonctionnalites_effacer")?></fonctionnalites_effacer>
		<fonctionnalites_courriel><?php echo $langue->getXML("fonctionnalites_courriel")?></fonctionnalites_courriel>
		<fonctionnalites_imprimer><?php echo $langue->getXML("fonctionnalites_imprimer")?></fonctionnalites_imprimer>
		<fonctionnalites_recommencer><?php echo $langue->getXML("fonctionnalites_recommencer")?></fonctionnalites_recommencer>
		<fonctionnalites_reprendre><?php echo $langue->getXML("fonctionnalites_reprendre")?></fonctionnalites_reprendre>
		<fonctionnalites_resultats><?php echo $langue->getXML("fonctionnalites_resultats")?></fonctionnalites_resultats>
		<fonctionnalites_lexique><?php echo $langue->getXML("fonctionnalites_lexique")?></fonctionnalites_lexique>
		<fonctionnalites_questionnaire><?php echo $langue->getXML("fonctionnalites_questionnaire")?></fonctionnalites_questionnaire>
		<fonctionnalites_solution><?php echo $langue->getXML("fonctionnalites_solution")?></fonctionnalites_solution>
		<fonctionnalites_valider><?php echo $langue->getXML("fonctionnalites_valider")?></fonctionnalites_valider>
		<navigation_page><?php echo $langue->getXML("navigation_page")?></navigation_page>
		<navigation_de><?php echo $langue->getXML("navigation_de")?></navigation_de>
		<message_bonnereponse><?php echo $langue->getXML("message_bonnereponse")?></message_bonnereponse>
		<message_mauvaisereponse><?php echo $langue->getXML("message_mauvaisereponse")?></message_mauvaisereponse>
		<message_reponseincomplete><?php echo $langue->getXML("message_reponseincomplete")?></message_reponseincomplete>
		<media_bonnereponse><?php echo $langue->getXML("media_bonnereponse")?></media_bonnereponse>
		<media_mauvaisereponse><?php echo $langue->getXML("media_mauvaisereponse")?></media_mauvaisereponse>
		<media_reponseincomplete><?php echo $langue->getXML("media_reponseincomplete")?></media_reponseincomplete>
		<message_libelle_solution><?php echo $langue->getXML("message_libelle_solution")?></message_libelle_solution>
		<message_point><?php echo $langue->getXML("message_point")?></message_point>
		<message_points><?php echo $langue->getXML("message_points")?></message_points>
		<message_sanstitre><?php echo $langue->getXML("message_sanstitre")?></message_sanstitre>
		<conjonction_et><?php echo $langue->getXML("conjonction_et")?></conjonction_et>
		<message_dictee_motsentrop><?php echo $langue->getXML("message_dictee_motsentrop")?></message_dictee_motsentrop>
		<message_dictee_orthographe><?php echo $langue->getXML("message_dictee_orthographe")?></message_dictee_orthographe>
		<message_dictee_motsmanquants><?php echo $langue->getXML("message_dictee_motsmanquants")?></message_dictee_motsmanquants>
		<message_reponsesuggeree><?php echo $langue->getXML("message_reponsesuggeree")?></message_reponsesuggeree>
		<resultats_afaire><?php echo $langue->getXML("resultats_afaire")?></resultats_afaire>
		<resultats_areprendre><?php echo $langue->getXML("resultats_areprendre")?></resultats_areprendre>
		<resultats_message_courriel_succes><?php echo $langue->getXML("resultats_message_courriel_succes")?></resultats_message_courriel_succes>
		<resultats_message_courriel_erreur><?php echo $langue->getXML("resultats_message_courriel_erreur")?></resultats_message_courriel_erreur>
		<resultats_objet_courriel><?php echo $langue->getXML("resultats_objet_courriel")?></resultats_objet_courriel>
		<resultats_confirmation><?php echo $langue->getXML("resultats_confirmation")?></resultats_confirmation>
		<resultats_accueil><?php echo $langue->getXML("resultats_accueil")?></resultats_accueil>
		<resultats_nbessais><?php echo $langue->getXML("resultats_nbessais")?></resultats_nbessais>
		<resultats_points><?php echo $langue->getXML("resultats_points")?></resultats_points>
		<resultats_reussi><?php echo $langue->getXML("resultats_reussi")?></resultats_reussi>
		<resultats_sansobjet><?php echo $langue->getXML("resultats_sansobjet")?></resultats_sansobjet>
		<resultats_statut><?php echo $langue->getXML("resultats_statut")?></resultats_statut>
		<resultats_tempsdereponse><?php echo $langue->getXML("resultats_tempsdereponse")?></resultats_tempsdereponse>
		<item_association><?php echo $langue->getXML("item_association")?></item_association>
		<item_choixmultiples><?php echo $langue->getXML("item_choixmultiples")?></item_choixmultiples>
		<item_classement><?php echo $langue->getXML("item_classement")?></item_classement>
		<item_damier><?php echo $langue->getXML("item_damier")?></item_damier>
		<item_developpement><?php echo $langue->getXML("item_developpement")?></item_developpement>
		<item_dictee><?php echo $langue->getXML("item_dictee")?></item_dictee>
		<item_marquage><?php echo $langue->getXML("item_marquage")?></item_marquage>
		<item_miseenordre><?php echo $langue->getXML("item_miseenordre")?></item_miseenordre>
		<item_reponsebreve><?php echo $langue->getXML("item_reponsebreve")?></item_reponsebreve>
		<item_reponsesmultiples><?php echo $langue->getXML("item_reponsesmultiples")?></item_reponsesmultiples>
		<item_textelacunaire><?php echo $langue->getXML("item_textelacunaire")?></item_textelacunaire>
		<item_vraioufaux><?php echo $langue->getXML("item_vraioufaux")?></item_vraioufaux>
		<item_zonesaidentifier><?php echo $langue->getXML("item_zonesaidentifier")?></item_zonesaidentifier>
		<remarque><?php echo $langue->getXML("remarque")?></remarque>
		<statut><?php echo $langue->getXML("statut")?></statut>
		<date_modification><?php echo $langue->getXML("date_modification")?></date_modification>
		<date_creation><?php echo $langue->getXML("date_creation")?></date_creation>
  </langue>

