<?php
/**
 * Fichier contenant les expressions pour la langue fr_CA
 *
 * @package NetquizWeb
 */


/** Expressions */
define('LANGUE_INTERFACE','1');
define('LANGUE_INTERFACE_TITRE','Français');
define('TXT_BIENVENUE', 'Bienvenue dans Netquiz Web');
define('TXT_NOUVEAU_QUESTIONNAIRE', 'Questionnaire sans titre');
define('TXT_NOUVEL_ITEM', 'Item sans titre');
define('TXT_NOUVELLE_SECTION', 'Section sans titre');
define('TXT_PREFIX_DUPLIQUER', '*');
define('TXT_QUESTIONNAIRES', 'Questionnaires');
define('TXT_MES_QUESTIONNAIRES', 'Mes questionnaires');
define('TXT_CORBEILLE', 'Corbeille');
define('TXT_FRANCAIS', 'Fran&ccedil;ais');
define('TXT_ANGLAIS', 'Anglais');
define('TXT_BIBLIOTHEQUE', 'Biblioth&egrave;que');
define('TXT_ACCUEIL_NETQUIZWEB', 'Accueil Netquiz Web');
define('TXT_MON_PROFIL', 'Mon profil');
define('TXT_DECONNEXION','D&eacute;connexion');
define('TXT_A_PROPOS','&Agrave; propos');
define('TXT_INTRODUCTION','Introduction');
define('TXT_DROITS_UTILISATION','Droits d\'utilisation');
define('TXT_GENERIQUE','G&eacute;n&eacute;rique');
define('TXT_COMMENTAIRES','Commentaires');
define('TXT_AIDE','Aide');
define('TXT_AJOUTER_NOUVEAU_QUESTIONNAIRE','Ajouter un nouveau questionnaire');
define('TXT_AFFICHER_TOUTES_LES_COLLECTIONS', 'Afficher toutes les collections');
define('TXT_CODE','Code');
define('TXT_TITRE','Titre');
define('TXT_ITEMS','Items');
define('TXT_COLLECTION','Collection');
define('TXT_STATUT','Statut');
define('TXT_DATE_DE_MODIFICATION','Date de modification');
define('TXT_PAR_PAGE', 'par page');
define('TXT_ELEMENT', '&Eacute;l&eacute;ment');
define('TXT_ELEMENT_MINUSCULES', '&eacute;l&eacute;ment');
define('TXT_DE', 'de');
define('TXT_DE_2', 'De');
define('TXT_MODIFIER', 'Modifier');
define('TXT_DUPLIQUER', 'Dupliquer');
define('TXT_ACTIVER_SUIVI', 'Activer le suivi');
define('TXT_ACCUEIL_CCDMD', 'Accueil CCDMD');
define('TXT_VOIR_APERCU_WEB', 'Voir un aper&ccedil;u Web');
define('TXT_EXPORTER_XML', 'Exporter XML');
define('TXT_IMPRIMER', 'Imprimer');
define('TXT_METTRE_A_LA_CORBEILLE', 'Mettre &agrave; la corbeille');
define('TXT_CCDMD_DROITS', 'Centre coll&eacute;gial de d&eacute;veloppement de mat&eacute;riel didactique, 2014');
define('TXT_INSCRIRE_MOTSCLES', 'Inscrire vos mots-cl&eacute;s');
define('TXT_PARAMETRES', 'Param&egrave;tres');
define('TXT_PARAMETRES_DE_ITEM', 'Param&egrave;tres de l\'item');
define('TXT_THEME', 'Th&egrave;me');
define('TXT_THEME_DU_QUESTIONNAIRE', 'Th&egrave;me du questionnaire');
define('TXT_ANNULER','Annuler');
define('TXT_ENREGISTRER', 'Enregistrer');
define('TXT_TITRE_DU_QUESTIONNAIRE', 'Titre du questionnaire');
define('TXT_CHOISIR_UNE_COLLECTION', 'Choisir une collection');
define('TXT_GENERATION_DES_ITEMS', 'Pr&eacute;sentation des items');
define('TXT_SELON_PARAMETRE_SECTION', 'Selon le param&egrave;tre de chaque section');
define('TXT_SELON_PARAMETRE_ITEM', 'Selon le param&egrave;tre de chaque item');
define('TXT_ORDRE_ALEATOIRE', 'Ordre al&eacute;atoire');
define('TXT_ORDRE_PREDETERMINE', 'Ordre pr&eacute;d&eacute;termin&eacute;');
define('TXT_INCLURE', 'Inclure');
define('TXT_ITEMS_SUR_X_ITEMS', 'items sur');
define('TXT_TEMPS_DE_PASSATION', 'Temps de passation');
define('TXT_ILLIMITE', 'Illimit&eacute;');
define('TXT_LIMITE', 'Limit&eacute;');
define('TXT_HEURES', 'heures');
define('TXT_MINUTES', 'minutes');
define('TXT_AFFICHAGE_DES_RESULTATS', 'Affichage des r&eacute;sultats');
define('TXT_TOUJOURS_AFFICHER', 'Toujours afficher');
define('TXT_JAMAIS_AFFICHER', 'Ne jamais afficher');
define('TXT_NOMBRE_ESSAI_POUR_REPONDRE', 'Nombre d\'essais pour r&eacute;pondre');
define('TXT_A', '&agrave;');
define('TXT_ESSAIS', 'essais');
define('TXT_DEMARRAGE_AUTOMATIQUE_DES_MEDIAS', 'D&eacute;marrage automatique des m&eacute;dias');
define('TXT_NE_JAMAIS_DEMARRER_DE_MEDIAS', 'Ne jamais d&eacute;marrer de m&eacute;dias');
define('TXT_TOUJOURS_DEMARRER_MEDIA_AUDIO', 'Toujours d&eacute;marrer le m&eacute;dia audio');
define('TXT_TOUJOURS_DEMARRER_MEDIA_VIDEO', 'Toujours d&eacute;marrer le m&eacute;dia vid&eacute;o');
define('TXT_LANGUE_DU_QUESTIONNAIRE_PUBLIE', 'Langue d\'aperçu ou de publication de ce questionnaire');
define('TXT_FIN_DU_QUESTIONNAIRE', 'Fin du questionnaire');
define('TXT_CONTENU', 'Contenu');
define('TXT_TEXTE', 'Texte');
define('TXT_NETQUIZ_WEB', 'Netquiz Web');
define('TXT_PAGE_ACCUEIL', 'Page d\'accueil');
define('TXT_COMPLEMENTS', 'Compl&eacute;ments');
define('TXT_TITRE_QUESTIONNAIRE_PAGE_ACCUEIL', 'Titre du questionnaire sur la page d\'accueil');
define('TXT_MOT_DE_BIENVENUE', 'Mot de bienvenue');
define('TXT_NOTE', 'Note');
define('TXT_MEDIA_ACCUEIL', 'M&eacute;dias d\'accueil');
define('TXT_MEDIA_ACCUEIL_TITRE', 'M&eacute;dias d\'accueil - Titre');
define('TXT_MEDIA_ACCUEIL_TEXTE', 'M&eacute;dias d\'accueil - Texte');
define('TXT_AJOUTER_UN_TEXTE', 'Ajouter un texte');
define('TXT_INSCRIRE_LE_TITRE', 'Inscrire le titre');
define('TXT_INSCRIRE_UN_TITRE', 'Inscrire un titre');
define('TXT_INSCRIRE_LE_TEXTE', 'Inscrire le texte');
define('TXT_AJOUTER_UNE_IMAGE', 'Ajouter une image');
define('TXT_AUCUNE_SELECTION', 'Aucune s&eacute;lection');
define('TXT_AJOUTER_UN_SON', 'Ajouter un son');
define('TXT_AJOUTER_UNE_VIDEO', 'Ajouter une vid&eacute;o');
define('TXT_TITRE_DE_LA_SECTION', 'Titre de la section');
define('TXT_CHOIX_MULTIPLES', 'Choix multiples');
define('TXT_TITRE_ITEM', 'Titre de l\'item');
define('TXT_ENONCE', '&Eacute;nonc&eacute;');
define('TXT_BONNE_REPONSE', 'Bonne r&eacute;ponse');
define('TXT_REPONSE', 'R&eacute;ponse');
define('TXT_RETROACTION', 'R&eacute;troaction');
define('TXT_CATEGORIE', 'Cat&eacute;gorie');
define('TXT_CHOISIR_UNE_CATEGORIE', 'Choisir une cat&eacute;gorie');
define('TXT_NE_PAS_DEMARRER_DE_MEDIA','Ne pas d&eacute;marrer de m&eacute;dias');
define('TXT_DEMARRER_LE_MEDIA_AUDIO','D&eacute;marrer le m&eacute;dia audio');
define('TXT_DEMARRER_LE_MEDIA_VIDEO','D&eacute;marrer le m&eacute;dia vid&eacute;o');
define('TXT_MODIFIER_CES_VALEURS_POUR_CE_QUESTIONNAIRE_SEULEMENT','Modifier ces valeurs pour ce questionnaire seulement');
define('TXT_VALEURS_MODIFIEES_POUR_CE_QUESTIONNAIRE_SEULEMENT','Valeurs modifi&eacute;es pour ce questionnaire seulement');
define('TXT_MODIFIER_CES_VALEURS_POUR_CET_ITEM_SEULEMENT','Modifier ces valeurs pour cet item seulement');
define('TXT_VALEURS_MODIFIEES_POUR_CET_ITEM_SEULEMENT','Valeurs modifi&eacute;es pour cet item seulement');
define('TXT_AFFICHAGE_DE_LA_SOLUTION','Affichage de la solution');
define('TXT_AFFICHER','Afficher');
define('TXT_NE_PAS_AFFICHER','Ne pas afficher');
define('TXT_ORDRE_DE_PRESENTATION_DES_ELEMENTS','Ordre de pr&eacute;sentation des &eacute;l&eacute;ments');
define('TXT_PREDETERMINE','Pr&eacute;d&eacute;termin&eacute;');
define('TXT_ALEATOIRE','Al&eacute;atoire');
define('TXT_ETIQUETTE_DES_ELEMENTS','&Eacute;tiquette des &eacute;l&eacute;ments');
define('TXT_NUMERIQUE','Num&eacute;rique');
define('TXT_ALPHABETIQUE','Alphab&eacute;tique');
define('TXT_AUCUN','Aucun');
define('TXT_MESSAGES_GENERAUX_DE_LA_LANGUE_DE_APERCU','Messages g&eacute;n&eacute;raux de la langue de l\'aper&ccedil;u');
define('TXT_MESSAGES_GENERAUX_DE_LA_LANGUE_DU_QUESTIONNAIRE','Messages g&eacute;n&eacute;raux de la langue du questionnaire');
define('TXT_MESSAGE_POUR_BONNE_REPONSE','Message pour bonne r&eacute;ponse');
define('TXT_MESSAGE_POUR_MAUVAISE_REPONSE','Message pour mauvaise r&eacute;ponse');
define('TXT_MESSAGE_POUR_REPONSE_INCOMPLETE','Message pour r&eacute;ponse incompl&egrave;te');
define('TXT_REMARQUE','Remarque');
define('TXT_PONDERATION', 'Pond&eacute;ration');
define('TXT_INFORMATION_COMPLEMENTAIRE', 'Information compl&eacute;mentaire');
define('TXT_INSCRIRE_LE_TITRE_DETAILS', 'Inscrire le titre (Indice, Source, Savoir plus, Aide, etc.)');
define('TXT_MEDIA_EN_ENTETE', 'M&eacute;dias en ent&ecirc;te');
define('TXT_QUESTIONNAIRE','Questionnaire');
define('TXT_DESACTIVER', 'D&eacute;sactiver');
define('TXT_PUBLIER_LE_QUESTIONNAIRE', 'Publier le questionnaire');
define('TXT_PUBLIE', 'Publi&eacute;');
define('TXT_PUBLIER', 'Publier');
define('TXT_APERCU', 'Aper&ccedil;u');
define('TXT_AJOUTER_UN_NOUVEL_ITEM', 'Ajouter un nouvel item');
define('TXT_ASSOCIATION', 'Association');
define('TXT_ASSOCIATIONS', 'Associations');
define('TXT_CLASSEMENT', 'Classement');
define('TXT_DAMIER', 'Damier');
define('TXT_DEVELOPPEMENT', 'D&eacute;veloppement');
define('TXT_DICTEE', 'Dict&eacute;e');
define('TXT_MARQUAGE', 'Marquage');
define('TXT_MISE_EN_ORDRE', 'Mise en ordre');
define('TXT_REPONSE_BREVE', 'R&eacute;ponse br&egrave;ve');
define('TXT_REPONSES_MULTIPLES', 'R&eacute;ponses multiples');
define('TXT_TEXTE_LACUNAIRE', 'Texte lacunaire');
define('TXT_VRAI_OU_FAUX', 'Vrai ou faux');
define('TXT_ZONES_A_IDENTIFIER', 'Zones &agrave; identifier');
define('TXT_ZONES_A_IDENTIFIER_ENTETE_ITEM', 'Zone à identifier');
define('TXT_PAGE', 'Page');
define('TXT_AJOUTER_UNE_SECTION', 'Ajouter une section');
define('TXT_AJOUTER_DES_ITEMS_DE_LA_BIBLIOTHEQUE', 'Ajouter des items de la biblioth&egrave;que');
define('TXT_BIENVENUE_DANS_NETQUIZ_WEB', 'Bienvenue dans Netquiz Web!');
define('TXT_BIENVENUE_DANS_NETQUIZ_WEB1', 'Bienvenue dans Netquiz Web! (Version');
define('TXT_BIENVENUE_DANS_NETQUIZ_WEB2', ')');
define('TXT_IDENTIFICATION_LIGNE1', '<em>Netquiz Web</em> vous permet de composer des exercices, des jeux-questionnaires ou des tests formatifs et de les publier sur le Web au moyen d\'un simple clic. Ces derniers peuvent comporter des items de 14 types diff&eacute;rents <em>(Associations, Choix multiples, Classement, Damier, D&eacute;veloppement, Dict&eacute;e, Marquage, Mise en ordre, R&eacute;ponse br&egrave;ve, R&eacute;ponses multiples, Texte lacunaire, Vrai ou faux, Zones &agrave; identifier, Page)</em>&nbsp;dans lesquels il vous est possible d\'ins&eacute;rer des images, des textes, des sons et des s&eacute;quences vid&eacute;o. Vous pouvez &eacute;galement ajouter un glossaire, de sorte que les termes et expressions qu\'il contient s\'affichent en relief dans le questionnaire, permettant aux r&eacute;pondants d\'obtenir leur d&eacute;finition sous forme de texte, d\'image, de vid&eacute;o, de son ou de liens.');
define('TXT_CONNEXION', 'Connexion');
define('TXT_ENTREZ_NOM_UTILISATEUR_ET_MOT_DE_PASSE', 'Entrez votre nom d\'utilisateur et votre mot de passe.');
define('TXT_IDENTIFICATION_CONSULTEZ_AIDE', '');
define('TXT_MESSAGE_NAVIGATEURS_NON_SUPPORTES', 'Cette application n\'est pas optimis&eacute;e pour votre navigateur. Veuillez faire passer votre navigateur &agrave; une version plus r&eacute;cente.');
define('TXT_COURRIEL_OU_NOM_UTILISATEUR', 'Courriel ou nom d\'utilisateur');
define('TXT_CHAMPS_REQUIS', 'Champs requis');
define('TXT_SE_SOUVENIR_DE_MOI', 'Se souvenir de moi');
define('TXT_ME_CONNECTER', 'Me connecter');
define('TXT_MOT_DE_PASSE_OU_UTILISATEUR_OUBLIE', 'Mot de passe ou nom d\'utilisateur oubli&eacute;?');
define('TXT_NOUVEAUTE', 'Nouveaut&eacute;s');
define('TXT_INSCRIRE_VOTRE_ENONCE', 'Inscrire votre &eacute;nonc&eacute;');
define('TXT_IMAGE', 'Image');
define('TXT_SON', 'Son');
define('TXT_VIDEO', 'Vid&eacute;o');
define('TXT_AUCUNE_IMAGE', 'Aucune image');
define('TXT_AUCUN_SON', 'Aucun son');
define('TXT_AUCUN_VIDEO', 'Aucune vid&eacute;o');
define('TXT_DATE_DE_CREATION', 'Date de cr&eacute;ation');
define('TXT_LISTE_DES_ELEMENTS', 'Liste des &eacute;l&eacute;ments');
define('TXT_SECTION', 'Section');
define('TXT_CONTENU_DETAILLE_DE_CHAQUE_ELEMENT_DU_QUESTIONNAIRE', 'Contenu d&eacute;taill&eacute; de chaque &eacute;l&eacute;ment du questionnaire');
define('TXT_CHOIX', 'Choix');
define('TXT_SUPPRIMER_ITEM', 'Supprimer cet item');
define('TXT_SUPPRIMER_ITEM_DU_QUESTIONNAIRE', 'Enlever cet item du questionnaire');
define('TXT_VOULEZ_VOUS_SUPPRIMER_CET_ITEM_DU_QUESTIONNAIRE','Voulez-vous vraiment supprimer cet item du questionnaire? Cette action est irréversible.');
define('TXT_VOULEZ_VOUS_SUPPRIMER_CET_ITEM','Voulez-vous vraiment supprimer cet item? Cette action est irréversible.');
define('TXT_SUPPRIMER_CETTE_SECTION_ET_SON_CONTENU', 'Supprimer cette section et son contenu');
define('TXT_VOULEZ_VOUS_SUPPRIMER_CETTE_SECTION', 'Voulez-vous vraiment supprimer cette section et son contenu? Cette action est irréversible.');
define('TXT_VOULEZ_VOUS_METTRE_QUESTIONNAIRE_DANS_LA_CORBEILLE', 'Voulez-vous vraiment mettre ce questionnaire dans la corbeille?');
define('TXT_TYPE_ITEM', 'Type d\'item');
define('TXT_CHANGER_TYPE_ITEM', 'Changer le type d\'item');
define('TXT_SUPPRIMER_DEFINITIVEMENT', 'Supprimer d&eacute;finitivement');
define('TXT_RECUPERER_ELEMENT', 'Restaurer');
define('TXT_ITEM', 'Item');
define('TXT_MES_ITEMS', 'Mes items');
define('TXT_AFFICHER_TOUS_LES_TYPES', 'Afficher tous les types');
define('TXT_TYPE','Type');
define('TXT_MES_MEDIAS', 'Mes m&eacute;dias');
define('TXT_MES_LANGUES', 'Mes langues');
define('TXT_MES_COLLECTIONS', 'Mes collections');
define('TXT_MES_CATEGORIES', 'Mes cat&eacute;gories');
define('TXT_NOUVELLE_COLLECTION', 'Collection sans titre');
define('TXT_NOUVELLE_CATEGORIE', 'Cat&eacute;gorie sans titre');
define('TXT_COLLECTIONS', 'Collections');
define('TXT_CATEGORIES', 'Cat&eacute;gories');
define('TXT_TITRE_DE_LA_COLLECTION', 'Titre de la collection');
define('TXT_TITRE_DE_LA_CATEGORIE', 'Titre de la cat&eacute;gorie');
define('TXT_AJOUTER_UNE_NOUVELLE_CATEGORIE', 'Ajouter une nouvelle cat&eacute;gorie');
define('TXT_AJOUTER_UNE_NOUVELLE_COLLECTION', 'Ajouter une nouvelle collection');
define('TXT_NOUVELLE_LANGUE', 'Langue sans titre');
define('TXT_AJOUTER_UNE_NOUVELLE_LANGUE', 'Ajouter une nouvelle langue');
define('TXT_LANGUE', 'Langue');
define('TXT_LANGUES', 'Langues');
define('TXT_PREFIX_ITEM', 'I');
define('TXT_PREFIX_MEDIA', 'M');
define('TXT_PREFIX_COLLECTION', 'C');
define('TXT_PREFIX_CATEGORIE', 'E');
define('TXT_PREFIX_LANGUE', 'L');
define('TXT_PREFIX_QUESTIONNAIRE', 'Q');
define('TXT_PREFIX_PROJET', 'P');
define('TXT_PREFIX_USAGER', 'U');
define('TXT_PREFIX_TERME', 'T');
define('TXT_DELIMITEUR_DE_NOMBRE', 'D&eacute;limiteur de nombre');

define('TXT_VIRGULE', 'Virgule');
define('TXT_DELIMITEUR_POINT', 'Point'); 

define('TXT_POINT', 'Point');
define('TXT_TITRE_DE_LA_LANGUE', 'Titre de la langue');
define('TXT_INSCRIRE_COMMENTAIRE_GESTION_LANGUES', 'Inscrire une remarque utile pour la gestion des langues');
define('TXT_AJOUTER_UN_MEDIA','Ajouter un m&eacute;dia');
define('TXT_AJOUTER_UN_NOUVEAU_MEDIA', 'Ajouter un nouveau m&eacute;dia');
define('TXT_NOUVEAU_MEDIA','M&eacute;dia sans titre');
define('TXT_TITRE_DU_MEDIA', 'Titre du m&eacute;dia');
define('TXT_DESCRIPTION', 'Description');
define('TXT_MEDIA', 'M&eacute;dia');
define('TXT_CHARGEMENT_EN_COURS', 'Chargement en cours');
define('TXT_CHOISIR_DE_LA_BIBLIOTHEQUE','Choisir de la biblioth&egrave;que');
define('TXT_CHOISIR_UNE_IMAGE_DE_LA_BIBLIOTHEQUE','Choisir une image de la biblioth&egrave;que');
define('TXT_CHOISIR_UNE_VIDEO_DE_LA_BIBLIOTHEQUE','Choisir une vid&eacute;o de la biblioth&egrave;que');
define('TXT_CHOISIR_UN_SON_DE_LA_BIBLIOTHEQUE','Choisir un son de la biblioth&egrave;que');
define('TXT_IMPORTER_UN_NOUVEAU_FICHIER', 'Importer un nouveau fichier');
define('TXT_SELECTION_FICHIER_SUR_VOTRE_ORDINATEUR', 'S&eacute;lection d\'un nouveau fichier sur votre ordinateur');
define('TXT_MEDIA_PROVENANT_AUTRE_SITE', 'M&eacute;dia provenant d\'un autre site');
define('TXT_FICHIER_MEDIA', 'Fichier média');
define('TXT_NOUVEAU_FICHIER','Nouveau fichier');
define('TXT_MEDIAS', 'M&eacute;dias');
define('TXT_ACCUEIL', 'Accueil');
define('TXT_ERREUR', 'Erreur');
define('TXT_SOURCE', 'Source');
define('TXT_FICHIER', 'Fichier');
define('TXT_CHOIX_DE_REPONSES', 'Choix de réponses');
define('TXT_CHOIX_DE_REPONSE', 'Choix de réponse');
define('TXT_BOUTONS','Boutons');
define('TXT_OK','OK');
define('TXT_CONSIGNES','Consignes');
define('TXT_QUESTION_TYPE_ASSOCIATION','Question de type Association');
define('TXT_QUESTION_TYPE_CHOIX_MULTIPLES','Question de type Choix multiples');
define('TXT_QUESTION_TYPE_CLASSEMENT','Question de type Classement');
define('TXT_QUESTION_TYPE_DAMIER_CASES_MASQUEES','Question de type Damier (cases masqu&eacute;es)');
define('TXT_QUESTION_TYPE_DAMIER_CASES_NON_MASQUEES','Question de type Damier (cases non masqu&eacute;es)');
define('TXT_QUESTION_TYPE_DEVELOPPEMENT','Question de type D&eacute;veloppement');
define('TXT_QUESTION_TYPE_DICTEE_CONSIGNE','Question de type Dict&eacute;e (D&eacute;but de la consigne)');
define('TXT_QUESTION_TYPE_DICTEE_MAJUSCULES','Question de type Dict&eacute;e (Option majuscules/minuscules)');
define('TXT_QUESTION_TYPE_DICTEE_PONCTUATION','Question de type Dict&eacute;e (Option ponctuation)');
define('TXT_QUESTION_TYPE_MARQUAGE','Question de type Marquage');
define('TXT_QUESTION_TYPE_MISE_EN_ORDRE','Question de type Mise en ordre');
define('TXT_QUESTION_TYPE_REPONSE_BREVE_CONSIGNE','Question de type R&eacute;ponse br&egrave;ve (D&eacute;but de la consigne)');
define('TXT_QUESTION_TYPE_REPONSE_BREVE_MAJUSCULES','Question de type R&eacute;ponse br&egrave;ve (Option majuscules/minuscules)');
define('TXT_QUESTION_TYPE_REPONSE_BREVE_PONCTUATION','Question de type R&eacute;ponse br&egrave;ve (Option ponctuation)');
define('TXT_QUESTION_TYPE_REPONSES_MULTIPLES_UNE_BONNE_REPONSE','Question de type R&eacute;ponses multiples (au moins une bonne r&eacute;ponse)');
define('TXT_QUESTION_TYPE_REPONSES_MULTIPLES_TOUTES_BONNES_REPONSES','Question de type R&eacute;ponses multiples (toutes les bonnes r&eacute;ponses)');
define('TXT_QUESTION_TYPE_TEXTE_LACUNAIRE_MENU','Question de type Texte lacunaire (menu d&eacute;roulant)');
define('TXT_QUESTION_TYPE_TEXTE_LACUNAIRE_GLISSER','Question de type Texte lacunaire (glisser-d&eacute;poser)');
define('TXT_QUESTION_TYPE_TEXTE_LACUNAIRE_CONSIGNE','Question de type Texte lacunaire (r&eacute;ponse br&egrave;ve, d&eacute;but de la consigne)');
define('TXT_QUESTION_TYPE_TEXTE_LACUNAIRE_MAJUSCULES','Question de type Texte lacunaire (r&eacute;ponse br&egrave;ve, option majuscules/minuscules)');
define('TXT_QUESTION_TYPE_TEXTE_LACUNAIRE_PONCTUATION','Question de type Texte lacunaire (r&eacute;ponse br&egrave;ve, option ponctuation)');
define('TXT_QUESTION_TYPE_VRAI_OU_FAUX','Question de type Vrai ou faux');
define('TXT_QUESTION_TYPE_ZONES_A_IDENTIFIER','Question de type Zones &agrave; identifier');
define('TXT_FENETRES','Fen&ecirc;tres');
define('TXT_RENSEIGNEMENT_SUR_LE_REPONDANT','Renseignements sur le r&eacute;pondant');
define('TXT_NOM','Nom');
define('TXT_PRENOM','Pr&eacute;nom');
define('TXT_MATRICULE','Identifiant');
define('TXT_GROUPE','Groupe');
define('TXT_COURRIEL','Courriel');
define('TXT_AUTRE','Autre');
define('TXT_ENVOI_DES_RESULTATS_PAR_COURRIEL','Envoi des r&eacute;sultats par courriel');
define('TXT_COURRIEL_DU_DESTINATAIRE','Courriel du destinataire');
define('TXT_FONCTIONNALITES','Fonctionnalit&eacute;s');
define('TXT_COMMENCER','Commencer');
define('TXT_EFFACER_LES_MARQUES','Effacer les marques sélectionnées');
define('TXT_ENVOYER_PAR_COURRIEL','Envoyer par courriel');
define('TXT_RECOMMENCER','Recommencer');
define('TXT_REPRENDRE','Reprendre');
define('TXT_RESULTATS','R&eacute;sultats');
define('TXT_SOLUTION','Solution');
define('TXT_VALIDER','Valider');
define('TXT_MENU_DE_NAVIGATION','Menu de navigation');
define('TXT_MESSAGE_GENERAUX','Messages g&eacute;n&eacute;raux (tout type d&rsquo;item)');
define('TXT_MESSAGE_BONNE_REPONSE','Message pour bonne r&eacute;ponse');
define('TXT_MESSAGE_MAUVAISE_REPONSE','Message pour mauvaise r&eacute;ponse');
define('TXT_MESSAGE_REPONSE_INCOMPLETE','Message pour r&eacute;ponse incompl&egrave;te');
define('TXT_MESSAGES_PARTICULIERS','Messages particuliers (propres &agrave; certains types d&rsquo;items)');
define('TXT_MESSAGE_POUR_MOTS_EN_TROP','Message pour mots en trop (dict&eacute;e)');
define('TXT_MESSAGE_POUR_MOTS_MAL_ORTHOGRAPHIES','Message pour mots mal orthographi&eacute;s (dict&eacute;e)');
define('TXT_MESSAGE_POUR_MOTS_MANQUANTS','Message pour mots manquants (dict&eacute;e)');
define('TXT_MESSAGE_POUR_REPONSE_SUGGEREE','Message pour r&eacute;ponse sugg&eacute;r&eacute;e (d&eacute;veloppement)');
define('TXT_TABLEAU_DE_RESULTATS','Tableau de r&eacute;sultats');
define('TXT_A_FAIRE','&Agrave; faire');
define('TXT_A_REPRENDRE','&Agrave; reprendre');
define('TXT_MESSAGE_DE_CONFIRMATION_REPRISE_QUESTIONNAIRE','Message de confirmation pour la reprise du questionnaire');
define('TXT_NOMBRE_ESSAIS','Nombre d&rsquo;essais');
define('TXT_POINTS','Points');
define('TXT_POINTS_POUR_MOTS_MAL_ORTHOGRAPHIES','Points retranch&eacute;s pour mots mal orthographi&eacute;s');
define('TXT_REUSSI','R&eacute;ussi');
define('TXT_SANS_OBJET','Sans objet');
define('TXT_TEMPS_DE_REPONSE','Temps de r&eacute;ponse');
define('TXT_TYPES_ITEMS','Types d&rsquo;items (pour affichage de leur consigne respective)');
define('TXT_EX_2_DE_30', '(ex. 2 de 30)');
define('TXT_CONJONCTION_ET', 'Conjonction et');
define('TXT_MON_COMPTE', 'Mon compte');
define('TXT_NOUVEAU_MOT_PASSE', 'Nouveau mot de passe');
define('TXT_NOUVEAU_MOT_PASSE_CONF', 'Confirmer le nouveau mot de passe');
define('TXT_MOT_PASSE_ACTUEL','Mot de passe actuel');
define('TXT_MDP_INSTRUCTIONS', '(Minimum de 8 caractères, incluant au moins une lettre et un chiffre)');
define('TXT_CODE_USAGER_INSTRUCTIONS', '(Minimum de 5 caractères, sans espaces, n\'incluant que des lettres, des chiffres, des traits soulignés (_) ou des tirets(-))');
define('TXT_MON_MOT_DE_PASSE', 'Mon mot de passe');
define('TXT_POUR_LA_CORRECTION_TENIR_COMPTE', 'Pour la correction, tenir compte');
define('TXT_DES_MAJUSCULES_MINUSCULES', 'des majuscules/minuscules');
define('TXT_DE_LA_PONCTUATION', 'de la ponctuation');
define('TXT_MOT_PASSE_OU_NOM_UTILISATEUR_OUBLIE','Mot de passe ou nom d\'utilisateur oubli&eacute;?');
define('TXT_SAISISSEZ_VOTRE_ADRESSE_COURRIEL','Saisissez votre adresse de courriel et nous vous enverrons un courriel qui vous permettra de r&eacute;initialiser votre mot de passe.');
define('TXT_ENVOYER', 'Envoyer');
define('TXT_RETOUR_A_LA_CONNEXION','Retour &agrave; la connexion');
define('TXT_COURRIEL_RAPPEL_OBJET', 'Netquiz Web - Mot de passe ou nom d\'utilisateur oublié');
define('TXT_COURRIEL_RAPPEL_BONJOUR','Bonjour');
define('TXT_COURRIEL_RAPPEL_LIGNE1','Vous avez oublié le mot de passe ou le nom d\'utilisateur de votre compte Netquiz Web. Pour accéder à ce site, vous devez réinitialiser votre mot de passe en cliquant sur le lien suivant:');
define('TXT_COURRIEL_RAPPEL_LIGNE2','Si ce lien ne fonctionne pas, veuillez le copier-coller dans la barre d\'adresse de votre fureteur.');
define('TXT_COURRIEL_RAPPEL_LIGNE3','N.B.: Si vous ne voulez pas réinitialiser votre mot de passe, veuillez ignorer ce message. Votre mot de passe ne sera pas réinitialisé. En cas de problème ou si ce n\'est pas vous qui avez fait cette demande, veuillez nous en informer par retour de ce courriel.');
define('TXT_COURRIEL_RAPPEL_MERCI','Merci d\'utiliser Netquiz Web.');
define('TXT_REINITIALISER_VOTRE_MOT_PASSE', 'R&eacute;initialiser votre mot de passe');
define('TXT_NOM_UTILISATEUR', 'Nom d\'utilisateur');
define('TXT_ERREURS_DETECTEES_ITEM', 'Erreurs d&eacute;tect&eacute;es dans la validation de l\'item');
define('TXT_ERREURS_DETECTEES_QUESTIONNAIRE', 'Erreurs détectées dans le questionnaire');
define('TXT_SANS_TITRE', 'Sans titre');
define('TXT_ADRESSE_DU_DOSSIER_EN_LIGNE', 'Identifiant unique pour l\'adresse URL de publication');
define('TXT_QUESTIONNAIRE_PUBLIE_AVEC_SUCCES', 'Le questionnaire a &eacute;t&eacute; publi&eacute; avec succ&egrave;s.');
define('TXT_ADRESSE_DU_DOSSIER_EN_LIGNE_EST', 'L\'adresse URL du questionnaire publié est');
define('TXT_FERMER', 'Fermer');
define('TXT_VOIR_LE_QUESTIONNAIRE_PUBLIE', 'Voir le questionnaire publié');
define('TXT_FICHIER_ACTUEL', 'Fichier actuel');
define('TXT_AUCUN_FICHIER_SELECTIONNE', 'Aucun fichier sélectionné');
define('TXT_AJOUTER_A_UN_QUESTIONNAIRE', 'Ajouter à un questionnaire');
define('TXT_LANGUE_DE_APERCU', 'Langue de l\'aper&ccedil;u');
define('TXT_LANGUE_DEFAUT', 'Langue par défaut pour aper&ccedil;u et publication');
define('TXT_THEME_DE_APERCU', 'Th&egrave;me de l\'aper&ccedil;u');
define('TXT_THEME_DEFAUT', 'Th&egrave;me par défaut pour aper&ccedil;u et publication');
define('TXT_SUPPRIMER', 'Supprimer');
define('TXT_AJOUTER', 'Ajouter');
define('TXT_INSCRIRE_VOTRE_TEXTE', 'Inscrire votre texte');
define('TXT_CHERCHER', 'Chercher');
define('TXT_CHOISIR_DES_ITEMS_DE_LA_BIBLIOTHEQUE','Choisir des items de la biblioth&egrave;que');
define('TXT_TELECHARGER_QUESTIONNAIRE_WEB','T&eacute;l&eacute;charger le questionnaire Web');
define('TXT_CHOISIR_UN_QUESTIONNAIRE','Choisir un questionnaire');
define('TXT_MESSAGE_LIBELLE_SOLUTION', 'Libell&eacute; Solution');
define('TXT_RESULTATS_OBJET_COURRIEL','Objet du courriel');
define('TXT_RESULTATS_MESSAGE_COURRIEL_SUCCES','Message Courriel envoy&eacute; avec succ&egrave;s');
define('TXT_RESULTATS_MESSAGE_COURRIEL_ERREUR','Message Erreur lors de l\'envoi du courriel');
define('TXT_CALCULER','Calculer');
define('TXT_NE_PAS_CALCULER','Ne pas calculer');
define('TXT_IMPORTER', 'Importer');
define('TXT_POSITION', 'Position');
define('TXT_ID_ITEM', 'id_item');
define('TXT_ID_MEDIA', 'id_media');
define('TXT_ID_QUEST', 'id_questionnaire');
define('TXT_INSCRIRE_NOUVELLE_CATEGORIE_AU_BESOIN', 'Inscrire une nouvelle cat&eacute;gorie au besoin');
define('TXT_VRAI', 'Vrai');
define('TXT_FAUX', 'Faux');
define('TXT_MOT_PASSE_MODIFIE_SUCCES', 'Votre mot de passe a &eacute;t&eacute; modifi&eacute; avec succ&egrave;s');
define('TXT_VEUILLEZ', 'Veuillez');
define('TXT_VOUS_CONNECTER', 'vous connecter');
define('TXT_POUR_CONTINUER', 'pour continuer');
define('TXT_UTILISATEUR_DOIT_DONNER', 'L\'utilisateur doit donner...');
define('TXT_TOUTES_LES_BONNES_REPONSES','toutes les bonnes r&eacute;ponses');
define('TXT_AU_MOINS_UNE_BONNE_REPONSE','au moins une bonne r&eacute;ponse parmi les choix offerts');
define('TXT_DEFINITION_DES_CLASSEURS','&Eacute;tape 1 - D&eacute;finir les classeurs');
define('TXT_EDITION_DU_CONTENU_DES_CLASSEURS','&Eacute;tape 2 - Ajouter des &eacute;l&eacute;ments dans les classeurs');
define('TXT_TYPE_DE_CLASSEUR_ONGLET_ELEMENT','Type de classeur (onglet / &eacute;l&eacute;ment)');
define('TXT_INSCRIRE_VOTRE_LIBELLE','Inscrire le titre de l\'onglet');
define('TXT_AJOUTER_UN_ELEMENT', 'Ajouter un &eacute;l&eacute;ment');
define('TXT_SUPPRIMER_LES_ELEMENTS_SELECTIONNES', 'Supprimer les &eacute;l&eacute;ments s&eacute;lectionn&eacute;s');
define('TXT_RETROACTIONS_POUR_CHAQUE_CLASSEUR', 'R&eacute;troactions pour chaque classeur');
define('TXT_INSCRIRE_RETROACTION_POSITIVE_CLASSEUR', 'Inscrire votre r&eacute;troaction si tous les &eacute;l&eacute;ments de ce classeur ont &eacute;t&eacute; trouv&eacute;s');
define('TXT_INSCRIRE_RETROACTION_NEGATIVE_CLASSEUR', 'Inscrire votre r&eacute;troaction si aucun &eacute;l&eacute;ment de ce classeur n\'a &eacute;t&eacute; trouv&eacute;');
define('TXT_INSCRIRE_RETROACTION_POUR_REPONSE_INCOMPLETE_CLASSEUR', 'Inscrire votre r&eacute;troaction si certains &eacute;l&eacute;ments de ce classeur ont &eacute;t&eacute; oubli&eacute;s');
define('TXT_INSCRIRE_VOTRE_RETROACTION', 'Inscrire votre r&eacute;troaction');
define('TXT_INSCRIRE_VOTRE_RETROACTION_POSITIVE', 'Inscrire votre r&eacute;troaction positive');
define('TXT_INSCRIRE_VOTRE_RETROACTION_NEGATIVE', 'Inscrire votre r&eacute;troaction n&eacute;gative');
define('TXT_ORIENTATION_DES_ELEMENTS_A_CLASSER', 'Orientation des &eacute;l&eacute;ments &agrave; classer');
define('TXT_HORIZONTALE', 'Horizontale');
define('TXT_VERTICALE', 'Verticale');
define('TXT_TEXTE_ELEMENT', 'Texte de l\'&eacute;l&eacute;ment');
define('TXT_IMAGE_ELEMENT', 'Image de l\'&eacute;l&eacute;ment');
define('TXT_BON_CLASSEUR', 'Bon classeur');
define('TXT_CLASSEUR', 'Classeur');
define('TXT_INSCRIRE_VOTRE_RETROACTION_POSITIVE_NEGATIVE', 'Inscrire votre r&eacute;troaction (positive si bonne r&eacute;ponse, n&eacute;gative sinon)');
define('TXT_REPONSE_SUGGEREE', 'R&eacute;ponse sugg&eacute;r&eacute;e');
define('TXT_SOLUTION_DICTEE', 'Solution de la dict&eacute;e');
define('TXT_RETROACTIONS_GLOBALES', 'R&eacute;troactions globales');
define('TXT_RETROACTION_POSITIVE', 'R&eacute;troaction positive');
define('TXT_RETROACTION_NEGATIVE', 'R&eacute;troaction n&eacute;gative');
define('TXT_RETROACTION_POUR_REPONSE_INCOMPLETE', 'R&eacute;troaction pour r&eacute;ponse incompl&egrave;te');
define('TXT_POINTS_RETRANCHES_MOT_MAL_ORTHOGRAPHIES', 'Points retranch&eacute;s pour mots mal orthographi&eacute;s');
define('TXT_ELEMENT_ASSOCIE', '&Eacute;l&eacute;ment associ&eacute;');
define('TXT_RETROACTIONS', 'R&eacute;troactions');
define('TXT_MASQUE', 'Masque');
define('TXT_IMPORTER_ELEMENTS', 'Importer des &eacute;l&eacute;ments');
define('TXT_REPONSE_PREVUE', 'R&eacute;ponse pr&eacute;vue');
define('TXT_RETROACTIONS_POUR_TOUTES_REPONSES_NON_PREVUES', 'R&eacute;troaction pour toutes les r&eacute;ponses non pr&eacute;vues');
define('TXT_INSCRIRE_RETROACTIONS_POUR_TOUTES_REPONSES_NON_PREVUES', 'Inscrire une r&eacute;troaction pour toutes les r&eacute;ponses non pr&eacute;vues (ex.: Erreur inconnue)');
define('TXT_COPIER_COLLER_CODE_HTML_OU_URL_DU_MEDIA', 'Copier/Coller le code HTML d\'int&eacute;gration ou l\'adresse URL du m&eacute;dia');
define('TXT_INSCRIRE_UNE_DESCRIPTION', 'Inscrire une description');
define('TXT_INSCRIRE_UN_COMMENTAIRE_UTILE_POUR_GESTION_ITEMS', 'Inscrire une remarque utile pour la gestion des items');
define('TXT_INSCRIRE_UNE_REMARQUE_UTILE', 'Inscrire une remarque utile pour la gestion de cet élément');
define('TXT_INSCRIRE_UN_MESSAGE_PERSONNALISE_POUR_CET_ITEM_SINON_ETC', 'Inscrire un message personnalis&eacute; pour cet item, sinon le message affich&eacute; dans le questionnaire publi&eacute; sera celui d&eacute;fini dans la section Messages g&eacute;n&eacute;raux de la langue choisie pour le questionnaire');
define('TXT_COULEUR_FOND_ELEMENT','Couleur de fond de l\'élément');
define('TXT_COULEUR_FOND_ELEMENT_A_ASSOCIER','Couleur de fond de l\'élément à associer');
define('TXT_TYPE_AFFICHAGE_DES_ELEMENTS_MASQUES','Type d\'affichage des éléments');
define('TXT_NON_MASQUES_AU_DEBUT','Non masqués au début');
define('TXT_MASQUES_AU_DEBUT','Masqués au début');
define('TXT_POINTS_RETRANCHES_PAR_MAUVAISE_REPONSE', 'Points retranch&eacute;s par mauvaise r&eacute;ponse');
define('TXT_DEFINITION_DES_COULEURS_DE_MARQUAGE', '&Eacute;tape 1 - D&eacute;finir les couleurs de marquage');
define('TXT_INSCRIRE_RETROACTION_POSITIVE_MARQUAGE', 'Inscrire votre r&eacute;troaction si toutes les marques de cette couleur ont &eacute;t&eacute; trouv&eacute;es');
define('TXT_INSCRIRE_RETROACTION_NEGATIVE_MARQUAGE', 'Inscrire votre r&eacute;troaction si aucune marque de cette couleur n\'a &eacute;t&eacute; trouv&eacute;e)');
define('TXT_INSCRIRE_RETROACTION_REPONSE_INCOMPLETE_MARQUAGE', 'Inscrire votre r&eacute;troaction si certaines marques de cette couleur ont &eacute;t&eacute; oubli&eacute;es');
define('TXT_EDITION_DU_TEXTE_ET_DES_MARQUES', '&Eacute;tape 2 - &Eacute;crire le texte et ajouter des marques');
define('TXT_SUPPRIMER_LES_MARQUES_SELECTIONNEES', 'Supprimer les marques s&eacute;lectionn&eacute;es');
define('TXT_AJOUTER_UNE_MARQUE', 'Ajouter une marque');
define('TXT_MARQUE', 'Marque');
define('TXT_COULEUR_DE_CETTE_MARQUE', 'Couleur de cette marque');
define('TXT_RETROACTIONS_POUR_CHAQUE_COULEUR_DE_MARQUAGE', 'R&eacute;troactions pour chaque couleur de marquage');
define('TXT_CHOISIR_UNE_COULEUR', 'Choisir une couleur');
define('TXT_BLANC', 'Blanc');
define('TXT_BEIGE', 'Beige');
define('TXT_GRIS', 'Gris');
define('TXT_BLEU', 'Bleu');
define('TXT_ROSE', 'Rose');
define('TXT_JAUNE', 'Jaune');
define('TXT_VERT', 'Vert');
define('TXT_POURPRE', 'Pourpre');
define('TXT_ORANGE', 'Orange');
define('TXT_TURQUOISE', 'Turquoise');
define('TXT_NOIR', 'Noir');
define('TXT_ROUGE', 'Rouge');
define('TXT_FICHIER_A_IMPORTER', 'Fichier &agrave; importer');
define('TXT_RESULTATS_DE_L_IMPORTATION', 'R&eacute;sultats de la dernière importation');
define('TXT_INSCRIRE_VOTRE_CONSIGNE', 'Inscrire la consigne');
define('TXT_INSCRIRE_NOUVELLE_COLLECTION_AU_BESOIN', 'Inscrire une nouvelle collection au besoin');
define('TXT_POUR_REPONSE_BREVE_SEULEMENT', 'Pour r&eacute;ponse br&egrave;ve seulement');
define('TXT_CONTOUR_DES_ZONES_SUR_IMAGE_WEB', 'Couleur de contour des zones sur l\'image');
define('TXT_DEFINITION_DES_TYPES_DE_LACUNE', '&Eacute;tape 1 - D&eacute;finir le type de lacune');
define('TXT_TYPE_DE_LACUNE', 'Type de lacune');
define('TXT_PETIT_CHAMP_TEXTE', 'Petit champ texte');
define('TXT_MOYEN_CHAMP_TEXTE', 'Moyen champ texte');
define('TXT_GRAND_CHAMP_TEXTE', 'Grand champ texte');
define('TXT_GLISSER_DEPOSER', 'Glisser / D&eacute;poser');
define('TXT_EDITION_DU_TEXTE_ET_DES_LACUNES', '&Eacute;tape 2 - &Eacute;crire le texte et ajouter des lacunes');
define('TXT_SUPPRIMER_LES_LACUNES_SELECTIONNEES', 'Supprimer les lacunes s&eacute;lectionn&eacute;es');
define('TXT_AJOUTER_UNE_LACUNE', 'Ajouter une lacune');
define('TXT_LACUNE', 'Lacune');
define('TXT_MAUVAISE_REPONSE', 'Mauvaise réponse');
define('TXT_TEXTE_AVEC_MARQUES', 'Texte avec marques');
define('TXT_MARQUES', 'Marques');
define('TXT_COULEURS', 'Couleurs');
define('TXT_ELEMENT_SANS_TEXTE', 'Élément sans texte');
define('TXT_ONGLET_SANS_IMAGE', 'Onglet sans image');
define('TXT_MENU_DEROULANT', 'Menu déroulant');
define('TXT_NOUVELLE_IMPORTATION', 'Nouvelle importation');
define('TXT_AUCUNE_INFORMATION', 'Aucune information disponible dans la session courante');
define('TXT_DEMANDER_UN_COMPTE', 'Demander un compte');
define('TXT_DEMANDER_UN_COMPTE_LIGNE1', 'Envoyez les renseignements suivants et l\'administrateur du site vous fera parvenir un message de confirmation par courriel.');
define('TXT_MOT_DE_PASSE', 'Mot de passe');
define('TXT_CONFIRMER_LE_MOT_DE_PASSE', 'Confirmer le mot de passe');
define('TXT_NOUVEL_UTILISATEUR', 'Nouvel utilisateur');
define('TXT_NOUVEL_UTILISATEUR_LIGNE1', 'Vous vous connectez à Netquiz Web pour la première fois. Tous les contenus que vous créez avec cette application (items, questionnaires, médias, glossaire, etc.) sont conservés dans un projet. Remplissez le formulaire qui suit pour créer votre premier projet. Vous pourrez éventuellement créer d\'autres projets pour organiser vos contenus selon vos besoins. <span class="ital">(Pour en savoir plus sur la notion de projet, consultez l\'<a href="#" onClick="NewWindow(\'http://aide.ccdmd.qc.ca/nqw/fr/content/ajouter-de-nouveaux-projets\',\'aide\',\'1024\',\'800\',\'yes\',\'yes\',\'yes\')">aide</a>.)</span>');
define('TXT_TITRE_DU_PROJET', 'Titre du projet');
define('TXT_IDENTIFIANT_UNIQUE_DU_PROJET', 'Identifiant unique du projet');
define('TXT_IDENTIFIANT_UNIQUE_DU_PROJET_CONTRAINTES', 'Seuls les lettres minuscules, chiffres, tirets et soulignés sont autorisés');
define('TXT_INSCRIRE_UN_IDENTIFIANT_UNIQUE', 'Inscrire un identifiant unique. Une fois sauvegardé, cet identifiant ne pourra plus être modifié.');
define('TXT_CREER_ET_COMMENCER', 'Créer et commencer');
define('TXT_NETQUIZ_WEB_ADMIN', 'Administration');
define('TXT_GESTION', 'Gestion');
define('TXT_PROJETS', 'Projets');
define('TXT_TOUS_LES_PROJETS', 'Tous les projets');
define('TXT_PROJET', 'Projet');
define('TXT_UTILISATEURS', 'Utilisateurs');
define('TXT_TOUS_LES_UTILISATEURS', 'Tous les utilisateurs');
define('TXT_AJOUTER_UN_PROJET', 'Ajouter un projet');
define('TXT_IDENTIFIANT', 'Identifiant');
define('TXT_RESPONSABLE', 'Responsable');
define('TXT_RESPONSABLE_DU_PROJET', 'Responsable du projet');
define('TXT_AFFICHER_TOUS_LES_RESPONSABLES', 'Afficher tous les responsables');
define('TXT_COLLABORATEURS_ACTUELS_DE_CE_PROJET', 'Collaborateurs actuels');
define('TXT_COLLABORATEURS_INVITES_A_CE_PROJET', 'Collaborateurs invités - en attente d\'une réponse');
define('TXT_COLLABORATEURS_INSTRUCTIONS', 'Les personnes qui n\'ont pas de compte seront invitées à s\'en créer un');
define('TXT_COLLABORATEURS_INSTRUCTIONS2', 'Inscrire le courriel de la personne avec qui vous voulez collaborer');
define('TXT_NOM_PRENOM', 'Nom, prénom');
define('TXT_NOTIFIER_RESPONSABLE_ET_COLLABORATEURS', 'Notifier le responsable et les collaborateurs des modifications apportées');
define('TXT_NOTIFIER_COLLABORATEURS', 'Notifier les collaborateurs des modifications apportées');
define('TXT_AJOUTER_UN_UTILISATEUR', 'Ajouter un utilisateur');
define('TXT_AFFICHER_TOUS_LES_PROJETS', 'Afficher tous les projets');
define('TXT_PROJET_COURANT', 'Projet courant');
define('TXT_PROJET_COURANT_A_LA_CONNEXION', 'Projet courant à la connexion');
define('TXT_LISTE_PROJETS_DE_CET_UTILISATEUR', 'Liste des projets de cet utilisateur');
define('TXT_ADMINISTRATEUR', 'Administrateur');
define('TXT_NOTIFIER_UTILISATEUR_DES_MODIFICATIONS', 'Notifier l\'utilisateur des modifications apportées');
define('TXT_DEMANDE_TRANSMISE', 'Votre demande a été transmise. Son approbation peut prendre 1 ou 2 jours ouvrables.');
define('TXT_DEMANDE_ACTIVATION_COMPTE_SUJET','Demande d\'activation d\'un compte Netquiz Web');
define('TXT_DEMANDE_ACTIVATION_COMPTE_TEXTE','Un nouvel utilisateur s\'est inscrit. Sa demande nécessite votre approbation :');
define('TXT_COMPTE','Compte');
define('TXT_MES_PROJETS','Mes projets');
define('TXT_DERNIER_ACCES', 'Dernier accès');
define('TXT_ADMINISTRATION', 'Administration');
define('TXT_COURRIEL_APPROBATION_OBJET', 'Netquiz Web - Demande de compte');
define('TXT_COURRIEL_APPROBATION_BONJOUR','Bonjour');
define('TXT_COURRIEL_APPROBATION_LIGNE1','Votre demande de compte a été approuvée. Vous pouvez accéder à l\'application en cliquant sur le lien suivant:');
define('TXT_COURRIEL_APPROBATION_LIGNE2','Si ce lien ne fonctionne pas, veuillez le copier-coller dans la barre d\'adresse de votre navigateur.');
define('TXT_COURRIEL_APPROBATION_MERCI','Merci d\'utiliser Netquiz Web.');
define('TXT_COURRIEL_REFUS_OBJET', 'Netquiz Web - Demande de compte');
define('TXT_COURRIEL_REFUS_BONJOUR','Bonjour');
define('TXT_COURRIEL_REFUS_LIGNE1','Votre demande de compte a été refusée.');
define('TXT_COURRIEL_REFUS_LIGNE2','Veuillez contacter l\'administrateur pour plus d\'informations.');
define('TXT_LANGUE_INTERFACE','Langue de l\'interface');
define('TXT_APROPOS_COMMENTAIRE_1','Votre opinion compte beaucoup pour les artisans qui ont travaill&eacute; &agrave; la conception et &agrave; la r&eacute;alisation de ce produit. La section Commentaires de la fiche du produit <em>Netquiz Web</em>, sur le site du CCDMD, vous permet d\'&eacute;crire vos commentaires et d&rsquo;&eacute;valuer ce produit. Vous pouvez aussi consulter la section Foire aux questions.');
define('TXT_APROPOS_COMMENTAIRE_ALLER_SECTION','Allez &agrave; la section');
define('TXT_APROPOS_COMMENTAIRE_COMMENTAIRES','Commentaires');
define('TXT_APROPOS_COMMENTAIRE_URL','http://www.ccdmd.qc.ca/catalogue/netquiz-web');
define('TXT_DROITS_UTILISATION_NQW','<em>Netquiz web</em> est un <a href="#" onClick="window.open(\'https://github.com/CCDMD/netquizweb/blob/master/LICENSE\')">logiciel libre</a>. Vous pouvez contribuer au développement de cette application en allant sur le site <a href="#" onClick="window.open(\'https://github.com/CCDMD/netquizweb\')">Github</a>. Pour plus de renseignements, communiquer avec le CCDMD par courriel à <a href="mailto:info@ccdmd.qc.ca">info@ccdmd.qc.ca</a>.');
define('TXT_GENERIQUE_LIGNE_1',' <p><em>Netquiz Web</em> est une production du Centre coll&eacute;gial de d&eacute;veloppement de mat&eacute;riel didactique (CCDMD, 2014). Ce produit est d&eacute;velopp&eacute; et maintenu par le CCDMD et par la communaut&eacute; du logiciel libre sur <a href="#" onClick="window.open(\'https://github.com/CCDMD/netquizweb\')">GitHub</a>.</p>');
define('TXT_GENERIQUE_LIGNE_2','<h3>Conception de l\'application</h3>Lucie Tr&eacute;panier, CCDMD<br />Christine Blais<br /><br />');
define('TXT_GENERIQUE_LIGNE_3','<h3>Conception informatique et programmation de l\'application</h3>Richard Dumoulin, e-Summum inc.<br /><br />');
define('TXT_GENERIQUE_LIGNE_4','<h3>Programmation des th&egrave;mes</h3>Robert Szczech<br /><br />');
define('TXT_GENERIQUE_LIGNE_5','<h3>Infographie de l\'application et des thèmes</h3>Christine Blais<br /><br />');
define('TXT_GENERIQUE_LIGNE_6','<h3>Int&eacute;gration de l\'interface de l\'application</h3>V&eacute;ronique Pivetta<br /><br />');
define('TXT_GENERIQUE_LIGNE_7','<h3>R&eacute;vision informatique</h3>Sylvain Gagnon, CCDMD<br /><br />');
define('TXT_GENERIQUE_LIGNE_8','<h3>Traduction anglaise</h3>Paulette Cake, CCDMD<br /><br />');
define('TXT_GENERIQUE_LIGNE_9','<h3>R&eacute;daction de l\'aide</h3>Raymond Cantin, CCDMD<br /><br />');
/*define('TXT_GENERIQUE_LIGNE_10','<h3>R&eacute;vision linguistique (français)</h3>&agrave; venir...<br /><br />');
define('TXT_GENERIQUE_LIGNE_11','<h3>R&eacute;vision linguistique (anglais)</h3>&agrave; venir...<br /><br />');*/
define('TXT_GENERIQUE_LIGNE_10','');
define('TXT_GENERIQUE_LIGNE_11','<h3>Responsable du projet</h3>Lucie Tr&eacute;panier, CCDMD<br /><br />');
define('TXT_GENERIQUE_LIGNE_12','<br />Cette application utilise le plugiciel jQuery <a href="#" onClick="window.open(\'https://github.com/mjsarfatti/nestedSortable\')">nestedSortable</a>, développé par Manuele J Sarfatti (licence MIT), et la biblioth&egrave;que de widgets <a href="#" onClick="window.open(\'http://www.jqwidgets.com/license/\')">jQWidgets</a>, sous la licence <em>Creative Commons Attribution-NonCommercial 3.0</em> (<a href="#" onClick="window.open(\'http://creativecommons.org/licenses/by-nc/3.0/\')">CC BY-NC 3.0</a>). N.B. La biblioth&egrave;que jQWidgets (&copy; 2011-2014) n\'est pas gratuite pour les applications commerciales.');
define('TXT_INTRO_LIGNE_1','<em>Netquiz Web</em> est une application multilingue, multiplateforme et multiutilisateur qui permet de constituer, sur le Web, une banque d\'items de 14 types diff&eacute;rents (Associations, Choix multiples, Classement, Damier, D&eacute;veloppement, Dict&eacute;e, Marquage, Mise en ordre, R&eacute;ponse br&egrave;ve, R&eacute;ponses multiples, Texte lacunaire, Vrai ou faux, Zones &agrave; identifier, Page) et de publier des exercices formatifs, des jeux-questionnaires ou des tests d&rsquo;un simple clic. Dans tous les types d\'items, il est possible d&rsquo;ins&eacute;rer des images, des textes, des sons et des s&eacute;quences vid&eacute;o et de personnaliser de nombreux param&egrave;tres. On peut &eacute;galement ajouter un glossaire, de sorte que des termes et expressions s\'affichent en relief dans le questionnaire, permettant aux r&eacute;pondants d\'obtenir leur d&eacute;finition sous forme de texte, d\'image, de vid&eacute;o, de son ou de liens.<br /><br /><em>Netquiz Web</em> ne permet pas encore de colliger les r&eacute;sultats. Cette fonction pourrait, en fonction de la demande, &ecirc;tre ajout&eacute;e dans les prochaines années. En attendant, les utilisateurs qui veulent faire des examens sommatifs ou&nbsp;compiler les r&eacute;sultats des exercices qu\'ils mettent en ligne peuvent t&eacute;l&eacute;charger gratuitement le logiciel <a href="#" onClick="window.open(\'http://www.ccdmd.qc.ca/catalogue/netquiz-pro-29\')">Netquiz Pro 2.9</a>.<br /><br /><b>Note&nbsp;:</b> Pour r&eacute;cup&eacute;rer une ancienne banque de questions et de questionnaires produite avec <em>Netquiz Pro</em>, il suffit d\'ouvrir le fichier &laquo;&nbsp;.npro&nbsp;&raquo; avec le logiciel <a href="#" onClick="window.open(\'http://www.ccdmd.qc.ca/catalogue/netquiz-pro-4\')">Netquiz Pro 4</a> version 4.9 ou sup&eacute;rieure, puis de choisir la commande &laquo;&nbsp;Exporter au format XML&nbsp;&raquo; du menu &laquo;&nbsp;Fichier&nbsp;&raquo;. Un r&eacute;pertoire portant le nom du&nbsp;fichier &laquo;&nbsp;.npro&nbsp;&raquo; suivi de &laquo;&nbsp;_XML&nbsp;&raquo; appara&icirc;t sur le bureau de l\'ordinateur. Ce r&eacute;pertoire doit &ecirc;tre compress&eacute; (n.b. sous MAC OS X, il faut compresser le contenu de ce r&eacute;pertoire et non le r&eacute;pertoire lui-m&ecirc;me). Enfin, dans <em>Netquiz Web</em>, il suffit de choisir la commande&nbsp;&laquo;&nbsp;Importer des &eacute;l&eacute;ments &raquo; apparaissant dans le menu contextuel de &laquo;&nbsp;Mes questionnaires&nbsp;&raquo; et de suivre les instructions.');
define('TXT_CONFIRMER_REFUS_COMPTE', 'Êtes-vous certain(e) de vouloir refuser ce compte?');
define('TXT_NOUVEAU_PROJET', 'Projet sans titre');
define('TXT_CONFIRMER_MISE_CORBEILLE_PROJET', "Les questionnaires publiés dans les projets mis à la corbeille seront perdus et cette action est irréversible.\\n\\nDésirez-vous continuer?");
define('TXT_CONFIRMER_SUPPRESSION_ELEMENTS', "La suppression des éléments sélectionnés est irréversible.\\n\\nATTENTION! Si cette sélection contient des projets, tous les éléments qu'ils comportent (Questionnaires, Items, Médias, Termes du glossaire, etc.) seront eux aussi supprimés de manière irréversible.\\n\\nDésirez-vous continuer?");
define('TXT_STATUT_DU_PROJET', 'Statut du projet');
define('TXT_DATE_ENVOI_INVITATION', 'Date d\'envoi de l\'invitation');
define('TXT_ENVOI_COURRIEL', 'Envoyer un courriel');
define('TXT_RETIRER_ACCESS', 'Retirer l\'accès au projet');
define('TXT_SUPPRIMER_INVITATION', 'Supprimer l\'invitation');
define('TXT_INVITER_NOUVEAU_COLLABORATEUR', 'Inviter un nouveau collaborateur');
define('TXT_ENVOI', 'Envoyer l\'invitation');
define('TXT_COLLABORATEUR_NOTE', 'Attention! Les collaborateurs peuvent ajouter, modifier, supprimer le contenu de votre projet.<br />Les collaborateurs seront prévenus par courriel des changements apportés au partage de ce projet.');
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_OBJET', "Invitation à collaborer dans un projet Netquiz Web");
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_BONJOUR','Bonjour,');
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_LIGNE1A','vous invite à collaborer au projet');
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_LIGNE1B','de Netquiz Web');
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_LIGNE2','Pour accéder au projet, il suffit de cliquer sur le lien suivant ou de le copier dans la barre d\'adresse de votre navigateur: ');
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_LIGNE3','Vous aurez d\'abord à remplir un formulaire pour créer votre compte Netquiz Web.');
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_MERCI','Merci!');		
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_SIGNATURE','L\'équipe de soutien technique de Netquiz Web');
define('TXT_COURRIEL_COLLABORATEUR_RETRAIT_OBJET', "Fin de collaboration à un projet de Netquiz Web");
define('TXT_COURRIEL_COLLABORATEUR_RETRAIT_BONJOUR','Bonjour');
define('TXT_COURRIEL_COLLABORATEUR_RETRAIT_LIGNE1A','Votre nom a été retiré de la liste des collaborateurs du projet');
define('TXT_COURRIEL_COLLABORATEUR_RETRAIT_LIGNE1B','de');
define('TXT_COURRIEL_COLLABORATEUR_RETRAIT_LIGNE2','Pour toute information, veuillez contacter cette personne.');
define('TXT_COURRIEL_COLLABORATEUR_RETRAIT_MERCI','Merci!');
define('TXT_COURRIEL_COLLABORATEUR_RETRAIT_SIGNATURE','L\'équipe de soutien technique de Netquiz Web');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_OBJET', "Modifications apportées à un projet de Netquiz Web");
define('TXT_COURRIEL_PROJET_MODIFICATIONS_BONJOUR','Bonjour');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_LIGNE1A','À l\'adresse URL');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_LIGNE1B',', une ou plusieurs modifications ont été effectuées au projet «');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_LIGNE1C','» auquel vous collaborez:');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_TITRE1',' - Le titre du projet a été modifié de «');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_TITRE2','» à «');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_TITRE3','».');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_RESPONSABLE1',' - Le responsable du projet a été modifié de «');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_RESPONSABLE2','» à «');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_RESPONSABLE3','».');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_STATUT_INACTIF',' - Le projet est maintenant inactif.');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_STATUT_ACTIF',' - Le projet est maintenant actif.');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_MERCI','Merci!');
define('TXT_COURRIEL_NOUVEAU_RESPONSABLE_OBJET', "Changement de responsable pour un projet de Netquiz Web");
define('TXT_COURRIEL_NOUVEAU_RESPONSABLE_BONJOUR','Bonjour');
define('TXT_COURRIEL_NOUVEAU_RESPONSABLE_LIGNE1A','vous a nommé responsable pour le projet «');
define('TXT_COURRIEL_NOUVEAU_RESPONSABLE_LIGNE1B','» dans Netquiz Web.');
define('TXT_COURRIEL_NOUVEAU_RESPONSABLE_LIGNE2','Vous pouvez accéder à Netquiz Web en utilisant le lien ci-dessous:');
define('TXT_COURRIEL_NOUVEAU_RESPONSABLE_SIGNATURE','L\'équipe de soutien technique de Netquiz Web');
define('TXT_COURRIEL_NOUVEAU_RESPONSABLE_MERCI','Merci!');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_SIGNATURE','L\'équipe de soutien technique de Netquiz Web');
define('TXT_NOMMER_RESPONSABLE','Nommer comme responsable du projet');
define('TXT_NOMMER_RESPONSABLE_AVERTISSEMENT','En nommant une autre personne responsable du projet, vous devenez collaborateur de ce projet et ne disposerez plus des droits pour le gérer. Désirez-vous continuer?');
define('TXT_ACTIF', 'Actif');
define('TXT_INACTIF', 'Inactif');
define('TXT_RETOUR', 'Retour');
define('TXT_ME_RETIRER_DE_LA_LISTE_DES_COLLABORATEURS', 'Me retirer de la liste des collaborateurs');
define('TXT_CONFIRMER_RETRAIT_DE_LA_LISTE_DES_COLLABORATEURS' , 'Voulez-vous vraiment vous retirer de la liste des collaborateurs de ce projet? Cette action est irréversible.');
define('TXT_INFORMATION', 'Profil');
define('TXT_PREFERENCES', 'Préférences');
define('TXT_ENVOYER_UN_COURRIEL','Envoyer un courriel');
define('TXT_NOMMER_RESPONSABLE_AVERTISSEMENT_ADMIN','En nommant une autre personne responsable du projet, le responsable actuel deviendra collaborateur de ce projet et ne disposera plus des droits pour le gérer. Désirez-vous continuer?');
define('TXT_APPROUVER_LA_DEMANDE', 'Approuver la demande');
define('TXT_AFFICHER_TOUS_LES_UTILISATEURS', 'Afficher tous les utilisateurs');
define('TXT_AFFICHER_TOUS_LES_UTILISATEURS_ACTIFS', 'Afficher les utilisateurs actifs');
define('TXT_AFFICHER_TOUS_LES_UTILISATEURS_VERROUILLES', 'Afficher les utilisateurs verrouillés');
define('TXT_AFFICHER_TOUS_LES_UTILISATEURS_EN_ATTENTE_APPROBATION', 'Afficher les utilisateurs en attente d\'approbation');
define('TXT_AFFICHER_TOUS_LES_UTILISATEURS_AVEC_ACCES_REFUSES', 'Afficher les utilisateurs dont l\'accès a été refusé');
define('TXT_ROLE', 'Rôle');
define('TXT_UTILISATEUR', 'Utilisateur');
define('TXT_INSCRIRE_NOUVEAU_MOT_PASSE_SI_DESIRE', 'Inscrire un nouveau mot de passe si désiré');
define('TXT_REPETER_NOUVEAU_MOT_PASSE','Répéter le nouveau mot de passe');
define('TXT_NB_MAUVAIS_ESSAIS_MDP', 'Nombre de connexions incorrectes');
define('TXT_COMPTE_VERROUILLE', 'Le compte est verrouillé après');
define('TXT_NOUVEL_UTILISATEUR_SANS_NOM', 'Nouvel utilisateur sans nom');
define('TXT_CONFIRMER_APPROBATION', 'Désirez-vous approuver l\'accès des utilisateurs sélectionnés?');
define('TXT_COLLABORATION', 'Collaboration');
define('TXT_TEXTES', 'Textes');
define('TXT_MESSAGE_AVERTISSEMENT_TEMPORAIRE', 'Message d\'avertissement sur la page de connexion');
define('TXT_INSCRIRE_MESSAGE_AVERTISSEMENT_TEMPORAIRE', 'Inscrire un message d\'avertissement sur la page de connexion');
define('TXT_TEXTE_SUPPLEMENTAIRE_MOT_BIENVENUE', 'Texte supplémentaire au mot de bienvenue');
define('TXT_INSCRIRE_TEXTE_SUPPLEMENTAIRE_MOT_BIENVENUE', 'Inscrire un texte supplémentaire au mot de bienvenue');
define('TXT_DERNIERE_EXPORTATION', 'Dernière exportation');
define('TXT_JS_CONFIRMER_INDEXATION1', 'Cette fonction met à jour les index de recherche des éléments de type «');
define('TXT_JS_CONFIRMER_INDEXATION2', '» et peut prendre du temps.\\n\\nDésirez-vous lancer l\\\'indexation?');
define('TXT_SUPPRIMER_CET_ELEMENT', 'Supprimer cet élément');
define('TXT_SUPPRIMER_CETTE_MARQUE', 'Supprimer cette marque');
define('TXT_TEXTE_DE_LA_MARQUE', 'Texte de la marque');
define('TXT_SUPPRIMER_CETTE_LACUNE', 'Supprimer cette lacune');
define('TXT_LEXIQUE', 'Glossaire');
define('TXT_MESSAGE_DE_CONFIRMATION_RETOUR_ACCUEIL', 'Message de confirmation pour le retour à la page d\'accueil');
define('TXT_LANCER_INDEXATION', 'Lancer l\'indexation des éléments');
define('TXT_COURRIEL_CREATION_COMPTE_ADMIN', 'Netquiz Web - Création d\'un compte administrateur');
define('TXT_COURRIEL_COMPTE_ADMIN_BONJOUR','Bonjour');
define('TXT_COURRIEL_COMPTE_ADMIN_LIGNE1','Votre compte administrateur a été créé. Vous pouvez accéder à l\'application en cliquant sur le lien suivant:');
define('TXT_COURRIEL_COMPTE_ADMIN_LIGNE2','Si ce lien ne fonctionne pas, veuillez le copier-coller dans la barre d\'adresse de votre navigateur.');
define('TXT_COURRIEL_COMPTE_ADMIN_MERCI','Merci d\'utiliser Netquiz Web.');
define('TXT_MES_TERMES','Mes termes');
define('TXT_NOUVEAU_TERME', 'Terme sans titre');
define('TXT_TERMES','Termes');
define('TXT_TERME','Terme');
define('TXT_VARIANTES','Variantes');
define('TXT_DEFINITION','Définition');
define('TXT_AJOUTER_UN_NOUVEAU_TERME','Ajouter un nouveau terme');
define('TXT_INSCRIRE_VARIANTES','Inscrire les variantes');
define('TXT_INSCRIRE_DEFINITION','Inscrire la définition');
define('TXT_INSERER_UNE_ADRESSE_URL','Inscrire une adresse URL complète (inclure le http:// ou https://)');
define('TXT_INSERER_UNE_ADRESSE_URL_VERS_UN_DOCUMENT','Inscrire l\'adresse URL d\'un document PDF, d\'une image, d\'une vidéo, d\'un site, etc.');
define('TXT_SEPAREES_PAR_DES_RETOUR','séparées chacune par un retour de chariot');
define('TXT_VOULEZ_VOUS_SUPPRIMER_CE_TERME','Voulez-vous vraiment supprimer ce terme? Cette action est irréversible.');
define('TXT_VOULEZ_VOUS_SUPPRIMER_CES_TERMES','Voulez-vous vraiment supprimer ce(s) terme(s)? Cette action est irréversible.');
define('TXT_TERMES_A_INCLURE','Termes de la bibliothèque à inclure dans le glossaire de ce questionnaire');
define('TXT_INSCRIRE_UN_COMMENTAIRE_UTILE_POUR_GESTION_QUESTIONNAIRES', 'Inscrire une remarque utile pour la gestion des questionnaires');
define('TXT_AVERTISSEMENT_FIN_SESSION', 'Votre session Netquiz Web est restée inactive trop longtemps et va expirer sous peu. Veuillez enregistrer vos modifications dès maintenant, afin de la réactiver.');
define('TXT_AVERTISSEMENT_SESSION_EXPIREE', 'Votre session Netquiz Web a expiré. Vous n\'êtes plus en mesure d\'enregistrer vos modifications. Au besoin, veuillez les prendre en note ou les copier dans un fichier externe, afin de reprendre votre travail lorsque vous vous connecterez de nouveau.');
define('TXT_AVERTISSEMENT_ANNULER', 'Voulez-vous vraiment annuler les modifications? Cette action est irréversible.');
define('TXT_AVERTISSEMENT_DESACTIVER_PUBLICATON', 'Voulez-vous vraiment désactiver cette publication? Cette action est irréversible.');
define('TXT_AVERTISSEMENT', 'Avertissement');
define('TXT_VERSION_NQW', 'Version actuelle de Netquiz Web');
define('TXT_ID_LANGUE', 'ID Langue');
define('TXT_ID_TERME', 'ID Terme');
define('TXT_ID_COLLECTION', 'ID Collection');
define('TXT_ID_CATEGORIE', 'ID Catégorie');
define('TXT_INSTALLATION_NETQUIZ_WEB', 'Installation de Netquiz Web');
define('TXT_TOUS_LES_PREREQUIS_TECHNIQUES_ONT_ETE_VALIDES', 'Tous les prérequis techniques nécessaires à l\'installation ont été validés avec succès. ');
define('TXT_ETAPE_1_DE_3', 'Étape 1 de 3&nbsp;: Vérification des prérequis techniques nécessaires à l\'installation');
define('TXT_ETAPE_2_DE_3', 'Étape 2 de 3&nbsp;: Création d\'un compte administrateur');
define('TXT_ETAPE_3_DE_3', 'Étape 3 de 3&nbsp;: Confirmation de l\'installation');
define('TXT_SAISIR_INFOS_ADMIN', 'Veuillez saisir les informations du compte administrateur');
define('TXT_INSTALLATION_TERMINEE', 'L\'installation de Netquiz Web est maintenant terminée');
define('TXT_DEBUTER_UTILISATION', 'Vous pouvez commencer à utiliser Netquiz Web');
define('TXT_ESSAYER_A_NOUVEAU', 'Essayer à nouveau');
define('TXT_CONTINUER', 'Continuer');

define('TXT_PERMETTRE_ACCES', 'Remettre le site en ligne');
define('TXT_FERMER_ACCES', 'Mettre en mode maintenance');
define('TXT_AFFICHER_TOUS_LES_ADMINISTRATEURS', 'Afficher tous les administrateurs');
define('TXT_CONSIGNE_PUBLICATION1', 'Attention! Chaque questionnaire doit être publié à une adresse URL unique, que vous pouvez transmettre à vos répondants.');
define('TXT_CONSIGNE_PUBLICATION2', 'Il est possible de republier un questionnaire en conservant la même adresse URL. Si vous voulez publier à une nouvelle adresse, l\'ancienne publication sera détruite et remplacée par la nouvelle.');
define('TXT_MAINTENANCE_LIGNE1', 'ATTENTION! L\'exécution de ces fonctions de maintenance peut avoir un impact temporaire sur les performances du site ou l\'accès au site par les utilisateurs. Veuillez les activer au moment opportun et à bon escient.');
define('TXT_VERSION_ACTUELLE', 'Version actuelle de Netquiz Web');
define('TXT_MAINTENANCE_DU_SITE', 'Maintenance du site');
define('TXT_MODE_MAINTENANCE', 'N. B. En mode maintenance, l\'application Netquiz Web n\'est accessible qu\'aux administrateurs du site.');
define('TXT_SAUVEGARDE_DE_LA_BASE_DE_DONNEES', 'Sauvegarde de la base de données');
define('TXT_EXPORTER_FORMAT_SQL', 'Exporter la base de données');
define('TXT_INDEXATION', 'Indexation des tables de la base de données');
define('TXT_NOTE_SAUVEGARDE', 'N. B. Certaines mises à jour peuvent modifier la base de données de Netquiz Web. Exportez sur votre ordinateur une copie de sûreté de la base de données actuelle, au cas où vous auriez besoin de revenir à cette version.');
define('TXT_NOTE_INDEXATION1', 'N. B. L\'indexation des tables de la base de données de Netquiz Web peut être nécessaire après certaines mises à jour. N\'effectuez cette opération que si vous recevez un message à cet effet.');
define('TXT_NOTE_INDEXATION2', 'Si vous indexez l\'une de ces tables, veuillez attendre le message de confirmation avant de continuer.');
define('TXT_INDEXER_CATEGORIES', 'Indexer les catégories');
define('TXT_INDEXER_COLLECTIONS', 'Indexer les collections');
define('TXT_INDEXER_ITEMS', 'Indexer les items');
define('TXT_INDEXER_LANGUES', 'Indexer les langues');
define('TXT_INDEXER_MEDIAS', 'Indexer les médias');
define('TXT_INDEXER_PROJETS', 'Indexer les projets');
define('TXT_INDEXER_QUESTIONNAIRES', 'Indexer les questionnaires');
define('TXT_INDEXER_UTILISATEURS', 'Indexer les utilisateurs');
define('TXT_COORDONNEE_X', 'Coordonnée x');
define('TXT_COORDONNEE_Y', 'Coordonnée y');
define('TXT_AVERTISSEMENT_NOUVEAU_VERROU', 'DANGER! Une ou plusieurs personnes travaillent actuellement sur le même élément que vous. Cette situation pourrait entraîner des pertes de données si vous enregistrez au même moment. Veuillez contacter ces personnes au besoin: ');
define('TXT_MAINTENANCE', 'Maintenance');


/** Langue **/ 
define('CHANGER_LANGUE_FR', 'fr_CA');
define('CHANGER_LANGUE_EN', 'en_CA');

/** Messages de confirmation */
define("MSG_001", "Les informations ont &eacute;t&eacute; enregistr&eacute;es avec succ&egrave;s.");
define("MSG_002", "");
define("MSG_003", "Le mot de passe a &eacute;t&eacute; mis &agrave; jour avec succ&egrave;s.");
define("MSG_004", "Les items sélectionnés ont été ajoutés au questionnaire.");
define("MSG_005", "Un courriel contenant les instructions pour r&eacute;initialiser votre mot de passe vous a &eacute;t&eacute; envoy&eacute;.");
define("MSG_006", "Les items de cette section ne comportent aucune erreur.");
define("MSG_007", "La publication du questionnaire a &eacute;t&eacute; d&eacute;sactiv&eacute; avec succ&egrave;s.");
define("MSG_008", "Le questionnaire a &eacute;t&eacute; publi&eacute; avec succ&egrave;s&nbsp;:");
define("MSG_009", "Importation complétée pour le média ");
define("MSG_010", "Importation complétée pour l'item ");
define("MSG_011", "Importation complétée pour le questionnaire ");
define("MSG_012", "La demande de compte a été approuvée.");
define("MSG_013", "La demande de compte a été refusée.");
define("MSG_014", "L'item sélectionné a été ajouté dans ce questionnaire.");
define("MSG_015", "Le nouveau projet a été créé et est prêt à être utilisé.");
define("MSG_016", "L'invitation a été envoyée par courriel.");
define("MSG_017", "Le nouveau collaborateur a été ajouté au projet et a été informé par courriel.");
define("MSG_018", "L'invitation pour ce collaborateur a été retirée.");
define("MSG_019", "Les invitations pour ces collaborateurs ont été retirées.");
define("MSG_020", "L'accès au projet pour ce collaborateur a été retirée.");
define("MSG_021", "Les accès au projet pour ces collaborateurs ont été retirée.");
define("MSG_022", "Les projets sélectionnés ont été mis à la corbeille.");
define("MSG_023", "Les projets sélectionnés ont été mis à la corbeille (sauf ceux pour lesquels vous n'êtes pas le propriétaire).");
define("MSG_024", "Le changement de rôle a été effectué avec succès.");
define("MSG_025", "Vous ne pouvez pas vous retirer de la liste de collaborateurs dans les projets sélectionnés où vous êtes responsable.");
define("MSG_026", "Certains projets parmi ceux sélectionnés ne peuvent pas être mis à la corbeille, car vous n'êtes pas le responsable.");
define("MSG_027", "Vous avez été retirés de la liste des collaborateurs pour ces projets.");
define("MSG_028", "Vous avez été retirés de la liste des collaborateurs pour ces projets (sauf ceux dont vous êtes propriétaires).");
define("MSG_029", "Veuillez enregistrer les nouvelles informations du projet avant de nommer un nouveau responsable.");
define("MSG_030", "Les utilisateurs sélectionnés ont été mis à la corbeille.");
define("MSG_031", "Certains utilisateurs sélectionnés n'ont pas le statut «En attente d'une approbation». Impossible de continuer.");
define("MSG_032", "Les utilisateurs sélectionnés ont maintenant accès à l'application.");
define("MSG_033", "L'indexation a été complétée avec succès.");
define("MSG_034", "Tous les prérequis techniques ont été validés avec succès.");
define("MSG_035", "Une ou plusieurs langues n'ont pu être mises à la corbeille car elles sont requises par l'application.");
define("MSG_036", "Un ou plusieurs utilisateurs n'ont pu être mis à la corbeille car ils sont administrateurs de l'application.");
define("MSG_037", "Importation complétée pour la collection ");
define("MSG_038", "Importation complétée pour la catégorie ");
define("MSG_039", "Importation complétée pour la langue ");
define("MSG_040", "Importation complétée pour le terme ");
define("MSG_041", "Une mise à jour de Netquiz Web est disponible à <a href='http://www.ccdmd.qc.ca/catalogue/netquiz-web' target='maj'>http://www.ccdmd.qc.ca/catalogue/netquiz-web</a>");
define("MSG_042", "Une mise à jour importante de Netquiz Web est disponible et doit être installée.");
define("MSG_043", "Une mise à jour critique de Netquiz Web est disponible et doit être installée.");
define("MSG_044", "Une mise à jour de sécurité de Netquiz Web est disponible et doit être installée.");
define("MSG_045", "Impossible de récupérer les informations sur les nouvelles versions de Netquiz Web.");
define("MSG_046", "Netquiz Web est actuellement en cours de maintenance et non accessible aux utilisateurs qui n'administrent pas le site. Revenez plus tard. Merci de votre patience.");
define("MSG_047", "Netquiz Web est actuellement en mode maintenance et non accessible aux utilisateurs. Si la mise à jour est terminée, vous pouvez remettre le site en ligne dans la section Maintenance du site.");


/** Messages d'erreurs */
define("ERR_000", "Une erreur est survenue. Veuillez essayer de nouveau. Si le probl&egrave;me persiste, contactez l'administrateur du site.");
define("ERR_001", "Impossible de se connecter &agrave; la base de donn&eacute;es. Veuillez v&eacute;rifier que la base de donn&eacute;es est disponible ou que les param&egrave;tres de connexion dans le fichier de configuration sont exacts.");
define("ERR_002", "Impossible d'&eacute;crire le journal applicatif. V&eacute;rifiez les droits d'écriture du répertoire /ressources/journaux.");
define("ERR_003", "Impossible de r&eacute;cup&eacute;rer les donn&eacute;es de l'utilisateur. Si le probl&egrave;me persiste, contactez l'administrateur du site.");
define("ERR_004", "Veuillez saisir votre courriel ou nom d'utilisateur et votre mot de passe.");
define("ERR_005", "Nom d'utilisateur ou mot de passe invalide.");
define("ERR_006", "La demande est incorrecte. Si le probl&egrave;me persiste, contactez l'administrateur du site.");
define("ERR_007", "Votre session a &eacute;t&eacute; ferm&eacute;e avec succ&egrave;s. &Agrave; bient&ocirc;t!");
define("ERR_008", "Impossible de r&eacute;cup&eacute;rer les donn&eacute;es du questionnaire. Si le probl&egrave;me persiste, contactez l'administrateur du site.");
define("ERR_009", "Le type d'item spécifié est incorrect ou non disponible.");
define("ERR_010", "Le questionnaire demandé est incorrect ou non disponible.");
define("ERR_011", "Impossible de r&eacute;cup&eacute;rer les donn&eacute;es d'une section. Si le probl&egrave;me persiste, contactez l'administrateur du site.");
define("ERR_012", "Impossible de pr&eacute;parer les fichiers pour l'aper&ccedil;u. Si le probl&egrave;me persiste, contactez l'administrateur du site.");
define("ERR_013", "Impossible de cr&eacute;er le r&eacute;pertoire pour les m&eacute;dias.");
define("ERR_014", "Le format du fichier transmis n'est pas support&eacute;");
define("ERR_015", "Impossible de transf&eacute;rer le fichier.");
define("ERR_016", "Aucun compte ne correspond &agrave; ce courriel.");
define("ERR_017", "Le mot de passe de confirmation ne correspond pas au nouveau mot de passe inscrit.");
define("ERR_018", "Une erreur technique est survenue. Pour plus d'informations, consultez les journaux applicatifs (/ressources/journaux) ou contactez l'administrateur de Netquiz Web si le problème persiste.");
define("ERR_019", "Les items sélectionnés ont été ajoutés au questionnaire, sauf ceux qui en faisaient déjà partie.");
define("ERR_020", "Aucun des items sélectionnés n'a été ajouté, puisqu'ils faisaient déjà partie du questionnaire.");
define("ERR_021", "La champ nom est incorrect ou absent.");
define("ERR_022", "La champ pr&eacute;nom est incorrect ou absent.");
define("ERR_023", "La champ courriel est incorrect ou absent.");
define("ERR_024", "Le mot de passe actuel est incorrect ou absent.");
define("ERR_025", "Le nouveau mot de passe est incorrect ou absent.");
define("ERR_026", "La confirmation du nouveau mot de passe est incorrecte ou absente.");
define("ERR_027", "Le nouveau mot de passe doit être différent de l'ancien.");
define("ERR_028", "Aucun compte ne correspond &agrave; ce courriel.");
define("ERR_029", "Une erreur est survenue durant l'envoi du courriel. Veuillez essayer de nouveau. Si le probl&egrave;me persiste, contactez l'administrateur du site.");
define("ERR_030", "La requête est incorrecte ou le code de confirmation est absent ou incorrect.");
define("ERR_031", "La bonne réponse parmi les choix n'est pas sélectionnée.");
define("ERR_032", "Une question de type &laquo;&nbsp;Choix multiples&nbsp;&raquo; doit comporter au moins deux choix de réponses valides.");
define("ERR_033", "Une section doit obligatoirement comporter du texte dans le champ &laquo;&nbsp;Titre de la section&nbsp;&raquo;.");
define("ERR_034", "Les items de cette section ne comportent aucune erreur.");
define("ERR_035", "La page d'accueil du questionnaire doit obligatoirement comporter du texte dans le champ &laquo;&nbsp;Titre du questionnaire sur la page d'accueil&nbsp;&raquo;.");
define("ERR_036", "La section doit comporter au moins un item.");
define("ERR_037", "La valeur du champ &laquo;&nbsp;Pondération&nbsp;&raquo; des param&egrave;tres de l'item doit &ecirc;tre num&eacute;rique.");
define("ERR_038", "La valeur du champ &laquo;&nbsp;Pondération&nbsp;&raquo; dans la section  &laquo;&nbsp;Valeurs pour ce questionnaire seulement&nbsp;&raquo; des param&egrave;tres de l'item doit &ecirc;tre num&eacute;rique.");
define("ERR_039", "Le nom du répertoire est incorrect ou absent. Le nom du r&eacute;pertoire doit contenir uniquement des lettres, des chiffres, des traits d'union ou des soulign&eacute;s.");
define("ERR_040", "Une erreur est survenue lors de la publication du questionnaire. L'identifiant inscrit pour l'adresse URL de publication existe peut-être déjà. Essayez un nouvel identifiant. Si le problème persiste, contactez l'administrateur du site.");
define("ERR_041", "Aucun thème n'a été sélectionné. Veuillez sélectionner un thème pour ce questionnaire avant de faire un aperçu ou de le publier.");
define("ERR_042", "Le dossier du thème sélectionné n'existe pas. Veuillez sélectionner un autre thème pour ce questionnaire.");
define("ERR_043", "Aucun item sélectionné ou impossible d'exporter les données pour les items sélectionnés.");
define("ERR_044", "Impossible de créer le répertoire temporaire pour l'importation. Si le probl&egrave;me persiste, contactez l'administrateur du site.");
define("ERR_045", "Impossible de localiser le fichier d'importation compressé. Si le problème persiste, contactez l'administrateur du site.");
define("ERR_046", "Le fichier d'importation doit être en format zip.");
define("ERR_047", "Une erreur est survenue lors du transfert du fichier d'importation compressé. Si le problème persiste, contactez l'administrateur du site.");
define("ERR_048", "Une erreur est survenue lors de l'extraction du fichier d'importation compressé. Veuillez vérifier le format de votre fichier.");
define("ERR_049", "Impossible de localiser le fichier XML pour l'importation. (N. B. Sur Mac, il faut compresser le fichier XML et le dossier MEDIAS et non le dossier parent.)");
define("ERR_050", "La balise XML &laquo;&nbsp;id_item&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_051", "La balise XML &laquo;&nbsp;titre&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_052", "La balise XML &laquo;&nbsp;info_comp1_titre&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_053", "La balise XML &laquo;&nbsp;info_comp1_texte&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_054", "La balise XML &laquo;&nbsp;info_comp2_titre&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_055", "La balise XML &laquo;&nbsp;info_comp2_texte&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_056", "La balise XML &laquo;&nbsp;media_titre&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_057", "La balise XML &laquo;&nbsp;media_texte&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_058", "La balise XML &laquo;&nbsp;media_image&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_059", "La balise XML &laquo;&nbsp;media_son&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_060", "La balise XML &laquo;&nbsp;media_video&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_061", "La balise XML &laquo;&nbsp;suivi&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_062", "La balise XML &laquo;&nbsp;ponderation&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_063", "La balise XML &laquo;&nbsp;ordre_presentation&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_064", "La balise XML &laquo;&nbsp;type_etiquettes&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_065", "La balise XML &laquo;&nbsp;afficher_solution&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_066", "La balise XML &laquo;&nbsp;points_retranches&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_067", "La balise XML &laquo;&nbsp;majmin&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_068", "La balise XML &laquo;&nbsp;ponctuation&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_069", "La balise XML &laquo;&nbsp;type_elements1&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_070", "La balise XML &laquo;&nbsp;demarrer_media&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_071", "La balise XML &laquo;&nbsp;reponse_bonne_message&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_072", "La balise XML &laquo;&nbsp;reponse_mauvaise_message&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_073", "La balise XML &laquo;&nbsp;reponse_incomplete_message&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_074", "La balise XML &laquo;&nbsp;reponse_bonne_media&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_075", "La balise XML &laquo;&nbsp;reponse_mauvaise_media&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_076", "La balise XML &laquo;&nbsp;reponse_incomplete_media&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_077", "La balise XML &laquo;&nbsp;remarque&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_078", "La balise XML &laquo;&nbsp;type_item&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_079", "Un des fichiers média est introuvable dans le répertoire medias&nbsp;: ");
define("ERR_080", "Impossible de localiser la définition XML du média ");
define("ERR_081", "La balise XML &laquo;&nbsp;id_item&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_082", "La balise XML &laquo;&nbsp;enonce&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_083", "La balise XML &laquo;&nbsp;description&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_084", "La balise XML &laquo;&nbsp;type&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_085", "La balise XML &laquo;&nbsp;source&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_086", "La balise XML &laquo;&nbsp;url&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_087", "La balise XML &laquo;&nbsp;suivi&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_088", "La balise XML &laquo;&nbsp;id_item_choix_mult&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_089", "La balise XML &laquo;&nbsp;bonne_reponse&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_090", "La balise XML &laquo;&nbsp;element&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_091", "La balise XML &laquo;&nbsp;retroaction&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_092", "La balise XML &laquo;&nbsp;titre_long&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_093", "La balise XML &laquo;&nbsp;generation_question_type&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_094", "La balise XML &laquo;&nbsp;generation_question_nb&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_095", "Impossible de localiser la définition XML pour la section ");
define("ERR_096", "La balise XML &laquo;&nbsp;temps_reponse_calculer&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_097", "La balise XML &laquo;&nbsp;essais_repondre_type&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_098", "La balise XML &laquo;&nbsp;essais_repondre_nb&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_099", "La balise XML &laquo;&nbsp;affichage_resultats_type&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_100", "La balise XML &laquo;&nbsp;demarrage_media_type&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_101", "La balise XML &laquo;&nbsp;id_langue_questionnaire&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_102", "La balise XML &laquo;&nbsp;theme&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_103", "La balise XML &laquo;&nbsp;mot_bienvenue&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_104", "La balise XML &laquo;&nbsp;note&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_105", "La balise XML &laquo;&nbsp;generique&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_106", "La balise XML &laquo;&nbsp;media_titre&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_107", "La balise XML &laquo;&nbsp;media_texte&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_108", "La balise XML &laquo;&nbsp;media_image&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_109", "La balise XML &laquo;&nbsp;media_son&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_110", "La balise XML &laquo;&nbsp;media_video&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_111", "La balise XML &laquo;&nbsp;texte_fin&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_112", "La balise XML &laquo;&nbsp;id_item&nbsp;&raquo; est incorrecte ou absente pour la section questionnaire_item où id_item = ");
define("ERR_113", "La balise XML &laquo;&nbsp;id_section&nbsp;&raquo; est incorrecte ou absente pour la section questionnaire_item où id_item = ");
define("ERR_114", "La balise XML &laquo;&nbsp;ponderation_quest&nbsp;&raquo; est incorrecte ou absente pour la section questionnaire_item où id_item = ");
define("ERR_115", "La balise XML &laquo;&nbsp;demarrer_media_quest&nbsp;&raquo; est incorrecte ou absente pour la section questionnaire_item où id_item = ");
define("ERR_116", "La balise XML &laquo;&nbsp;ordre_presentation_quest&nbsp;&raquo; est incorrecte ou absente pour la section questionnaire_item où id_item = ");
define("ERR_117", "La balise XML &laquo;&nbsp;type_etiquettes_quest&nbsp;&raquo; est incorrecte ou absente pour la section questionnaire_item où id_item = ");
define("ERR_118", "La balise XML &laquo;&nbsp;id_section&nbsp;&raquo; est incorrecte ou absente pour une section.");
define("ERR_119", "La balise XML &laquo;&nbsp;titre&nbsp;&raquo; est incorrecte ou absente pour la section où id_section = ");
define("ERR_120", "La balise XML &laquo;&nbsp;generation_question_type&nbsp;&raquo; est incorrecte ou absente pour la section où id_section = ");
define("ERR_121", "La balise XML &laquo;&nbsp;generation_question_nb&nbsp;&raquo; est incorrecte ou absente pour la section où id_section = ");
define("ERR_122", "La balise XML &laquo;&nbsp;type_bonnesreponses_quest&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_123", "La balise XML &laquo;&nbsp;retroaction_negative&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_124", "La balise XML &laquo;&nbsp;points_retranches_quest&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_125", "La balise XML &laquo;&nbsp;majmin_quest&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_126", "Impossible de localiser la définition XML pour l'item ");
define("ERR_127", "Une page doit nécessairement comporter du texte dans le champ &laquo;&nbsp;Texte&nbsp;&raquo;.");
define("ERR_128", "Impossible de créer le type d'item demandé. Erreur d'application s'est produite.");
define("ERR_129", "Une question de type &laquo;&nbsp;Vrai ou faux&nbsp;&raquo; doit comporter au moins deux choix de réponses valides.");
define("ERR_130", "Une question de type &laquo;&nbsp;Réponses multiples&nbsp;&raquo; doit comporter au moins deux choix de réponses valides.");
define("ERR_131", "Votre session a expiré et vous avez été déconnecté. Veuillez vous authentifier pour continuer.");
define("ERR_132", "Une question de type &laquo;&nbsp;Mise en ordre&nbsp;&raquo; doit comporter au moins deux choix de réponses valides.");
define("ERR_133", "");
define("ERR_134", "La balise XML &laquo;&nbsp;ponctuation_quest&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_135", "La balise XML &laquo;&nbsp;solution&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_136", "La balise XML &laquo;&nbsp;retroaction_positive&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_137", "La balise XML &laquo;&nbsp;retroaction_negative&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_138", "Une question de type &laquo;&nbsp;Développement&nbsp;&raquo; doit comporter du texte dans le champ &laquo;&nbsp;Énoncé&nbsp;&raquo;.");
define("ERR_139", "Une question de type &laquo;&nbsp;Dictée&nbsp;&raquo; doit comporter du texte dans la section &laquo;&nbsp;Solution de la dictée&nbsp;&raquo;.");
define("ERR_140", "Le champ &laquo;&nbsp;Points retranchés&nbsp;&raquo; des paramètres de l'item doit être numérique.");
define("ERR_141", "Le nombre de points à retrancher par faute est supérieur à la pondération de cette question.");
define("ERR_142", "Le champ &laquo;&nbsp;Points retranchés&nbsp;&raquo; dans &laquo;&nbsp;Valeurs pour ce questionnaire seulement&nbsp;&raquo; doit &ecirc;tre num&eacute;rique.");
define("ERR_143", "Une question de type &nbsp;&laquo;Associations&nbsp;&raquo; doit comporter au moins deux paires associées valides.");
define("ERR_144", "Certaines paires associées ne sont pas complètes.");
define("ERR_145", "Certaines éléments du damier ne sont pas complètes.");
define("ERR_146", "Une question de type &laquo;&nbsp;Damier&nbsp;&raquo; doit comporter 2, 4, 6, 8 ou 10 paires d'éléments associés valides.");
define("ERR_147", "La balise XML &laquo;&nbsp;masque&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_148", "Une question de type &laquo;&nbsp;Réponse brève&nbsp;&raquo; doit comporter une rétroaction pour toutes les réponses non prévues.");
define("ERR_149", "Une question de type &laquo;&nbsp;Réponse brève&nbsp;&raquo; doit comporter du texte dans le champ &laquo;&nbsp;Énoncé&nbsp;&raquo;.");
define("ERR_150", "Une question de type &laquo;&nbsp;Réponse brève&nbsp;&raquo; doit comporter au moins une bonne réponse prévue.");
define("ERR_151", "La même couleur de marquage est employée plus d'une fois.");
define("ERR_152", "Certaines couleurs de marquage n'ont pas de libellé.");
define("ERR_153", "Certaines couleurs de marquage comportent le même libellé.");
define("ERR_154", "Une question de type &laquo;&nbsp;Classement&nbsp;&raquo; doit comporter au moins deux classeurs valides.");
define("ERR_155", "Certains classeurs n'ont pas d'onglet valide.");
define("ERR_156", "La balise XML &laquo;&nbsp;orientation_elements_quest&nbsp;&raquo; est incorrecte ou absente pour l'item ");
define("ERR_157", "La balise XML &laquo;&nbsp;orientation_elements&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_158", "Le fichier XML comporte une ou plusieurs erreurs de syntaxe et ne peut être traité.");
define("ERR_159", "Chaque lacune d'un item de type Texte lacunaire doit comporter au moins une bonne réponse.");
define("ERR_160", "Chaque lacune d'un item de type &laquo;&nbsp;Texte lacunaire&nbsp;&raquo; avec réponses brèves doit comporter du texte dans le champ &laquo;&nbsp;Rétroaction pour toutes les réponses non prévues&nbsp;&raquo;.");
define("ERR_161", "Chaque lacune d'un item de type &laquo;&nbsp;Texte lacunaire&nbsp;&raquo; avec menus déroulants doit comporter au moins une mauvaise réponse.");
define("ERR_162", "Chaque lacune d'un item de type &laquo;&nbsp;Texte lacunaire&nbsp;&raquo; avec réponses à glisser-déposer ou réponses brèves doit comporter au moins une réponse prévue valide.");
define("ERR_163", "Chaque lacune d'un item de type &laquo;&nbsp;Texte lacunaire&nbsp;&raquo; avec menus déroulants doit comporter au moins deux réponses valides.");
define("ERR_164", "Une question de type &laquo;&nbsp;Texte lacunaire&nbsp;&raquo; doit comporter un texte et au moins une lacune.");
define("ERR_165", "La balise XML &laquo;&nbsp;type_champs&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_166", "La balise XML &laquo;&nbsp;couleur_element_quest&nbsp;&raquo; est incorrecte ou absente pour l'item ");
define("ERR_167", "La balise XML &laquo;&nbsp;couleur_element_associe_quest&nbsp;&raquo; est incorrecte ou absente pour l'item ");
define("ERR_168", "La balise XML &laquo;&nbsp;afficher_masque_quest&nbsp;&raquo; est incorrecte ou absente pour l'item ");
define("ERR_169", "La balise XML &laquo;&nbsp;type_champs_quest&nbsp;&raquo; est incorrecte ou absente pour l'item ");
define("ERR_170", "La balise XML &laquo;&nbsp;id_terme&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_171", "La balise XML &laquo;&nbsp;couleur_zones&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_172", "Le thème actuellement sélectionné est introuvable. Veuillez choisir un nouveau thème.");
define("ERR_173", "Une question de type &laquo;&nbsp;Zone à identifier&nbsp;&raquo; doit comporter une image sur laquelle seront placées les étiquettes de chaque zone.");
define("ERR_174", "Une question de type &laquo;&nbsp;Zone à identifier&nbsp;&raquo; doit comporter au moins deux zones valides.");
define("ERR_175", "Certaines étiquettes de zones à identifier sont placées l'une sur l'autre au même endroit.");
define("ERR_176", "Le champ &laquo;&nbsp;nom d'utilisateur&nbsp;&raquo; est incorrect ou absent.");
define("ERR_177", "Le nom d'utilisateur est déjà utilisé.");
define("ERR_178", "Un compte existe déjà pour cette adresse de courriel. Vous pouvez retourner à la page de connexion et cliquer sur le lien «&nbsp;Mot de passe ou nom d'utilisateur oublié?&nbsp;».");
define("ERR_179", "Votre compte doit être approuvé avant de permettre la connexion.");
define("ERR_180", "Votre compte est verrouillé. Veuillez contacter l'administrateur.");
define("ERR_181", "Le titre du projet est incorrect ou absent.");
define("ERR_182", "La description du projet est incorrecte ou absente.");
define("ERR_183", "L'identifiant unique du projet est incorrect ou absent.");
define("ERR_184", "Le projet sélectionné n'est pas accessible. Vérifier que le projet est actif et que vous disposez des permissions pour y avoir accès.");
define("ERR_185", "L'identifiant unique du projet est déjà utilisé. Veuillez inscrire un nouvel identifiant.");
define("ERR_186", "L'identifiant unique du projet doit contenir au moins une lettre.");
define("ERR_187", "Vous ne disposez pas des droits requis pour effectuer cette opération.");
define("ERR_188", "Le projet spécifié est incorrect ou absent.");
define("ERR_189", "Votre demande de compte a été refusée. Veuillez contacter l'administrateur.");
define("ERR_190", "La langue par défaut pour l'aperçu et la publication est incorrecte ou absente.");
define("ERR_191", "Le thème par défaut pour l'aperçu et la publication est incorrect ou absent.");
define("ERR_192", "La langue pour les aperçus est incorrecte ou absente.");
define("ERR_193", "Cette personne a déjà été invitée.");
define("ERR_194", "Cette personne est déjà un collaborateur et ne peut être invitée à nouveau.");
define("ERR_195", "Vous avez déjà accès à ce projet; il n'est pas possible de vous ajouter comme collaborateur.");
define("ERR_196", "Vous ne disposez pas des accès requis pour ce projet.");
define("ERR_197", "L'adresse de courriel du nouveau collaborateur est incorrecte ou absente.");
define("ERR_198", "Veuillez noter que le projet dans lequel vous avez été invité a été supprimé.");
define("ERR_199", "Veuillez noter que le projet dans lequel vous avez été invité est maintenant inactif.");
define("ERR_200", "Cet utilisateur a été supprimé ou n'est plus actif. Impossible de le nommer responsable du projet.");
define("ERR_201", "Veuillez noter que le projet ou l'invitation de collaboration a été supprimé.");
define("ERR_202", "Le nombre d'items à inclure dans le questionnaire, indiqué dans le paramètre &laquo;&nbsp;Présentation des items&nbsp;&raquo;, est supérieur au nombre total d'items du questionnaire.");
define("ERR_203", "Votre accès à Netquiz Web est temporairement désactivé. Veuillez contactez l'administrateur du site.");
define("ERR_204", "Le dernier thème que vous avez sauvegardé n'existe plus. Le thème par défaut sera utilisé.");
define("ERR_205", "Erreur détectée dans le fichier XML. Dans la liste «&nbsp;questionnaire_item&nbsp;», les identifiants des items ne sont pas uniques. Identifiant(s) incorrect(s)&nbsp;: ");
define("ERR_206", "Erreur détectée dans le fichier XML. Dans la liste des items, les identifiants des items ne sont pas uniques. Identifiant(s) incorrect(s)&nbsp;: ");
define("ERR_207", "Erreur détectée dans le fichier XML. Les identifiants des médias ne sont pas uniques. Identifiant(s) incorrect(s)&nbsp;: ");
define("ERR_208", "Erreur détectée dans le fichier XML. Les identifiants des questionnaires ne sont pas uniques. Identifiant(s) incorrect(s)&nbsp;: ");
define("ERR_209", "Un compte existe déjà pour cette adresse de courriel. Veuillez vérifier ou utiliser une adresse de courriel différente.");
define("ERR_210", "Le projet courant n'a pas d'identifiant unique. Veuillez compléter le champ «&nbsp;Identifiant unique&nbsp;» dans le formulaire du projet.");
define("ERR_211", "Certains champs de la langue d'aperçu ou de publication du questionnaire sont absents. Veuillez les remplir dans la section &laquo;&nbsp;Bibliothèque/Mes Langues&nbsp;&raquo;.");
define("ERR_212", "Impossible de trouver le nom d'utilisateur dans la base de données");
define("ERR_213", "Votre accès a été temporairement désactivé. Veuillez contactez l'administrateur du site.");
define("ERR_214", "Le fichier &laquo;&nbsp;netquizweb-installation.sql&nbsp;&raquo; contenant le schéma de la base de données ne peut être localisé. Impossible de continuer.");
define("ERR_215", "Une erreur est survenue lors de la création des tables dans la base de données. Vérifiez si le nom d'utilisateur pour l'accès à la base de données dispose des privilèges pour la création des tables.");
define("ERR_216", "Le répertoire servant à la publication des questionnaires n'a pas les droits d'écriture requis. Vérifiez les permissions du répertoire suivant&nbsp;:");
define("ERR_217", "Le répertoire des médias n'a pas les droits d'écriture requis. Vérifiez les permissions du répertoire suivant&nbsp;:");
define("ERR_218", "Le répertoire des journaux applicatifs n'a pas les droits d'écriture requis. Vérifiez les permissions du répertoire suivant&nbsp;:");
define("ERR_219", "Une erreur d'accès à la base de données est survenue durant la mise à jour de Netquiz Web. Vérifiez si le nom d'utilisateur pour l'accès à la base de données dispose de tous les privilèges requis et essayez de nouveau.");
define("ERR_220", "Le paramètre DB_HOST du fichier de configuration &laquo;&nbsp;config.inc.php&nbsp;&raquo; est absent ou incorrect.");
define("ERR_221", "Le paramètre DB_NAME du fichier de configuration &laquo;&nbsp;config.inc.php&nbsp;&raquo; est absent ou incorrect.");
define("ERR_222", "Le paramètre DB_USER du fichier de configuration &laquo;&nbsp;config.inc.php&nbsp;&raquo; est absent ou incorrect.");
define("ERR_223", "Le paramètre DB_PASSWORD du fichier de configuration &laquo;&nbsp;config.inc.php&nbsp;&raquo; est absent ou incorrect.");
define("ERR_224", "Le paramètre EMAIL_FROM du fichier de configuration &laquo;&nbsp;config.inc.php&nbsp;&raquo; est absent ou incorrect.");
define("ERR_225", "Le répertoire «&nbsp;ressources&nbsp;» ne doit pas être visible à partir du web. Vérifiez les permissions de ce répertoire, le fichier .htaccess ou la configuration Apache pour la prise en compte des fichiers .htaccess.");
define("ERR_226", "L'installation de l'application Netquiz Web n'est pas complétée ou un problème est survenu avec le contenu de la base de données. Cliquez sur ce lien <a href='http://aide.ccdmd.qc.ca/nqw/node/135/' target='help'>Installation de l'application Netquiz Web sur un serveur</a> et assurez-vous d'avoir bien suivi les étapes. Sinon, contactez l'administrateur de la base de données.");
define("ERR_227", "Erreur détectée dans le fichier XML&nbsp;: les identifiants des langues ne sont pas uniques. Identifiant incorrect&nbsp;: ");
define("ERR_228", "La balise XML &laquo;&nbsp;id_langue&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_229", "La balise XML &laquo;&nbsp;id_collection&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_230", "La balise XML &laquo;&nbsp;id_categorie&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_231", "La balise XML &laquo;&nbsp;terme&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_232", "La balise XML &laquo;&nbsp;variantes&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_233", "La balise XML &laquo;&nbsp;type_definition&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_234", "La balise XML &laquo;&nbsp;texte&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_235", "La balise XML &laquo;&nbsp;url&nbsp;&raquo; est incorrecte ou absente.");
define("ERR_236", "Le fichier n'est pas du bon type.");
define("ERR_237", "DANGER! Une ou plusieurs personnes travaillent actuellement sur le même élément que vous. Cette situation pourrait entraîner des pertes de données si vous enregistrez au même moment. Veuillez contacter ces personnes au besoin&nbsp;: ");
define("ERR_238", "Le paramètre RETURN_PATH du fichier de configuration &laquo;&nbsp;config.inc.php&nbsp;&raquo; est absent ou incorrect.");

/** URL pour l'aide en ligne **/
define('URL_AIDE_NQW', 'http://aide.ccdmd.qc.ca/nqw/fr/content/');

/** Fichiers **/
define("FICHIER_THEME_APERCU", "apercu.jpg");

/** Questionnaires - statuts **/
define("QUESTIONNAIRE_STATUT_0", "Supprimé");
define("QUESTIONNAIRE_STATUT_1", "Brouillon");
define("QUESTIONNAIRE_STATUT_2", "Publié");

/** Projets - statuts **/
define("PROJET_STATUT_0", "Inactif");
define("PROJET_STATUT_1", "Actif");
define("PROJET_STATUT_2", "Supprimé");
define("PROJET_STATUT_3", "Verrouillé");

/** Usager - statuts **/
define("USAGER_STATUT_0", "Actif");
define("USAGER_STATUT_1", "Verrouillé");
define("USAGER_STATUT_2", "En attente d'une approbation");
define("USAGER_STATUT_3", "Accès refusé");
define("USAGER_STATUT_4", "Incomplet");
define("USAGER_STATUT_9", "Supprimé");

?>
