<?php
/**
 * Fichier contenant les expressions pour la langue en_CA
 *
 * @package NetquizWeb
 */


/** Expressions */ 
define('LANGUE_INTERFACE','2'); 
define('LANGUE_INTERFACE_TITRE','English'); 
define('TXT_BIENVENUE', 'Welcome to Netquiz Web'); 
define('TXT_NOUVEAU_QUESTIONNAIRE', 'Untitled quiz'); 
define('TXT_NOUVEL_ITEM', 'Untitled item'); 
define('TXT_NOUVELLE_SECTION', 'Untitled section'); 
define('TXT_PREFIX_DUPLIQUER', '*'); 
define('TXT_QUESTIONNAIRES', 'Quizzes'); 
define('TXT_MES_QUESTIONNAIRES', 'My Quizzes'); 
define('TXT_CORBEILLE', 'Recycle Bin'); 
define('TXT_FRANCAIS', 'French'); 
define('TXT_ANGLAIS', 'English');
define('TXT_BIBLIOTHEQUE', 'Library'); 
define('TXT_ACCUEIL_NETQUIZWEB', 'Netquiz Web Homepage'); 
define('TXT_MON_PROFIL', 'My Profile'); 
define('TXT_DECONNEXION','Logout'); 
define('TXT_A_PROPOS','About'); 
define('TXT_INTRODUCTION','Introduction'); 
define('TXT_DROITS_UTILISATION','Terms of Use'); 
define('TXT_GENERIQUE','Credits'); 
define('TXT_COMMENTAIRES','Comments'); 
define('TXT_AIDE','Help'); 
define('TXT_AJOUTER_NOUVEAU_QUESTIONNAIRE','Add a new quiz'); 
define('TXT_AFFICHER_TOUTES_LES_COLLECTIONS', 'Display all collections'); 
define('TXT_CODE','Code'); 
define('TXT_TITRE','Title'); 
define('TXT_ITEMS','Items'); 
define('TXT_COLLECTION','Collection'); 
define('TXT_STATUT','Status'); 
define('TXT_DATE_DE_MODIFICATION','Modification date'); 
define('TXT_PAR_PAGE', 'per page'); 
define('TXT_ELEMENT', 'Element'); 
define('TXT_ELEMENT_MINUSCULES', 'element');
define('TXT_DE', 'of'); 
define('TXT_DE_2', 'Of'); 
define('TXT_MODIFIER', 'Modify'); 
define('TXT_DUPLIQUER', 'Duplicate'); 
define('TXT_ACTIVER_SUIVI', 'Flag'); 
define('TXT_ACCUEIL_CCDMD', 'CCDMD Homepage'); 
define('TXT_VOIR_APERCU_WEB', 'Web preview'); 
define('TXT_EXPORTER_XML', 'Export XML'); 
define('TXT_IMPRIMER', 'Print'); 
define('TXT_METTRE_A_LA_CORBEILLE', 'Move to recycle bin'); 
define('TXT_CCDMD_DROITS', 'Collegial Centre for Educational Materials Development, 2014'); 
define('TXT_INSCRIRE_MOTSCLES', 'Enter the keywords'); 
define('TXT_PARAMETRES', 'Parameters'); 
define('TXT_PARAMETRES_DE_ITEM', 'Item parameters'); 
define('TXT_THEME', 'Theme'); 
define('TXT_THEME_DU_QUESTIONNAIRE', 'Quiz theme'); 
define('TXT_ANNULER','Cancel'); 
define('TXT_ENREGISTRER', 'Save'); 
define('TXT_TITRE_DU_QUESTIONNAIRE', 'Quiz title'); 
define('TXT_CHOISIR_UNE_COLLECTION', 'Choose a collection'); 
define('TXT_GENERATION_DES_ITEMS', 'Presentation of items'); 
define('TXT_SELON_PARAMETRE_SECTION', 'Based on the parameter of each section'); 
define('TXT_SELON_PARAMETRE_ITEM', 'Based on the parameter of each item'); 
define('TXT_ORDRE_ALEATOIRE', 'Random order'); 
define('TXT_ORDRE_PREDETERMINE', 'Predetermined order'); 
define('TXT_INCLURE', 'Include'); 
define('TXT_ITEMS_SUR_X_ITEMS', 'items of X'); 
define('TXT_TEMPS_DE_PASSATION', 'Duration'); 
define('TXT_ILLIMITE', 'Unlimited'); 
define('TXT_LIMITE', 'Limited'); 
define('TXT_HEURES', 'hours'); 
define('TXT_MINUTES', 'minutes'); 
define('TXT_AFFICHAGE_DES_RESULTATS', 'Display results'); 
define('TXT_TOUJOURS_AFFICHER', 'Always display'); 
define('TXT_JAMAIS_AFFICHER', 'Never display'); 
define('TXT_NOMBRE_ESSAI_POUR_REPONDRE', 'Number of tries'); 
define('TXT_A', 'to'); 
define('TXT_ESSAIS', 'tries'); 
define('TXT_DEMARRAGE_AUTOMATIQUE_DES_MEDIAS', 'Automatically start media'); 
define('TXT_NE_JAMAIS_DEMARRER_DE_MEDIAS', 'Never start media'); 
define('TXT_TOUJOURS_DEMARRER_MEDIA_AUDIO', 'Always start audio'); 
define('TXT_TOUJOURS_DEMARRER_MEDIA_VIDEO', 'Always start video'); 
define('TXT_LANGUE_DU_QUESTIONNAIRE_PUBLIE', 'Language for preview or publication of this quiz'); 
define('TXT_FIN_DU_QUESTIONNAIRE', 'End of quiz'); 
define('TXT_CONTENU', 'Content'); 
define('TXT_TEXTE', 'Text'); 
define('TXT_NETQUIZ_WEB', 'Netquiz Web'); 
define('TXT_PAGE_ACCUEIL', 'Homepage'); 
define('TXT_COMPLEMENTS', 'Add-ons'); 
define('TXT_TITRE_QUESTIONNAIRE_PAGE_ACCUEIL', 'Quiz title on homepage'); 
define('TXT_MOT_DE_BIENVENUE', 'Welcome message'); 
define('TXT_NOTE', 'Note'); 
define('TXT_MEDIA_ACCUEIL', 'Media on homepage'); 
define('TXT_MEDIA_ACCUEIL_TITRE', 'Media on homepage - title'); 
define('TXT_MEDIA_ACCUEIL_TEXTE', 'Media on homepage - text'); 
define('TXT_AJOUTER_UN_TEXTE', 'Add a text'); 
define('TXT_INSCRIRE_LE_TITRE', 'Type a title'); 
define('TXT_INSCRIRE_UN_TITRE', 'Type a title'); 
define('TXT_INSCRIRE_LE_TEXTE', 'Type a text'); 
define('TXT_AJOUTER_UNE_IMAGE', 'Add image file'); 
define('TXT_AUCUNE_SELECTION', 'No selection'); 
define('TXT_AJOUTER_UN_SON', 'Add audio file'); 
define('TXT_AJOUTER_UNE_VIDEO', 'Add video file'); 
define('TXT_TITRE_DE_LA_SECTION', 'Section title'); 
define('TXT_CHOIX_MULTIPLES', 'Multiple choice'); 
define('TXT_TITRE_ITEM', 'Item title'); 
define('TXT_ENONCE', 'Question text');
define('TXT_BONNE_REPONSE', 'Correct answer'); 
define('TXT_REPONSE', 'Answer'); 
define('TXT_RETROACTION', 'Feedback'); 
define('TXT_CATEGORIE', 'Category'); 
define('TXT_CHOISIR_UNE_CATEGORIE', 'Choose a category'); 
define('TXT_NE_PAS_DEMARRER_DE_MEDIA','Do not start media'); 
define('TXT_DEMARRER_LE_MEDIA_AUDIO','Start audio'); 
define('TXT_DEMARRER_LE_MEDIA_VIDEO','Start video'); 
define('TXT_MODIFIER_CES_VALEURS_POUR_CE_QUESTIONNAIRE_SEULEMENT','Modify values for this quiz only'); 
define('TXT_VALEURS_MODIFIEES_POUR_CE_QUESTIONNAIRE_SEULEMENT', 'Values modified for this quiz only'); 
define('TXT_MODIFIER_CES_VALEURS_POUR_CET_ITEM_SEULEMENT','Modify values for this item only'); 
define('TXT_VALEURS_MODIFIEES_POUR_CET_ITEM_SEULEMENT','Values modified for this item only'); 
define('TXT_AFFICHAGE_DE_LA_SOLUTION','Display correct answer'); 
define('TXT_AFFICHER','Display'); 
define('TXT_NE_PAS_AFFICHER','Do not display'); 
define('TXT_ORDRE_DE_PRESENTATION_DES_ELEMENTS','Display order of the elements'); 
define('TXT_PREDETERMINE','Predetermined'); 
define('TXT_ALEATOIRE','Random'); 
define('TXT_ETIQUETTE_DES_ELEMENTS','Elements label'); 
define('TXT_NUMERIQUE','Numeric'); 
define('TXT_ALPHABETIQUE','Alphabetic'); 
define('TXT_AUCUN','None'); 
define('TXT_MESSAGES_GENERAUX_DE_LA_LANGUE_DE_APERCU','General messages in the language of the preview'); 
define('TXT_MESSAGES_GENERAUX_DE_LA_LANGUE_DU_QUESTIONNAIRE','General messages in the language of the quiz'); 
define('TXT_MESSAGE_POUR_BONNE_REPONSE','Message for a correct answer'); 
define('TXT_MESSAGE_POUR_MAUVAISE_REPONSE','Message for an incorrect answer'); 
define('TXT_MESSAGE_POUR_REPONSE_INCOMPLETE','Message for an incomplete answer'); 
define('TXT_REMARQUE','Note'); 
define('TXT_PONDERATION', 'Weighting'); 
define('TXT_INFORMATION_COMPLEMENTAIRE', 'Add-on'); 
define('TXT_INSCRIRE_LE_TITRE_DETAILS', 'Type a title (Clue, Source, ... etc.)'); 
define('TXT_MEDIA_EN_ENTETE', 'Media in the header'); 
define('TXT_QUESTIONNAIRE','Quiz'); 
define('TXT_DESACTIVER', 'Unpublish'); 
define('TXT_PUBLIER_LE_QUESTIONNAIRE', 'Publish the quiz'); 
define('TXT_PUBLIE', 'Published'); 
define('TXT_PUBLIER', 'Publish'); 
define('TXT_APERCU', 'Preview'); 
define('TXT_AJOUTER_UN_NOUVEL_ITEM', 'Add a new item'); 
define('TXT_ASSOCIATION', 'Matching'); 
define('TXT_ASSOCIATIONS', 'Matching'); 
define('TXT_CLASSEMENT', 'Classification'); 
define('TXT_DAMIER', 'Matching Board'); 
define('TXT_DEVELOPPEMENT', 'Essay'); 
define('TXT_DICTEE', 'Dictation'); 
define('TXT_MARQUAGE', 'Highlight'); 
define('TXT_MISE_EN_ORDRE', 'Sequencing'); 
define('TXT_REPONSE_BREVE', 'Short Answer'); 
define('TXT_REPONSES_MULTIPLES', 'Multiple Answer'); 
define('TXT_TEXTE_LACUNAIRE', 'Fill in the blanks'); 
define('TXT_VRAI_OU_FAUX', 'True/False'); 
define('TXT_ZONES_A_IDENTIFIER', 'Identify Parts of an Image');
define('TXT_ZONES_A_IDENTIFIER_ENTETE_ITEM', 'Part of the image'); 
define('TXT_PAGE', 'Page'); 
define('TXT_AJOUTER_UNE_SECTION', 'Add a section'); 
define('TXT_AJOUTER_DES_ITEMS_DE_LA_BIBLIOTHEQUE', 'Add items from the library');
define('TXT_BIENVENUE_DANS_NETQUIZ_WEB', 'Welcome to Netquiz Web!'); 
define('TXT_BIENVENUE_DANS_NETQUIZ_WEB1', 'Welcome to Netquiz Web! (Version:'); 
define('TXT_BIENVENUE_DANS_NETQUIZ_WEB2', ')');
define('TXT_IDENTIFICATION_LIGNE1', '<em>Netquiz Web</em> lets you create exercises, quizzes or formative tests and publish them on the Web with a single click. These quizzes offer 14 different items or question-types (<em>Matching, Multiple Choice, Classification, Matching board, Essay, Dictation, Highlight, Sequencing, Short answer, Multiple answer, Fill in the blanks, True or False, Identify parts of an image, Page</em>). You can insert texts, images, audio and video files into any question. You can also add a glossary, so that the terms it contains appear highlighted in the quizz, allowing respondents to get their definition in the form of text, image, video, sound or links.'); 
define('TXT_CONNEXION', 'Log in'); 
define('TXT_ENTREZ_NOM_UTILISATEUR_ET_MOT_DE_PASSE', 'Enter your username and password.'); 
define('TXT_IDENTIFICATION_CONSULTEZ_AIDE', 'If you have questions or experience technical problems, contact technical support at <a href="mailto:soutien@ccdmd.qc.ca">soutien@ccdmd.qc.ca</a>.'); 
define('TXT_MESSAGE_NAVIGATEURS_NON_SUPPORTES', 'Netquiz Web is not optimized for your browser. Please upgrade your browser to a newer version.'); 
define('TXT_COURRIEL_OU_NOM_UTILISATEUR', 'Email or username'); 
define('TXT_CHAMPS_REQUIS', 'Required fields'); 
define('TXT_SE_SOUVENIR_DE_MOI', 'Remember me'); 
define('TXT_ME_CONNECTER', 'Log in'); 
define('TXT_MOT_DE_PASSE_OU_UTILISATEUR_OUBLIE', 'Password or username forgotten?'); 
define('TXT_NOUVEAUTE', 'What\'s new'); 
define('TXT_INSCRIRE_VOTRE_ENONCE', 'Type your question'); 
define('TXT_IMAGE', 'Image'); 
define('TXT_SON', 'Audio'); 
define('TXT_VIDEO', 'Video'); 
define('TXT_AUCUNE_IMAGE', 'No image file'); 
define('TXT_AUCUN_SON', 'No audio file'); 
define('TXT_AUCUN_VIDEO', 'No video file'); 
define('TXT_DATE_DE_CREATION', 'Creation date'); 
define('TXT_LISTE_DES_ELEMENTS', 'List of elements'); 
define('TXT_SECTION', 'Section'); 
define('TXT_CONTENU_DETAILLE_DE_CHAQUE_ELEMENT_DU_QUESTIONNAIRE', 'Detailed content of each element in the quiz'); 
define('TXT_CHOIX', 'Choice'); 
define('TXT_SUPPRIMER_ITEM', 'Delete this item'); 
define('TXT_SUPPRIMER_ITEM_DU_QUESTIONNAIRE', 'Remove this item from the quiz'); 
define('TXT_VOULEZ_VOUS_SUPPRIMER_CET_ITEM','Are you sure that you want to delete this item? This action is irreversible.'); 
define('TXT_VOULEZ_VOUS_SUPPRIMER_CET_ITEM_DU_QUESTIONNAIRE','Are you sure that you want to delete this item from the quiz? This action is irreversible.'); 
define('TXT_SUPPRIMER_CETTE_SECTION_ET_SON_CONTENU', 'Delete this section and its content'); 
define('TXT_VOULEZ_VOUS_SUPPRIMER_CETTE_SECTION', 'Are you sure that you want to delete this section and its content? This action is irreversible.'); 
define('TXT_VOULEZ_VOUS_METTRE_QUESTIONNAIRE_DANS_LA_CORBEILLE', 'Are you sure that you want to move this quiz to the recycle bin?'); 
define('TXT_TYPE_ITEM', 'Item type'); 
define('TXT_CHANGER_TYPE_ITEM', 'Change item type'); 
define('TXT_SUPPRIMER_DEFINITIVEMENT', 'Delete forever'); 
define('TXT_RECUPERER_ELEMENT', 'Restore'); 
define('TXT_ITEM', 'Item'); 
define('TXT_MES_ITEMS', 'My Items'); 
define('TXT_AFFICHER_TOUS_LES_TYPES', 'Display all types'); 
define('TXT_TYPE','Type'); 
define('TXT_MES_MEDIAS', 'My Media'); 
define('TXT_MES_LANGUES', 'My Languages'); 
define('TXT_MES_COLLECTIONS', 'My Collections'); 
define('TXT_MES_CATEGORIES', 'My Categories'); 
define('TXT_NOUVELLE_COLLECTION', 'Untitled collection'); 
define('TXT_NOUVELLE_CATEGORIE', 'Untitled category');
define('TXT_COLLECTIONS', 'Collections'); 
define('TXT_CATEGORIES', 'Categories'); 
define('TXT_TITRE_DE_LA_COLLECTION', 'Collection Title'); 
define('TXT_TITRE_DE_LA_CATEGORIE', 'Category Title'); 
define('TXT_AJOUTER_UNE_NOUVELLE_CATEGORIE', 'Add a new category'); 
define('TXT_AJOUTER_UNE_NOUVELLE_COLLECTION', 'Add a new collection'); 
define('TXT_NOUVELLE_LANGUE', 'Untitled language'); 
define('TXT_AJOUTER_UNE_NOUVELLE_LANGUE', 'Add a new language'); 
define('TXT_LANGUE', 'Language'); 
define('TXT_LANGUES', 'Languages'); 
define('TXT_PREFIX_ITEM', 'I'); 
define('TXT_PREFIX_MEDIA', 'M'); 
define('TXT_PREFIX_COLLECTION', 'C'); 
define('TXT_PREFIX_CATEGORIE', 'E'); 
define('TXT_PREFIX_LANGUE', 'L'); 
define('TXT_PREFIX_QUESTIONNAIRE', 'Q'); 
define('TXT_PREFIX_PROJET', 'P'); 
define('TXT_PREFIX_USAGER', 'U');
define('TXT_PREFIX_TERME', 'T'); 
define('TXT_DELIMITEUR_DE_NOMBRE', 'Number delimiter'); 

define('TXT_VIRGULE', 'Comma');
define('TXT_DELIMITEUR_POINT', 'Period'); 

define('TXT_POINT', 'Point'); 
define('TXT_TITRE_DE_LA_LANGUE', 'Language title'); 
define('TXT_INSCRIRE_COMMENTAIRE_GESTION_LANGUES', 'Type a useful note for the management of languages'); 
define('TXT_AJOUTER_UN_MEDIA','Add media'); 
define('TXT_AJOUTER_UN_NOUVEAU_MEDIA', 'Add new media'); 
define('TXT_NOUVEAU_MEDIA','Untitled media'); 
define('TXT_TITRE_DU_MEDIA', 'Media title'); 
define('TXT_DESCRIPTION', 'Description'); 
define('TXT_MEDIA', 'Media'); 
define('TXT_CHARGEMENT_EN_COURS', 'Loading'); 
define('TXT_CHOISIR_DE_LA_BIBLIOTHEQUE','Choose from library'); 
define('TXT_CHOISIR_UNE_IMAGE_DE_LA_BIBLIOTHEQUE','Choose an image file from library'); 
define('TXT_CHOISIR_UNE_VIDEO_DE_LA_BIBLIOTHEQUE','Choose video file from library'); 
define('TXT_CHOISIR_UN_SON_DE_LA_BIBLIOTHEQUE','Choose audio file from library'); 
define('TXT_IMPORTER_UN_NOUVEAU_FICHIER', 'Import a new file'); 
define('TXT_SELECTION_FICHIER_SUR_VOTRE_ORDINATEUR', 'Select a file from your computer'); 
define('TXT_MEDIA_PROVENANT_AUTRE_SITE', 'Media from another site'); 
define('TXT_FICHIER_MEDIA', 'Media File'); 
define('TXT_NOUVEAU_FICHIER','New file'); 
define('TXT_MEDIAS', 'Media'); 
define('TXT_ACCUEIL', 'Home'); 
define('TXT_ERREUR', 'Error'); 
define('TXT_SOURCE', 'Source'); 
define('TXT_FICHIER', 'File'); 
define('TXT_CHOIX_DE_REPONSES', 'Choice of answers'); 
define('TXT_CHOIX_DE_REPONSE', 'Choice of answer'); 
define('TXT_BOUTONS','Buttons'); 
define('TXT_OK','OK'); 
define('TXT_CONSIGNES','Instructions'); 
define('TXT_QUESTION_TYPE_ASSOCIATION','Matching question'); 
define('TXT_QUESTION_TYPE_CHOIX_MULTIPLES','Multiple choice question'); 
define('TXT_QUESTION_TYPE_CLASSEMENT','Classification question'); 
define('TXT_QUESTION_TYPE_DAMIER_CASES_MASQUEES','Matching board question (hidden squares)'); 
define('TXT_QUESTION_TYPE_DAMIER_CASES_NON_MASQUEES','Matching board question (visible squares)'); 
define('TXT_QUESTION_TYPE_DEVELOPPEMENT','Essay question'); 
define('TXT_QUESTION_TYPE_DICTEE_CONSIGNE','Dictation question (beginning of the instructions)'); 
define('TXT_QUESTION_TYPE_DICTEE_MAJUSCULES','Dictation question (capital/small letter option)'); 
define('TXT_QUESTION_TYPE_DICTEE_PONCTUATION','Dictation (punctuation option)'); 
define('TXT_QUESTION_TYPE_MARQUAGE','Highlight text question'); 
define('TXT_QUESTION_TYPE_MISE_EN_ORDRE','Sequencing question'); 
define('TXT_QUESTION_TYPE_REPONSE_BREVE_CONSIGNE','Short answer question (beginning of the instructions)'); 
define('TXT_QUESTION_TYPE_REPONSE_BREVE_MAJUSCULES','Short answer question (capital/small letter option)'); 
define('TXT_QUESTION_TYPE_REPONSE_BREVE_PONCTUATION','Short answer question (punctuation option)'); 
define('TXT_QUESTION_TYPE_REPONSES_MULTIPLES_UNE_BONNE_REPONSE','Multiple answer question (at least one correct answer) '); 
define('TXT_QUESTION_TYPE_REPONSES_MULTIPLES_TOUTES_BONNES_REPONSES','Multiple answer question (all correct answers)'); 
define('TXT_QUESTION_TYPE_TEXTE_LACUNAIRE_MENU','Fill in the blanks question (drop-down menu)'); 
define('TXT_QUESTION_TYPE_TEXTE_LACUNAIRE_GLISSER','Fill in the blanks question (drag and drop)'); 
define('TXT_QUESTION_TYPE_TEXTE_LACUNAIRE_CONSIGNE','Fill in the blanks question (short answer, beginning of the instructions)'); 
define('TXT_QUESTION_TYPE_TEXTE_LACUNAIRE_MAJUSCULES','Fill in the blanks question (short answer, capital/small letter option)'); 
define('TXT_QUESTION_TYPE_TEXTE_LACUNAIRE_PONCTUATION','Fill in the blanks question (short answer, punctuation option)'); 
define('TXT_QUESTION_TYPE_VRAI_OU_FAUX','True/False question'); 
define('TXT_QUESTION_TYPE_ZONES_A_IDENTIFIER','Parts of an image question'); 
define('TXT_FENETRES','Windows'); 
define('TXT_RENSEIGNEMENT_SUR_LE_REPONDANT','Information about the user'); 
define('TXT_NOM','Last name'); 
define('TXT_PRENOM','First name'); 
define('TXT_MATRICULE','Identifier'); 
define('TXT_GROUPE','Group'); 
define('TXT_COURRIEL','Email'); 
define('TXT_AUTRE','Other'); 
define('TXT_ENVOI_DES_RESULTATS_PAR_COURRIEL','Send results by email'); 
define('TXT_COURRIEL_DU_DESTINATAIRE','Destination email'); 
define('TXT_FONCTIONNALITES','Features'); 
define('TXT_COMMENCER','Start'); 
define('TXT_EFFACER_LES_MARQUES','Erase selected highlighting'); 
define('TXT_ENVOYER_PAR_COURRIEL','Send by email'); 
define('TXT_RECOMMENCER','Start over'); 
define('TXT_REPRENDRE','Reset'); 
define('TXT_RESULTATS','Results'); 
define('TXT_SOLUTION','Correct Answer'); 
define('TXT_VALIDER','Submit'); 
define('TXT_MENU_DE_NAVIGATION','Navigation menu'); 
define('TXT_MESSAGE_GENERAUX','General messages (all types of items)'); 
define('TXT_MESSAGE_BONNE_REPONSE','Message for Correct Answer'); 
define('TXT_MESSAGE_MAUVAISE_REPONSE','Message for Incorrect Answer'); 
define('TXT_MESSAGE_REPONSE_INCOMPLETE','Message for Incomplete Answer'); 
define('TXT_MESSAGES_PARTICULIERS','Specific messages (for certain types of items)'); 
define('TXT_MESSAGE_POUR_MOTS_EN_TROP','Message for superfluous words (Dictation)'); 
define('TXT_MESSAGE_POUR_MOTS_MAL_ORTHOGRAPHIES','Message for spelling mistakes (Dictation)'); 
define('TXT_MESSAGE_POUR_MOTS_MANQUANTS','Message for words missing (Dictation)'); 
define('TXT_MESSAGE_POUR_REPONSE_SUGGEREE','Message for suggested answer (Essay)'); 
define('TXT_TABLEAU_DE_RESULTATS','Results table'); 
define('TXT_A_FAIRE','To be done'); 
define('TXT_A_REPRENDRE','To be done over'); 
define('TXT_MESSAGE_DE_CONFIRMATION_REPRISE_QUESTIONNAIRE','Confirmation message to start over'); 
define('TXT_NOMBRE_ESSAIS','Number of tries'); 
define('TXT_POINTS','Points'); 
define('TXT_POINTS_POUR_MOTS_MAL_ORTHOGRAPHIES','Points removed for word not spelled correctly'); 
define('TXT_REUSSI','Successfully finished'); 
define('TXT_SANS_OBJET','N/A'); 
define('TXT_TEMPS_DE_REPONSE','Response time'); 
define('TXT_TYPES_ITEMS','Items type (to display their specific instructions)'); 
define('TXT_EX_2_DE_30', '(ex. 2 of 30)'); 
define('TXT_CONJONCTION_ET', 'Conjunction and'); 
define('TXT_MON_COMPTE', 'My Account'); 
define('TXT_NOUVEAU_MOT_PASSE', 'New password'); 
define('TXT_NOUVEAU_MOT_PASSE_CONF', 'Confirm new password'); 
define('TXT_MOT_PASSE_ACTUEL','Current password'); 
define('TXT_MDP_INSTRUCTIONS', '(Minimum of 8 characters, including at least one letter and one number)'); 
define('TXT_CODE_USAGER_INSTRUCTIONS', '(Minimum of 5 characters, without spaces, including only letters, numbers, underscore(_) or dash(-))'); 
define('TXT_MON_MOT_DE_PASSE', 'My Password'); 
define('TXT_POUR_LA_CORRECTION_TENIR_COMPTE', 'When correcting, take into account'); 
define('TXT_DES_MAJUSCULES_MINUSCULES', 'capital letters/small letters'); 
define('TXT_DE_LA_PONCTUATION', 'punctuation'); 
define('TXT_MOT_PASSE_OU_NOM_UTILISATEUR_OUBLIE','Forgot your password or username?'); 
define('TXT_SAISISSEZ_VOTRE_ADRESSE_COURRIEL','Enter your email address and you will receive an email on how to access your account.'); 
define('TXT_ENVOYER', 'Send'); 
define('TXT_RETOUR_A_LA_CONNEXION','Return to the login page'); 
define('TXT_COURRIEL_RAPPEL_OBJET', 'Netquiz Web - Password or username retrieval'); 
define('TXT_COURRIEL_RAPPEL_BONJOUR','Hi'); 
define('TXT_COURRIEL_RAPPEL_LIGNE1','You forgot your password or username of your Netquiz Web account. To access the site, you\'ll need to reset your password by clicking on the following link:'); 
define('TXT_COURRIEL_RAPPEL_LIGNE2','If the above link does not work, please copy and paste it in your browser bar.'); 
define('TXT_COURRIEL_RAPPEL_LIGNE3','NB: If you do not want to reset your password, please ignore this message. Your password will not be reset. In the case of a problem or if it is not you who made this request, please let us know by returning this email.'); 
define('TXT_COURRIEL_RAPPEL_MERCI','Thank you for using Netquiz Web.'); 
define('TXT_REINITIALISER_VOTRE_MOT_PASSE', 'Reset your password'); 
define('TXT_NOM_UTILISATEUR', 'Username'); 
define('TXT_ERREURS_DETECTEES_ITEM', 'Errors detected in the item validation'); 
define('TXT_ERREURS_DETECTEES_QUESTIONNAIRE', 'Errors detected in the quiz'); 
define('TXT_SANS_TITRE', 'Untitled'); 
define('TXT_ADRESSE_DU_DOSSIER_EN_LIGNE', 'Unique identifier for the URL of publication'); 
define('TXT_QUESTIONNAIRE_PUBLIE_AVEC_SUCCES', 'The quiz was successfully published'); 
define('TXT_ADRESSE_DU_DOSSIER_EN_LIGNE_EST', 'Published quiz URL is'); 
define('TXT_FERMER', 'Close'); 
define('TXT_VOIR_LE_QUESTIONNAIRE_PUBLIE', 'View published quiz'); 
define('TXT_FICHIER_ACTUEL', 'Current file'); 
define('TXT_AUCUN_FICHIER_SELECTIONNE', 'No file selected'); 
define('TXT_AJOUTER_A_UN_QUESTIONNAIRE', 'Add to a quiz'); 
define('TXT_LANGUE_DE_APERCU', 'Language of preview'); 
define('TXT_LANGUE_DEFAUT', 'Default language for preview and publication');
define('TXT_THEME_DE_APERCU', 'Theme of preview'); 
define('TXT_THEME_DEFAUT', 'Defaut theme for preview and publication');
define('TXT_SUPPRIMER', 'Delete'); 
define('TXT_AJOUTER', 'Add'); 
define('TXT_INSCRIRE_VOTRE_TEXTE', 'Type your text'); 
define('TXT_CHERCHER', 'Search'); 
define('TXT_CHOISIR_DES_ITEMS_DE_LA_BIBLIOTHEQUE','Choose items from library'); 
define('TXT_TELECHARGER_QUESTIONNAIRE_WEB','Download web quiz'); 
define('TXT_CHOISIR_UN_QUESTIONNAIRE','Choose a quiz'); 
define('TXT_MESSAGE_LIBELLE_SOLUTION', 'Correct answer label'); 
define('TXT_RESULTATS_OBJET_COURRIEL','Subject field'); 
define('TXT_RESULTATS_MESSAGE_COURRIEL_SUCCES','Email successfully sent message'); 
define('TXT_RESULTATS_MESSAGE_COURRIEL_ERREUR','Error on sending email message');
define('TXT_CALCULER','Calculate'); 
define('TXT_NE_PAS_CALCULER','Do not calculate'); 
define('TXT_IMPORTER', 'Import'); 
define('TXT_POSITION', 'Position'); 
define('TXT_ID_ITEM', 'id_item'); 
define('TXT_ID_MEDIA', 'id_media'); 
define('TXT_ID_QUEST', 'id_quiz'); 
define('TXT_INSCRIRE_NOUVELLE_CATEGORIE_AU_BESOIN', 'Add a new category if needed'); 
define('TXT_VRAI', 'True'); 
define('TXT_FAUX', 'False'); 
define('TXT_MOT_PASSE_MODIFIE_SUCCES', 'Your password was successfully modified'); 
define('TXT_VEUILLEZ', 'Please'); 
define('TXT_VOUS_CONNECTER', 'log in'); 
define('TXT_POUR_CONTINUER', 'to continue'); 
define('TXT_UTILISATEUR_DOIT_DONNER', 'The user must give...'); 
define('TXT_TOUTES_LES_BONNES_REPONSES','all the correct answers'); 
define('TXT_AU_MOINS_UNE_BONNE_REPONSE','at least one correct answer among the choices'); 
define('TXT_DEFINITION_DES_CLASSEURS','Step 1 - Define the folders'); 
define('TXT_EDITION_DU_CONTENU_DES_CLASSEURS','Step 2 - Add elements in folders'); 
define('TXT_TYPE_DE_CLASSEUR_ONGLET_ELEMENT','Type of folder (tab / element)'); 
define('TXT_INSCRIRE_VOTRE_LIBELLE','Type the tab label'); 
define('TXT_AJOUTER_UN_ELEMENT', 'Add an element'); 
define('TXT_SUPPRIMER_LES_ELEMENTS_SELECTIONNES', 'Delete selected elements'); 
define('TXT_RETROACTIONS_POUR_CHAQUE_CLASSEUR', 'Feedback for each folder'); 
define('TXT_INSCRIRE_RETROACTION_POSITIVE_CLASSEUR', 'Type your feedback if all the elements of this folder were found'); 
define('TXT_INSCRIRE_RETROACTION_NEGATIVE_CLASSEUR', 'Type your feedback if none of the elements of this folder was found'); 
define('TXT_INSCRIRE_RETROACTION_POUR_REPONSE_INCOMPLETE_CLASSEUR', 'Type your feedback if certain elements of this folder were omitted'); 
define('TXT_INSCRIRE_VOTRE_RETROACTION', 'Type your feedback'); 
define('TXT_INSCRIRE_VOTRE_RETROACTION_POSITIVE', 'Type your positive feedback'); 
define('TXT_INSCRIRE_VOTRE_RETROACTION_NEGATIVE', 'Type your negative feedback'); 
define('TXT_ORIENTATION_DES_ELEMENTS_A_CLASSER', 'Position of elements to be classified'); 
define('TXT_HORIZONTALE', 'Horizontal'); 
define('TXT_VERTICALE', 'Vertical'); 
define('TXT_TEXTE_ELEMENT', 'Text'); 
define('TXT_IMAGE_ELEMENT', 'Image'); 
define('TXT_BON_CLASSEUR', 'Correct folder'); 
define('TXT_CLASSEUR', 'Folder'); 
define('TXT_INSCRIRE_VOTRE_RETROACTION_POSITIVE_NEGATIVE', 'Type your feedback (positive if correct answer, negative otherwise)'); 
define('TXT_REPONSE_SUGGEREE', 'Suggested answer'); 
define('TXT_SOLUTION_DICTEE', 'Correct answer'); 
define('TXT_RETROACTIONS_GLOBALES', 'Global feedback'); 
define('TXT_RETROACTION_POSITIVE', 'Positive feedback'); 
define('TXT_RETROACTION_NEGATIVE', 'Negative feedback'); 
define('TXT_RETROACTION_POUR_REPONSE_INCOMPLETE', 'Feedback for incomplete answer'); 
define('TXT_POINTS_RETRANCHES_MOT_MAL_ORTHOGRAPHIES', 'Points deducted for misspelled words'); 
define('TXT_ELEMENT_ASSOCIE', 'Associated element'); 
define('TXT_RETROACTIONS', 'Feedback'); 
define('TXT_MASQUE', 'Mask image'); 
define('TXT_IMPORTER_ELEMENTS', 'Import elements'); 
define('TXT_REPONSE_PREVUE', 'Predicted answer'); 
define('TXT_RETROACTIONS_POUR_TOUTES_REPONSES_NON_PREVUES', 'Feedback for unpredicted answers'); 
define('TXT_INSCRIRE_RETROACTIONS_POUR_TOUTES_REPONSES_NON_PREVUES', 'Type your feedback for all the unpredicted answers'); 
define('TXT_COPIER_COLLER_CODE_HTML_OU_URL_DU_MEDIA', 'Copy/paste the HTML integration code or the media\'s URL address'); 
define('TXT_INSCRIRE_UNE_DESCRIPTION', 'Type a description'); 
define('TXT_INSCRIRE_UN_COMMENTAIRE_UTILE_POUR_GESTION_ITEMS', 'Type a useful note for the management of items'); 
define('TXT_INSCRIRE_UNE_REMARQUE_UTILE', 'Type a useful note for the management of this element');
define('TXT_INSCRIRE_UN_MESSAGE_PERSONNALISE_POUR_CET_ITEM_SINON_ETC', 'Type a personalized message for this item, otherwise the message shown in the published quiz will be the one defined in the general messages section of the language chosen for the quiz'); 
define('TXT_COULEUR_FOND_ELEMENT','Background color of the element'); 
define('TXT_COULEUR_FOND_ELEMENT_A_ASSOCIER','Background color of the element to associate'); 
define('TXT_TYPE_AFFICHAGE_DES_ELEMENTS_MASQUES','Type of display for the elements'); 
define('TXT_NON_MASQUES_AU_DEBUT','Not masked from the beginning'); 
define('TXT_MASQUES_AU_DEBUT','Masked from the beginning'); 
define('TXT_POINTS_RETRANCHES_PAR_MAUVAISE_REPONSE', 'Points deducted for incorrect answer'); 
define('TXT_DEFINITION_DES_COULEURS_DE_MARQUAGE', 'Step 1 - Define the highlighter colours'); 
define('TXT_INSCRIRE_RETROACTION_POSITIVE_MARQUAGE', 'Type your feedback if all sections to be highlighted in this color were found'); 
define('TXT_INSCRIRE_RETROACTION_NEGATIVE_MARQUAGE', 'Type your feedback if no sections to be highlighted in this color was found)'); 
define('TXT_INSCRIRE_RETROACTION_REPONSE_INCOMPLETE_MARQUAGE', 'Type your feedback if certain sections to be highlighted in this color were omitted'); 
define('TXT_EDITION_DU_TEXTE_ET_DES_MARQUES', 'Step 2 – Add text and highlighting'); 
define('TXT_SUPPRIMER_LES_MARQUES_SELECTIONNEES', 'Delete highlighted sections'); 
define('TXT_AJOUTER_UNE_MARQUE', 'Add highlight'); 
define('TXT_MARQUE', 'Highlight'); 
define('TXT_COULEUR_DE_CETTE_MARQUE', 'Highlight color'); 
define('TXT_RETROACTIONS_POUR_CHAQUE_COULEUR_DE_MARQUAGE', 'Feedback for every highlight colour'); 
define('TXT_CHOISIR_UNE_COULEUR', 'Choose a colour'); 
define('TXT_BLANC', 'White'); 
define('TXT_BEIGE', 'Beige'); 
define('TXT_GRIS', 'Grey'); 
define('TXT_BLEU', 'Blue'); 
define('TXT_ROSE', 'Pink'); 
define('TXT_JAUNE', 'Yellow'); 
define('TXT_VERT', 'Green'); 
define('TXT_POURPRE', 'Purple'); 
define('TXT_ORANGE', 'Orange'); 
define('TXT_TURQUOISE', 'Turquoise'); 
define('TXT_NOIR', 'Black'); 
define('TXT_ROUGE', 'Red'); 
define('TXT_FICHIER_A_IMPORTER', 'Import file'); 
define('TXT_RESULTATS_DE_L_IMPORTATION', 'Results from the last import'); 
define('TXT_INSCRIRE_VOTRE_CONSIGNE', 'Type instruction'); 
define('TXT_INSCRIRE_NOUVELLE_COLLECTION_AU_BESOIN', 'Create a new collection if needed'); 
define('TXT_POUR_REPONSE_BREVE_SEULEMENT', 'For short answer only'); 
define('TXT_CONTOUR_DES_ZONES_SUR_IMAGE_WEB', 'Box outline colour'); 
define('TXT_DEFINITION_DES_TYPES_DE_LACUNE', 'Step 1 - Define the type of blanks'); 
define('TXT_TYPE_DE_LACUNE', 'Type of blank'); 
define('TXT_PETIT_CHAMP_TEXTE', 'Small text field'); 
define('TXT_MOYEN_CHAMP_TEXTE', 'Medium text field'); 
define('TXT_GRAND_CHAMP_TEXTE', 'Large text field'); 
define('TXT_GLISSER_DEPOSER', 'Drag and Drop'); 
define('TXT_EDITION_DU_TEXTE_ET_DES_LACUNES', 'Step 2 - Add text and blanks'); 
define('TXT_SUPPRIMER_LES_LACUNES_SELECTIONNEES', 'Delete selected blanks'); 
define('TXT_AJOUTER_UNE_LACUNE', 'Add a blank'); 
define('TXT_LACUNE', 'Blank'); 
define('TXT_MAUVAISE_REPONSE', 'Incorrect answer'); 
define('TXT_TEXTE_AVEC_MARQUES', 'Highlighted Text'); 
define('TXT_MARQUES', 'Highlighted'); 
define('TXT_COULEURS', 'Colours'); 
define('TXT_ELEMENT_SANS_TEXTE', 'Untitled element'); 
define('TXT_ONGLET_SANS_IMAGE', 'Tab without image'); 
define('TXT_MENU_DEROULANT', 'Drop-down menu'); 
define('TXT_NOUVELLE_IMPORTATION', 'New import'); 
define('TXT_AUCUNE_INFORMATION', 'No information available for the current session'); 
define('TXT_DEMANDER_UN_COMPTE', 'Ask for an account'); 
define('TXT_DEMANDER_UN_COMPTE_LIGNE1', 'Send the following information and the site administrator will send you a confirmation email.'); 
define('TXT_MOT_DE_PASSE', 'Password'); 
define('TXT_CONFIRMER_LE_MOT_DE_PASSE', 'Confirm password'); 
define('TXT_NOUVEL_UTILISATEUR', 'New user'); 
define('TXT_NOUVEL_UTILISATEUR_LIGNE1', 'You are a first-time Netquiz Web user. All content that you create (items, quizzes, media, glossary, etc.) are grouped as a project. Complete the form below to create your first project. You can optionally create other projects to organize your content according to your needs. (To find out more about projects, <a href="#" onClick="NewWindow(\'http://aide.ccdmd.qc.ca/nqw/en/content/en-ajouter-de-nouveaux-projets\',\'aide\',\'1024\',\'800\',\'yes\',\'yes\',\'yes\')">see Netquiz Web Help</a>.)');
define('TXT_TITRE_DU_PROJET', 'Project title'); 
define('TXT_IDENTIFIANT_UNIQUE_DU_PROJET', 'Unique identifier'); 
define('TXT_IDENTIFIANT_UNIQUE_DU_PROJET_CONTRAINTES', 'Only lowercase letters, numbers, dash and underscores are allowed'); 
define('TXT_INSCRIRE_UN_IDENTIFIANT_UNIQUE', 'Type a unique identifier. Once saved, the identifier cannot be changed.'); 
define('TXT_CREER_ET_COMMENCER', 'Create and start'); 
define('TXT_NETQUIZ_WEB_ADMIN', 'Administration'); 
define('TXT_GESTION', 'Management'); 
define('TXT_PROJETS', 'Projects');
define('TXT_TOUS_LES_PROJETS', 'All Projects'); 
define('TXT_PROJET', 'Project'); 
define('TXT_UTILISATEURS', 'Users');
define('TXT_TOUS_LES_UTILISATEURS', 'All Users'); 
define('TXT_AJOUTER_UN_PROJET', 'Add a project'); 
define('TXT_IDENTIFIANT', 'Identifier'); 
define('TXT_RESPONSABLE', 'Manager'); 
define('TXT_RESPONSABLE_DU_PROJET', 'Project Manager'); 
define('TXT_AFFICHER_TOUS_LES_RESPONSABLES', 'Show all managers'); 
define('TXT_COLLABORATEURS_ACTUELS_DE_CE_PROJET', 'Actual collaborators');
define('TXT_COLLABORATEURS_INVITES_A_CE_PROJET', 'Invited collaborators - waiting for an answer');
define('TXT_COLLABORATEURS_INSTRUCTIONS', 'People who do not have accounts will be asked to create one'); 
define('TXT_COLLABORATEURS_INSTRUCTIONS2', 'Enter the email address of the person with whom you want to collaborate'); 
define('TXT_NOM_PRENOM', 'Last Name, First Name'); 
define('TXT_NOTIFIER_RESPONSABLE_ET_COLLABORATEURS', 'Notify the manager and collaborators of changes made'); 
define('TXT_NOTIFIER_COLLABORATEURS', 'Notify collaborators of changes made'); 
define('TXT_AJOUTER_UN_UTILISATEUR', 'Add a user'); 
define('TXT_AFFICHER_TOUS_LES_PROJETS', 'Show all projects'); 
define('TXT_PROJET_COURANT', 'Current project'); 
define('TXT_PROJET_COURANT_A_LA_CONNEXION', 'Current project at connection'); 
define('TXT_LISTE_PROJETS_DE_CET_UTILISATEUR', 'Project list of this user'); 
define('TXT_ADMINISTRATEUR', 'Administrator'); 
define('TXT_NOTIFIER_UTILISATEUR_DES_MODIFICATIONS', 'Notify user of changes made'); 
define('TXT_DEMANDE_TRANSMISE', 'The request has been sent. Approval may take 1-2 working days.'); 
define('TXT_DEMANDE_ACTIVATION_COMPTE_SUJET','Request to activate a Netquiz Web account'); 
define('TXT_DEMANDE_ACTIVATION_COMPTE_TEXTE','A new user has registered. This request requires your approval:'); 
define('TXT_COMPTE','Account'); 
define('TXT_MES_PROJETS','My Projects'); 
define('TXT_DERNIER_ACCES', 'Last access'); 
define('TXT_ADMINISTRATION', 'Administration'); 
define('TXT_COURRIEL_APPROBATION_OBJET', 'Netquiz Web - Account request'); 
define('TXT_COURRIEL_APPROBATION_BONJOUR','Hi'); 
define('TXT_COURRIEL_APPROBATION_LIGNE1','Your account has been approved. You can now login at:'); 
define('TXT_COURRIEL_APPROBATION_LIGNE2','If the above link does not work, please copy and paste it in your browser bar.'); 
define('TXT_COURRIEL_APPROBATION_MERCI','Thank you for using Netquiz Web.'); 
define('TXT_COURRIEL_REFUS_OBJET', 'Netquiz Web - Account request'); 
define('TXT_COURRIEL_REFUS_BONJOUR','Hi'); 
define('TXT_COURRIEL_REFUS_LIGNE1','Your account request has been refused.'); 
define('TXT_COURRIEL_REFUS_LIGNE2','For more information, please contact the administrator.'); 
define('TXT_LANGUE_INTERFACE','Interface Language'); 
define('TXT_APROPOS_COMMENTAIRE_1','Your opinion is very important to us. Go to the Comments section on the Netquiz Web Product Summary sheet to give us your feedback. You can also refer to the FAQ section.');
define('TXT_APROPOS_COMMENTAIRE_ALLER_SECTION','Go to the');
define('TXT_APROPOS_COMMENTAIRE_COMMENTAIRES','Comments section');
define('TXT_APROPOS_COMMENTAIRE_URL','http://www.ccdmd.qc.ca/eng/catalog/netquiz-web');
define('TXT_DROITS_UTILISATION_NQW','Netquiz Web is an <a href="#" onClick="window.open(\'https://github.com/CCDMD/netquizweb/blob/master/LICENSE\')">open-source</a> software. You can contribute to the development of this software by going to the website <a href="#" onClick="window.open(\'https://github.com/CCDMD/netquizweb\')">Github</a>. For more information, contact us at <a href="mailto:info@ccdmd.qc.ca">info@ccdmd.qc.ca</a>.');
define('TXT_GENERIQUE_LIGNE_1','<p>Netquiz Web was created by the Centre collegial de développement de materiel didactique (CCDMD, 2014). This product is developed and maintained by CCDMD and the community of open source software on <a href="#" onClick="window.open(\'https://github.com/CCDMD/netquizweb\')">GitHub</a>.</p>');
define('TXT_GENERIQUE_LIGNE_2','<h3> Software Design</h3>Lucie Tr&eacute;panier, CCDMD<br />Christine Blais<br /><br />');
define('TXT_GENERIQUE_LIGNE_3','<h3>Computer design and programming</h3>Richard Dumoulin, e-Summum inc.<br /><br />');
define('TXT_GENERIQUE_LIGNE_4','<h3>Themes Programming</h3>Robert Szczech<br /><br />');
define('TXT_GENERIQUE_LIGNE_5','<h3>Graphic Design (Software and Themes)</h3>Christine Blais<br /><br />');
define('TXT_GENERIQUE_LIGNE_6','<h3>Web Integrator (Software)</h3>V&eacute;ronique Pivetta<br /><br />');
define('TXT_GENERIQUE_LIGNE_7','<h3>Testing and Debugging</h3>Sylvain Gagnon, CCDMD<br /><br />');
define('TXT_GENERIQUE_LIGNE_8','<h3>English Translation</h3>Paulette Cake, CCDMD<br /><br />');
define('TXT_GENERIQUE_LIGNE_9','<h3>« Help » Authors</h3>Raymond Cantin, CCDMD<br /><br />');
/*define('TXT_GENERIQUE_LIGNE_10','<h3>Linguistic Revision (english)</h3>TBC<br /><br />');
define('TXT_GENERIQUE_LIGNE_11','<h3>Linguistic Revision (french)</h3>TBC<br /><br />');*/
define('TXT_GENERIQUE_LIGNE_10','');
define('TXT_GENERIQUE_LIGNE_11','<h3>Project Manager</h3>Lucie Tr&eacute;panier, CCDMD<br /><br /><br />');
define('TXT_GENERIQUE_LIGNE_12','<br /><em>Netquiz Web</em> uses the jQuery plugin <a href="#" onClick="window.open(\'https://github.com/mjsarfatti/nestedSortable\')">nestedSortable</a>, developed by Manuele J Sarfatti (MIT License), and widget library <a href="#" onClick="window.open(\'http://www.jqwidgets.com/license/\')">jQWidgets</a>, under the Creative Commons Attribution-NonCommercial 3.0 License (<a href="#" onClick="window.open(\'http://creativecommons.org/licenses/by-nc/3.0/\')">CC BY-NC 3.0</a>). Note: jQWidgets (&copy; 2011-2014) is not free for commercial use.');
define('TXT_INTRO_LIGNE_1','Netquiz Web is a multilingual, multiplatform and multi-user Web-based software that generates question banks for evaluation purposes. There are 14 question-types available: Matching, Multiple Choice, Classification, Dictation, Highlight, Identification, Essay, Fill-in-the-Blanks, Sequencing, Multiple Answer, Short Answer, True or False, Matching Board, Page. The software allows users to publish exercises, formative quizzes or tests in a single click. In all types of items, it is possible to insert images, text, sound and video clips and customize many parameters. Users can also add a glossary, so that words and expressions appear highlighted in the quiz, allowing respondents to obtain their definitions in the form of text, image, video, sound or links.<br /><br />Netquiz Web does not yet allow for the collection of results. Depending on demand, this feature may be added in the future. In the meantime, users who wish to generate summative tests can use the <a href="#" onClick="window.open(\'http://www.ccdmd.qc.ca/eng/catalog/netquiz-pro-29\')">Netquiz 2.9</a> version, which is free to download from the CCDMD website.<br /><br /><strong>Note:</strong>&nbsp;For users who have already created question banks in previous versions (2.9 and Pro 4), follow these steps to import them into Netquiz Web:<br /><br />- Open the .npro file in <a href="#" onClick="window.open(\'http://www.ccdmd.qc.ca/eng/catalog/netquiz-pro-4\')">Netquiz Pro 4</a>, version 4.96 or higher<br />- Click on FILE, then choose EXPORT to XML format<br />- Find the folder on the desktop (<nameoffile>.npro_XML)<br />- Zip this folder (Note: for MAC OS X, zip all files in the folder)<br />- Go to Netquiz Web and choose IMPORT ELEMENTS which is found in the MY Quizzes menu<br />- Follow the instructions.');
define('TXT_CONFIRMER_REFUS_COMPTE', 'Are you sure you want to refuse this account?');
define('TXT_NOUVEAU_PROJET', 'Untitled project'); 
define('TXT_CONFIRMER_MISE_CORBEILLE_PROJET', "Quizzes published in projects sent to the recycle bin will be lost forever.\\n\\nAre you sure you want to continue?"); 
define('TXT_CONFIRMER_SUPPRESSION_ELEMENTS', 'Deleting selected elements will be final and irreversible. If you delete a project, its elements (quizzes, items, media, terms...) will also be deleted.\\n\\nAre you sure you want to continue?'); 
define('TXT_STATUT_DU_PROJET', 'Project status');
define('TXT_DATE_ENVOI_INVITATION', 'Invitation request date'); 
define('TXT_ENVOI_COURRIEL', 'Send an email');
define('TXT_RETIRER_ACCESS', 'Deny access to project');
define('TXT_SUPPRIMER_INVITATION', 'Delete invitation'); 
define('TXT_INVITER_NOUVEAU_COLLABORATEUR', 'Invite a new collaborator');
define('TXT_ENVOI', 'Send invitation'); 
define('TXT_COLLABORATEUR_NOTE', 'Attention! Collaborators can add, modify, and delete project content.<br />Collaborators will be advised by email of any changes in this project (project title, project description, project status, collaborators, etc.).'); 
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_OBJET', "Request to collaborate on a Netquiz Web project");
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_BONJOUR','Hi'); 
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_LIGNE1A','invites you to collaborate on the Netquiz Web project');
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_LIGNE1B','');
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_LIGNE2','To access the project, click on the following link or copy it into your web browser:'); 
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_LIGNE3','You must first fill out a form to create your Netquiz Web account.'); 
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_MERCI','Thank you!');
define('TXT_COURRIEL_COLLABORATEUR_INVITATION_SIGNATURE','The Netquiz Web technical support team');
define('TXT_COURRIEL_COLLABORATEUR_RETRAIT_OBJET', "End of Netquiz Web project collaboration");
define('TXT_COURRIEL_COLLABORATEUR_RETRAIT_BONJOUR','Hi'); 
define('TXT_COURRIEL_COLLABORATEUR_RETRAIT_LIGNE1A','Your name has been removed from the collaborators list for the project');
define('TXT_COURRIEL_COLLABORATEUR_RETRAIT_LIGNE1B','of');
define('TXT_COURRIEL_COLLABORATEUR_RETRAIT_LIGNE2','For more information, contact this person.');
define('TXT_COURRIEL_COLLABORATEUR_RETRAIT_MERCI','Thank you!');
define('TXT_COURRIEL_COLLABORATEUR_RETRAIT_SIGNATURE','The Netquiz Web technical support team');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_OBJET', "Changes to a Netquiz Web project"); 
define('TXT_COURRIEL_PROJET_MODIFICATIONS_BONJOUR','Hi');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_LIGNE1A','At the URL'); 
define('TXT_COURRIEL_PROJET_MODIFICATIONS_LIGNE1B',', one or more changes have been made to the project "');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_LIGNE1C','" on which you are collaborating:'); 
define('TXT_COURRIEL_PROJET_MODIFICATIONS_TITRE1',' - The project title has been changed from "');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_TITRE2','" to "');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_TITRE3','".');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_RESPONSABLE1',' - The project manager has been changed to "');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_RESPONSABLE2','" to "'); 
define('TXT_COURRIEL_PROJET_MODIFICATIONS_RESPONSABLE3','".');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_STATUT_INACTIF',' - The project is now inactive.'); 
define('TXT_COURRIEL_PROJET_MODIFICATIONS_STATUT_ACTIF',' - The project is now active.'); 
define('TXT_COURRIEL_PROJET_MODIFICATIONS_MERCI','Thank you!');
define('TXT_COURRIEL_NOUVEAU_RESPONSABLE_OBJET', "New manager of Netquiz Web project");
define('TXT_COURRIEL_NOUVEAU_RESPONSABLE_BONJOUR','Hi');
define('TXT_COURRIEL_NOUVEAU_RESPONSABLE_LIGNE1A','has made you the project manager for the projet "');
define('TXT_COURRIEL_NOUVEAU_RESPONSABLE_LIGNE1B','" in Netquiz Web.');
define('TXT_COURRIEL_NOUVEAU_RESPONSABLE_LIGNE2','You can access Netquiz Web by clicking on this link:'); 
define('TXT_COURRIEL_NOUVEAU_RESPONSABLE_SIGNATURE','The Netquiz Web technical support team');
define('TXT_COURRIEL_NOUVEAU_RESPONSABLE_MERCI','Thank you!');
define('TXT_COURRIEL_PROJET_MODIFICATIONS_SIGNATURE','The Netquiz Web technical support team');
define('TXT_NOMMER_RESPONSABLE','Name as project manager'); 
define('TXT_NOMMER_RESPONSABLE_AVERTISSEMENT','By making another person project manager, you become a collaborator to this project, and you will lose the right to manage it. Would you like to continue?');
define('TXT_ACTIF', 'Active');
define('TXT_INACTIF', 'Inactive');
define('TXT_RETOUR', 'Back');
define('TXT_ME_RETIRER_DE_LA_LISTE_DES_COLLABORATEURS', 'Remove me from the collaborators\' list');
define('TXT_CONFIRMER_RETRAIT_DE_LA_LISTE_DES_COLLABORATEURS' , 'Are you sure you want to be removed from the collaborators\' list for this project ? This action is irreversible.'); 
define('TXT_INFORMATION', 'Profile');
define('TXT_PREFERENCES', 'Preferences');
define('TXT_ENVOYER_UN_COURRIEL','Send an email');
define('TXT_NOMMER_RESPONSABLE_AVERTISSEMENT_ADMIN','By making another person project manager, the actual project manager will become a collaborator of this project, and will lose the rights to manage it. Would you like to continue?');
define('TXT_APPROUVER_LA_DEMANDE', 'Approve the request');
define('TXT_AFFICHER_TOUS_LES_UTILISATEURS', 'Display all users');
define('TXT_AFFICHER_TOUS_LES_UTILISATEURS_ACTIFS', 'Display active users');
define('TXT_AFFICHER_TOUS_LES_UTILISATEURS_VERROUILLES', 'Display locked users');
define('TXT_AFFICHER_TOUS_LES_UTILISATEURS_EN_ATTENTE_APPROBATION', 'Display users waiting for approval');
define('TXT_AFFICHER_TOUS_LES_UTILISATEURS_AVEC_ACCES_REFUSES', 'Display users whose access has been denied');
define('TXT_ROLE', 'Role');
define('TXT_UTILISATEUR', 'User');
define('TXT_INSCRIRE_NOUVEAU_MOT_PASSE_SI_DESIRE', 'Write a new password if desired');
define('TXT_REPETER_NOUVEAU_MOT_PASSE','Confirm new password');
define('TXT_NB_MAUVAIS_ESSAIS_MDP', 'Number of incorrect tries');
define('TXT_COMPTE_VERROUILLE', 'The account is locked after');
define('TXT_NOUVEL_UTILISATEUR_SANS_NOM', 'New user without a name');
define('TXT_CONFIRMER_APPROBATION', 'Approve access to the selected users?');
define('TXT_COLLABORATION', 'Collaboration');
define('TXT_TEXTES', 'Texts');
define('TXT_MESSAGE_AVERTISSEMENT_TEMPORAIRE', 'Warning message on the connection page');
define('TXT_INSCRIRE_MESSAGE_AVERTISSEMENT_TEMPORAIRE', 'Write a warning message on the connection page');
define('TXT_TEXTE_SUPPLEMENTAIRE_MOT_BIENVENUE', 'Supplementary text for welcome message');
define('TXT_INSCRIRE_TEXTE_SUPPLEMENTAIRE_MOT_BIENVENUE', 'Write supplementary text to the welcome message');
define('TXT_DERNIERE_EXPORTATION', 'Last export');
define('TXT_JS_CONFIRMER_INDEXATION1', 'This function will update ');
define('TXT_JS_CONFIRMER_INDEXATION2', ' search indexes and may take time. Start indexing?');
define('TXT_SUPPRIMER_CET_ELEMENT', 'Delete this element');
define('TXT_SUPPRIMER_CETTE_MARQUE', 'Delete this highlight');
define('TXT_TEXTE_DE_LA_MARQUE', 'Highlighted text');
define('TXT_SUPPRIMER_CETTE_LACUNE', 'Delete this blank');
define('TXT_LEXIQUE', 'Glossary');
define('TXT_MESSAGE_DE_CONFIRMATION_RETOUR_ACCUEIL', 'Confirmation message to return to home page');
define('TXT_LANCER_INDEXATION', 'Launch the indexing of the following elements');
define('TXT_COURRIEL_CREATION_COMPTE_ADMIN', 'Netquiz Web – Creation of an administrator account');
define('TXT_COURRIEL_COMPTE_ADMIN_BONJOUR','Hi');
define('TXT_COURRIEL_COMPTE_ADMIN_LIGNE1','Your administrator account has been created. You can now login at');
define('TXT_COURRIEL_COMPTE_ADMIN_LIGNE2','If the above link does not work, please copy and paste it in your browser bar.');
define('TXT_COURRIEL_COMPTE_ADMIN_MERCI','Thank you for using Netquiz Web.');
define('TXT_MES_TERMES', 'My Terms');
define('TXT_NOUVEAU_TERME', 'Untitled term');
define('TXT_TERMES', 'Terms');
define('TXT_TERME', 'Term');
define('TXT_VARIANTES', 'Variants');
define('TXT_DEFINITION', 'Definition');
define('TXT_AJOUTER_UN_NOUVEAU_TERME', 'Add a new term');
define('TXT_INSCRIRE_VARIANTES', 'Enter the variants');
define('TXT_INSCRIRE_DEFINITION', 'Type the definition');
define('TXT_INSERER_UNE_ADRESSE_URL', 'Enter full URL (include http:// or https://)');
define('TXT_INSERER_UNE_ADRESSE_URL_VERS_UN_DOCUMENT', 'Enter the URL of a PDF document, an image, a video, a website, etc..');
define('TXT_SEPAREES_PAR_DES_RETOUR', 'separated by a carriage return');
define('TXT_VOULEZ_VOUS_SUPPRIMER_CE_TERME', 'Are you sure you want to delete this term? This action is irreversible.');
define('TXT_VOULEZ_VOUS_SUPPRIMER_CES_TERMES', 'Are you sure you want to delete this or these terms? This action is irreversible.');
define('TXT_TERMES_A_INCLURE', 'Terms from the library to include in the quiz\'s glossary');
define('TXT_INSCRIRE_UN_COMMENTAIRE_UTILE_POUR_GESTION_QUESTIONNAIRES', 'Type a useful note for the management of quizzes.');
define('TXT_AVERTISSEMENT_FIN_SESSION', 'Your Netquiz Web session has been inactive for too long and will expire shortly. Please save your changes now, to reactivate.');
define('TXT_AVERTISSEMENT_SESSION_EXPIREE', 'Your Netquiz Web session has expired. You\'re no longer able to save your changes. If necessary, please note or copy them to an external file, in order to resume your work when you connect again.');
define('TXT_AVERTISSEMENT_ANNULER', 'Do you really want to undo those changes? This action is irreversible.');
define('TXT_AVERTISSEMENT_DESACTIVER_PUBLICATON', 'Do you really want to unpublish this quiz? This action is irreversible.');
define('TXT_AVERTISSEMENT', 'Warning');
define('TXT_VERSION_NQW', 'Current version of Netquiz Web');
define('TXT_ID_LANGUE', 'Language ID');
define('TXT_ID_TERME', 'Term ID');
define('TXT_ID_COLLECTION', 'Collection ID');
define('TXT_ID_CATEGORIE', 'Category ID');
define('TXT_INSTALLATION_NETQUIZ_WEB', 'Netquiz Web Installation');
define('TXT_TOUS_LES_PREREQUIS_TECHNIQUES_ONT_ETE_VALIDES', 'The software requirements have been verified');
define('TXT_ETAPE_1_DE_3', 'Step 1 of 3: Verification of software requirements');
define('TXT_ETAPE_2_DE_3', 'Step 2 of 3: Creation of an administrator account');
define('TXT_ETAPE_3_DE_3', 'Step 3 of 3: Confirmation of installation');
define('TXT_SAISIR_INFOS_ADMIN', 'Enter administrator account information');
define('TXT_INSTALLATION_TERMINEE', 'The installation of Netquiz Web has been completed');
define('TXT_DEBUTER_UTILISATION', 'You can now start using Netquiz Web');
define('TXT_ESSAYER_A_NOUVEAU', 'Try again');
define('TXT_CONTINUER', 'Continue');

define('TXT_PERMETTRE_ACCES', 'Restore the site to online mode');
define('TXT_FERMER_ACCES', 'Put site into maintenance mode');
define('TXT_AFFICHER_TOUS_LES_ADMINISTRATEURS', 'Show all administrators');
define('TXT_CONSIGNE_PUBLICATION1', 'Warning! Each quiz must be published to a unique URL that you can send to your respondents.');
define('TXT_CONSIGNE_PUBLICATION2', 'You can republish a quiz to the same URL. If you want to publish to a new URL, the old publication will be destroyed and replaced by the new one.');
define('TXT_MAINTENANCE_LIGNE1', 'Warning! The execution of maintenance functions may have a temporary effect on site performances or access to the site by users. Plan your actions accordingly.');
define('TXT_VERSION_ACTUELLE', 'Current version of Netquiz Web');
define('TXT_MAINTENANCE_DU_SITE', 'Site maintenance');
define('TXT_MODE_MAINTENANCE', 'NB In maintenance mode, Netquiz Web is accessible only to the site administrators.');
define('TXT_SAUVEGARDE_DE_LA_BASE_DE_DONNEES', 'Saving the database');
define('TXT_EXPORTER_FORMAT_SQL', 'Export database');
define('TXT_INDEXATION', 'Indexing the database tables');
define('TXT_NOTE_SAUVEGARDE', 'NB Some updates can modify the Netquiz Web database. Export a copy of the current database to your computer in case you need to revert to this version.');
define('TXT_NOTE_INDEXATION1', 'NB Indexing the Netquiz Web database tables may be necessary after some updates. Do this only if you receive a message to this effect.');
define('TXT_NOTE_INDEXATION2', 'If you index one of these tables, please wait for the confirmation message before continuing.');
define('TXT_INDEXER_CATEGORIES', 'Indexing categories');
define('TXT_INDEXER_COLLECTIONS', 'Indexing collections');
define('TXT_INDEXER_ITEMS', 'Indexing items');
define('TXT_INDEXER_LANGUES', 'Indexing languages');
define('TXT_INDEXER_MEDIAS', 'Indexing media');
define('TXT_INDEXER_PROJETS', 'Indexing projects');
define('TXT_INDEXER_QUESTIONNAIRES', 'Indexing quizzes');
define('TXT_INDEXER_UTILISATEURS', 'Indexing users');
define('TXT_COORDONNEE_X', 'X coordinate');

define('TXT_COORDONNEE_Y', 'Y coordinate');

define('TXT_AVERTISSEMENT_NOUVEAU_VERROU', 'WARNING! One or more people are working on the same element as you. This could result in a loss of data if you save. If necessary, contact these people: ');

define('TXT_MAINTENANCE', 'Maintenance');

/** Langue **/ 
define('CHANGER_LANGUE_FR', 'fr_CA'); 
define('CHANGER_LANGUE_EN', 'en_CA');

/** Messages de confirmation */ 
define("MSG_001", "The information has been saved successfully"); 
define("MSG_002", ""); 
define("MSG_003", "The password has been updated successfully"); 
define("MSG_004", "The selected items have been added to the quiz"); 
define("MSG_005", "An email with instructions to reset your password has been sent."); 
define("MSG_006", "Items in this section contain no error."); 
define("MSG_007", "The quiz was successfully unpublished"); 
define("MSG_008", "The quiz was successfully published:"); 
define("MSG_009", "Import completed for the media "); 
define("MSG_010", "Import completed for the item "); 
define("MSG_011", "Import completed for the quiz "); 
define("MSG_012", "The request has been approved."); 
define("MSG_013", "The request has been refused."); 
define("MSG_014", "The selected item has been added to the quiz");
define("MSG_015", "The new project has been created and is ready to use.");
define("MSG_016", "The invitation was sent by email.");
define("MSG_017", "The new collaborator has been added to the project and has received a confirmation email.");
define("MSG_018", "The invitation request for this collaborator has been deleted.");
define("MSG_019", "The invitation requests for these collaborators have been removed.");
define("MSG_020", "Project access for this collaborator has been removed."); 
define("MSG_021", "Project access for these collaborators has been removed."); 
define("MSG_022", "The projects selected have been sent to the recycle bin."); 
define("MSG_023", "The projects selected have been sent to the recycle bin (except those that do not have you as project manager)");
define("MSG_024", "The role has been changed successfully.");
define("MSG_025", "You cannot remove yourself from the collaborators list for the projects selected because you are the project manager.");
define("MSG_026", "Some of the projects selected cannot be sent to the recycle bin because you are not the project manager.");
define("MSG_027", "You have been removed from the collaborators' list for these projects.");
define("MSG_028", "You have been removed from the collaborators' list for these projects (except those for which you are the project manager.)");
define("MSG_029", "Save new project information before naming a new project manager.");
define("MSG_030", "The selected users have been sent to the recycle bin.");
define("MSG_031", "Some of the selected users do not have the status 'Waiting for approval'. Impossible to continue.");
define("MSG_032", "The selected users now have access to Netquiz Web.");
define("MSG_033", "The indexation was completed successfully.");
define("MSG_034", "All the software requirements have been validated");
define("MSG_035", "One or more languages have not been put in the recycle bin because they are required by Netquiz Web.");
define("MSG_036", "One or more users have not been put in the recycle bin because they are Netquiz Web administrators.");
define("MSG_037", "Import completed for the collection ");
define("MSG_038", "Import completed for the category ");
define("MSG_039", "Import completed for the language ");
define("MSG_040", "Import completed for the term ");
define("MSG_041", "A Netquiz Web update is available at <a href='http://www.ccdmd.qc.ca/catalogue/netquiz-web' target='maj'>http://www.ccdmd.qc.ca/catalogue/netquiz-web</a>");
define("MSG_042", "An important update of Netquiz Web is available and must be installed.");
define("MSG_043", "A critical update of Netquiz Web is available and must be installed.");
define("MSG_044", "A security update of Netquiz Web is available and must be installed.");
define("MSG_045", "Unable to retrieve information regarding new versions of Netquiz Web.");
define("MSG_046", "Netquiz Web is currently undergoing maintenance and cannot be accessed by users who are not site administrators. Check back later. Thank you for your patience.");
define("MSG_047", "Netquiz Web is currently in maintenance mode and unavailable to users. If the update is complete, you can restore the site to online status in the Site Maintenance section.");



/** Messages d'erreurs */
define("ERR_000", "An error has occurred. Please try again. If the problem persists, contact the site administrator.");
define("ERR_001", "Impossible to connect to the database. Make sure the database is accessible or that the connection parameters of the configuration file are correct."); 
define("ERR_002", "Impossible to complete the log file. Verify the write permissions for the folder /ressources/journaux.");
define("ERR_003", " Impossible to access the user's data. If the problem persists, contact the site administrator.");
define("ERR_004", "Enter your email or username and your password."); 
define("ERR_005", "Incorrect username or password."); 
define("ERR_006", "The request is invalid. If the problem persists, contact the site administrator."); 
define("ERR_007", "You have logged out successfully. See you again soon!");
define("ERR_008", "Impossible to access quiz data. If the problem persists, contact the site administrator. If the problem persists, contact the site administrator.");
define("ERR_009", "The type of item specified is invalid or not available."); 
define("ERR_010", "The requested quiz is invalid or not available."); 
define("ERR_011", "Impossible to access the section data. If the problem persists, contact the site administrator."); 
define("ERR_012", "Impossible to retrieve files for the Web Preview. If the problem persists, contact the site administrator.");
define("ERR_013", "Impossible to create the media directory."); 
define("ERR_014", "This file format is not supported."); 
define("ERR_015", "Impossible to transfer file.");
define("ERR_016", "There is no account for this email.");
define("ERR_017", "The confirmation password does not match the new password entered."); 
define("ERR_018", "A technical error has occured. For more information, consult the software logs (/ressources/journaux) or contact the Netquiz site administrator if the problem persists.");
define("ERR_019", "Selected items have been added to the quiz, except those that are already part of it.");
define("ERR_020", "None of the selected items have been added as they are already part of the quiz.");
define("ERR_021", "Last name is invalid or missing.");
define("ERR_022", "First name is invalid or missing.");
define("ERR_023", "Email is invalid or missing."); 
define("ERR_024", "Password is invalid or missing."); 
define("ERR_025", "New password is invalid or missing.");
define("ERR_026", "New password confirmation is invalid or missing.");
define("ERR_027", "New password must be different from the old.");
define("ERR_028", "No account matches this email."); 
define("ERR_029", "An error occurred while sending the email. Please try again. If the problem persists, contact the site administrator.");
define("ERR_030", "The request is invalid or the confirmation code is missing or invalid."); 
define("ERR_031", "The correct answer was not selected from the answer choices."); 
define("ERR_032", "A question-type 'Mutliple Choice' must include at least 2 valid answer choices.");
define("ERR_033", "A section must contain text in the field 'Section Title'");
define("ERR_034", "The items in this section are error-free.");
define("ERR_035", "The quiz home page must contain text in the field 'Quiz title on homepage'.");
define("ERR_036", "The section must contain at least one item."); 
define("ERR_037", "The value of 'Weighting' field in the parameters of the item must be numerical.");
define("ERR_038", "The value of 'Weighting' field in the parameters of the item ('Values modified for this quiz only' section) must be numerical."); 
define("ERR_039", "The folder name is invalid or missing. A folder name must contain only letters, numbers, dashes or underscore."); 
define("ERR_040", "An error occurred while publishing the quiz. The identifier for the publication URL may already exist. Try a new identifier. If the problem persists, contact the site administrator.");
define("ERR_041", "No theme selected. Select a quiz theme before previewing or publishing."); 
define("ERR_042", "The selected theme folder does not exist. Choose another theme for this quiz."); 
define("ERR_043", "No item selected or impossible to export data for the selected items."); 
define("ERR_044", "Impossible to create a temporary folder to import. If the problem persists, contact the site administrator."); 
define("ERR_045", "Impossible to locate the zip file for import. If the problem persists, contact the site administrator.");
define("ERR_046", "The import file must be in zip format."); 
define("ERR_047", "An error occurred while transferring the zip file for import. If the problem persists, contact your site administrator."); 
define("ERR_048", "An error occurred while extracting the zip file for import. Please check the format of your file."); 
define("ERR_049", "Impossible to locate the XML file to import. (NB On Mac, you must compress the XML file and the MEDIA folder and not the parent folder.)"); 
define("ERR_050", "The XML tag 'id_item' is invalid or missing."); 
define("ERR_051", "The XML tag 'titre' is invalid or missing.");
define("ERR_052", "The XML tag 'info_comp1_titre' is invalid or missing.");
define("ERR_053", "The XML tag 'info_comp1_texte' is invalid or missing."); 
define("ERR_054", "The XML tag 'info_comp2_titre' is invalid or missing.");
define("ERR_055", "The XML tag 'info_comp2_texte' is invalid or missing.");
define("ERR_056", "The XML tag 'media_titre' is invalid or missing."); 
define("ERR_057", "The XML tag 'media_texte' is invalid or missing."); 
define("ERR_058", "The XML tag 'media_image' is invalid or missing."); 
define("ERR_059", "The XML tag 'media_son' is invalid or missing."); 
define("ERR_060", "The XML tag 'media_video' is invalid or missing.");
define("ERR_061", "The XML tag 'suivi' is invalid or missing.");
define("ERR_062", "The XML tag 'ponderation' is invalid or missing.");
define("ERR_063", "The XML tag 'ordre_presentation' is invalid or missing.");
define("ERR_064", "The XML tag 'type_etiquettes' est invalid ou absent.");
define("ERR_065", "The XML tag 'afficher_solution' is invalid or missing.");
define("ERR_066", "The XML tag 'points_retranches' is invalid or missing.");
define("ERR_067", "The XML tag 'majmin' is invalid or missing.");
define("ERR_068", "The XML tag 'ponctuation' is invalid or missing.");
define("ERR_069", "The XML tag 'type_elements1' is invalid or missing.");
define("ERR_070", "The XML tag 'demarrer_media' is invalid or missing.");
define("ERR_071", "The XML tag 'reponse_bonne_message' is invalid or missing.");
define("ERR_072", "The XML tag 'reponse_mauvaise_message' is invalid or missing.");
define("ERR_073", "The XML tag 'reponse_incomplete_message' is invalid or missing.");
define("ERR_074", "The XML tag 'reponse_bonne_media' is invalid or missing.");
define("ERR_075", "The XML tag 'reponse_mauvaise_media' is invalid or missing.");
define("ERR_076", "The XML tag 'reponse_incomplete_media' is invalid or missing.");
define("ERR_077", "The XML tag 'remarque' is invalid or missing.");
define("ERR_078", "The XML tag 'type_item' is invalid or missing.");
define("ERR_079", "A media file is not found in the media folder: "); 
define("ERR_080", "Impossible to find the XML definition for the media file ");
define("ERR_081", "The XML tag 'id_item' is invalid or missing.");
define("ERR_082", "The XML tag 'enonce' is invalid or missing.");
define("ERR_083", "The XML tag 'description' is invalid or missing.");
define("ERR_084", "The XML tag 'type' is invalid or missing.");
define("ERR_085", "The XML tag 'source' is invalid or missing.");
define("ERR_086", "The XML tag 'url' is invalid or missing.");
define("ERR_087", "The XML tag 'suivi' is invalid or missing.");
define("ERR_088", "The XML tag 'id_item_choix_mult' is invalid or missing.");
define("ERR_089", "The XML tag 'bonne_reponse' is invalid or missing.");
define("ERR_090", "The XML tag 'element' is invalid or missing.");
define("ERR_091", "The XML tag 'retroaction' is invalid or missing.");
define("ERR_092", "The XML tag 'titre_long' is invalid or missing.");
define("ERR_093", "The XML tag 'generation_question_type' is invalid or missing.");
define("ERR_094", "The XML tag 'generation_question_nb' is invalid or missing.");
define("ERR_095", "Impossible to locate the XML definition for section ");
define("ERR_096", "The XML tag 'temps_reponse_calculer' is invalid or missing.");
define("ERR_097", "The XML tag 'essais_repondre_type' is invalid or missing.");
define("ERR_098", "The XML tag 'essais_repondre_nb' is invalid or missing.");
define("ERR_099", "The XML tag 'affichage_resultats_type' is invalid or missing.");
define("ERR_100", "The XML tag 'demarrage_media_type' is invalid or missing.");
define("ERR_101", "The XML tag 'id_langue_questionnaire' is invalid or missing.");
define("ERR_102", "The XML tag 'theme' is invalid or missing.");
define("ERR_103", "The XML tag 'mot_bienvenue' is invalid or missing.");
define("ERR_104", "The XML tag 'note' is invalid or missing.");
define("ERR_105", "The XML tag 'generique' is invalid or missing.");
define("ERR_106", "The XML tag 'media_titre' is invalid or missing.");
define("ERR_107", "The XML tag 'media_texte' is invalid or missing.");
define("ERR_108", "The XML tag 'media_image' is invalid or missing.");
define("ERR_109", "The XML tag 'media_son' is invalid or missing.");
define("ERR_110", "The XML tag 'media_video' is invalid or missing.");
define("ERR_111", "The XML tag 'texte_fin' is invalid or missing.");
define("ERR_112", "The XML tag 'id_item' is invalid or missing for the section questionnaire_item where id_item = ");
define("ERR_113", "The XML tag 'id_section' is invalid or missing for the section questionnaire_item where id_item = ");
define("ERR_114", "The XML tag 'ponderation_quest' is invalid or missing for the section questionnaire_item where id_item = ");
define("ERR_115", "The XML tag 'demarrer_media_quest' is invalid or missing for the section questionnaire_item where id_item = ");
define("ERR_116", "The XML tag 'ordre_presentation_quest' is invalid or missing for the section questionnaire_item where id_item = ");
define("ERR_117", "The XML tag 'type_etiquettes_quest' is invalid or missing for the section questionnaire_item where id_item = ");
define("ERR_118", "The XML tag 'id_section' is invalid or missing for a section.");
define("ERR_119", "The XML tag 'titre' is invalid or missing for la section where id_section = ");
define("ERR_120", "The XML tag 'generation_question_type' is invalid or missing for la section where id_section = ");
define("ERR_121", "The XML tag 'generation_question_nb' is invalid or missing for la section where id_section = ");
define("ERR_122", "The XML tag 'type_bonnesreponses_quest' is invalid or missing.");
define("ERR_123", "The XML tag 'retroaction_negative' is invalid or missing.");
define("ERR_124", "The XML tag 'points_retranches_quest' is invalid or missing.");
define("ERR_125", "The XML tag 'majmin_quest' is invalid or missing.");
define("ERR_126", "Impossible to locate the XML definition for the item ");
define("ERR_127", "A 'page' must necessarily include text in the field 'Text'.");
define("ERR_128", "Unable to create the type of item requested. Software error has occurred.");
define("ERR_129", "A question-type 'True or False' must include at least 2 valid answers choices.");
define("ERR_130", "A question-type 'Multiple Answer' must include at least 2 valid answers choices.");
define("ERR_131", "Your session has expired and you have been logged out. Confirm your username and password to continue.");
define("ERR_132", " A question-type 'Sequencing' must include at least 2 valid answers choices.");
define("ERR_133", "");
define("ERR_134", "The XML tag 'ponctuation_quest' is invalid or missing.");
define("ERR_135", "The XML tag 'solution' is invalid or missing.");
define("ERR_136", "The XML tag 'retroaction_positive' is invalid or missing.");
define("ERR_137", "The XML tag 'retroaction_negative' is invalid or missing.");
define("ERR_138", "An 'Essay' question must include text in the 'Question text' field.");
define("ERR_139", "A question-type 'Dictation' must include text in the 'Correct Answer' field.");
define("ERR_140", "The value of 'Points deducted' in the item parameters must be numerical.");
define("ERR_141", "The number of points to deduct per mistake is more than the value of this question.");
define("ERR_142", "The value of 'Points deducted' in the item parameters ('Values modified for this quiz only' section) must be numerical."); 
define("ERR_143", "A question-type 'Matching' must include at least two valid pairs of elements.");
define("ERR_144", "Certain pairs of elements to match are not completed."); 
define("ERR_145", "Certain pairs of elements to match in the matching board are not completed.");
define("ERR_146", "A question-type 'Matching Board' must include 2, 4, 6, 8, or 10 valid pairs of elements to match."); 
define("ERR_147", "The XML tag 'masque' is invalid or missing.");
define("ERR_148", "A question-type 'Short answer' must include feedback for unpredicted answers.");
define("ERR_149", "A question-type 'Short answer' must include text in the 'Question text' field."); 
define("ERR_150", "A question-type 'Short answer' must include at least one predicted answer.");
define("ERR_151", "The same highlighting colour is used more than once."); 
define("ERR_152", "Certain highlighting colours do not have labels."); 
define("ERR_153", "Certain highlighting colours have the same label."); 
define("ERR_154", "A question-type 'Classification' must include at least 2 valid folders.");
define("ERR_155", "Certain folders do not have a valid tab.");
define("ERR_156", "The XML tag 'orientation_elements_quest' is invalid or missing.");
define("ERR_157", "The XML tag 'orientation_elements' is invalid or missing.");
define("ERR_158", "The XML file has one or more syntax errors and cannot be processed.");
define("ERR_159", "Each blank of a 'Fill-in-the-blanks' question must include at least one correct answer.");
define("ERR_160", "Each blank of a 'Fill-in-the-blanks' question with short answers must include feedback for unpredicted answers.");
define("ERR_161", "Each blank of a 'Fill-in-the-blanks' question with drop-down menus must include at least one incorrect answer."); 
define("ERR_162", "Each blank of a 'Fill-in-the-blanks' question with drag and drop or short answers must include at least one possible correct answer."); 
define("ERR_163", "Each blank of a 'Fill-in-the-blanks' question with drop-down menus  must include at least two possible answers.");
define("ERR_164", "A question-type 'Fill-in-the-blanks' must include a text and at least one blank.");
define("ERR_165", "The XML tag 'type_champs' is invalid or missing for the item ");
define("ERR_166", "The XML tag 'couleur_element_quest' is invalid or missing for the item ");
define("ERR_167", "The XML tag 'couleur_element_associe_quest' is invalid or missing for the item ");
define("ERR_168", "The XML tag 'afficher_masque_quest' is invalid or missing for the item ");
define("ERR_169", "The XML tag 'type_champs_quest' is invalid or missing for the item ");
define("ERR_170", "The XML tag 'id_terme' is invalid or missing.");
define("ERR_171", "The XML tag 'couleur_zones' is invalid or missing.");
define("ERR_172", "The currently selected theme cannot be found. Please choose a new theme.");
define("ERR_173", "A question-type 'Identify Parts of an Image' must include an image on which labels of the parts to be identified will be placed.");
define("ERR_174", "A question-type 'Identify Parts of an Image' must include at least two valid parts.");
define("ERR_175", "Certain boxes for parts to be identified are placed on top of each other.");
define("ERR_176", "The username is invalid or missing.");
define("ERR_177", "The username already exists."); 
define("ERR_178", "An account already exists for this email. If you forgot your password or username, click on the link on the connection page.");
define("ERR_179", "Your account must be approved before you can connect.");
define("ERR_180", "Your account is locked. Contact the site administrator.");
define("ERR_181", "The project title is invalid or missing."); 
define("ERR_182", "The project description is invalid or missing."); 
define("ERR_183", "The unique identifier for this project is invalid or missing.");
define("ERR_184", "The selected project is not accessible. Make sure this project is active and that you have the required permissions to access it.");
define("ERR_185", "The unique identifier for this project is already used. Please enter a new identifier."); 
define("ERR_186", "The unique identifier must include at least one letter."); 
define("ERR_187", "You do not have the required permissions to perform this operation.");
define("ERR_188", "The specified project is invalid or missing."); 
define("ERR_189", "Your account request was refused. Contact the site administrator.");
define("ERR_190", "The default language for preview and publication is invalid or missing.");
define("ERR_191", "The default theme for preview and publication is invalid or missing."); 
define("ERR_192", "The display language for preview is invalid.");
define("ERR_193", "This person has already received an invitation.");
define("ERR_194", "This person is already a collaborator on this project.");
define("ERR_195", "You already have access to this project, so you cannot be made a collaborator.");
define("ERR_196", "You do not have the required access for this project.");
define("ERR_197", "The new collaborator's email address is invalid or missing.");
define("ERR_198", "Note that the project you have been invited to join has been deleted.");
define("ERR_199", " Note that the project you have been invited to join is now inactive.");
define("ERR_200", "This user has been deleted or is inactive. Unable to make it the project manager.");
define("ERR_201", "Note that the projet or the collaboration request has been deleted."); 
define("ERR_202", "The number of quiz items to include, as indicated in the 'Presentation of items' parameter, is more than the total number of quiz items.");
define("ERR_203", "Your access to Netquiz Web is temporarily disabled. Please contact the site administrator.");
define("ERR_204", "The theme previously saved no longer exists. The default theme will be used.");
define("ERR_205", "Error detected in the XML file: the item IDs are not unique in the 'questionnaire_item' list. Incorrect IDs: ");
define("ERR_206", "Error detected in the XML file: the item IDs are not unique in the list of items. Incorrect IDs: ");
define("ERR_207", "Error detected in the XML file: the media IDs are not unique. Incorrect IDs: ");
define("ERR_208", "Error detected in the XML file: The quiz IDs are not unique. Incorrect IDs: ");
define("ERR_209", "An account already exists for this email. Please check or use a different email.");
define("ERR_210", "The current project has no unique identifier. Please complete the field 'Unique identifier' in the project settings.");
define("ERR_211", "Some fields are missing in the language chosen for preview or publication of this quiz. Please complete these fields in the Library/My languages section.");
define("ERR_212", "Impossible to find the username in the database.");
define("ERR_213", "Your access has been temporarily disabled. Please contact the site administrator.");
define("ERR_214", "The file 'netquizweb-installation.sql' containing the database schema cannot be located. The request cannot be completed.");
define("ERR_215", "An error occurred while the database tables were being created. Check that the username for accessing the database has the required privileges for creating tables.");
define("ERR_216", "The folder used to publish quizzes does not have the required permissions. Check the permissions of this folder:");
define("ERR_217", "The media folder does not have the required privileges. Check the permissions of this folder:");
define("ERR_218", "The folder for the software logs does not have the required permissions. Check the permissions of this folder:");
define("ERR_219", "An error occurred while attempting to access the database during the Netquiz Web update. Check that the username for accessing the database has the required privileges and try again.");
define("ERR_220", "The DB_HOST parameter is missing or incorrect in the config.inc.php file.");
define("ERR_221", "The DB_NAME parameter is missing or incorrect in the config.inc.php file.");
define("ERR_222", "The DB_USER parameter is missing or incorrect in the config.inc.php file.");
define("ERR_223", "The DB_PASSWORD parameter is missing or incorrect in the config.inc.php file.");
define("ERR_224", "The EMAIL_FROM parameter is missing or incorrect in the config.inc.php file.");
define("ERR_225", "The 'resources' folder should not be public. Check the folder permissions, the .htaccess file or Apache's .htaccess settings.");
define("ERR_226", "Netquiz Web installation is not completed or a problem occurred with the database content. Click this link <a href='http://aide.ccdmd.qc.ca/nqw/node/136/' target='help'>Netquiz Web installation</a> and make sure you have completed the steps. Otherwise, contact the administrator of the database.");
define("ERR_227", "Error detected in the XML file: language ID are not unique. Incorrect ID: ");
define("ERR_228", "The XML tag 'id_langue' is invalid or missing.");
define("ERR_229", "The XML tag 'id_collection' is invalid or missing.");
define("ERR_230", "The XML tag 'id_categorie' is invalid or missing.");
define("ERR_231", "The XML tag 'terme' is invalid or missing.");
define("ERR_232", "The XML tag 'variantes' is invalid or missing.");
define("ERR_233", "The XML tag 'type_definition' is invalid or missing.");
define("ERR_234", "The XML tag 'texte' is invalid or missing.");
define("ERR_235", "The XML tag 'url' is invalid or missing.");
define("ERR_236", "This is not the correct file type.");
define("ERR_237", "WARNING! One or more people are working on the same element as you. This could result in a loss of data if you save. If necessary, contact these people: ");

/** URL pour l'aide en ligne **/
define('URL_AIDE_NQW', 'http://aide.ccdmd.qc.ca/nqw/en/content/');

 /** Fichiers **/
define("FICHIER_THEME_APERCU", "apercuEN.jpg");

/** Questionnaires - statut **/
define ("QUESTIONNAIRE_STATUT_0", "Deleted");
define ("QUESTIONNAIRE_STATUT_1", "Draft");
define ("QUESTIONNAIRE_STATUT_2", "Published");

/** Projets - statuts **/
define("PROJET_STATUT_0", "Inactive"); 
define("PROJET_STATUT_1", "Active");
define("PROJET_STATUT_2", "Deleted"); 
define("PROJET_STATUT_3", "Locked"); 

/** Usager - statuts **/
define("USAGER_STATUT_0", "Active");
define("USAGER_STATUT_1", "Locked");
define("USAGER_STATUT_2", "Waiting for approval");
define("USAGER_STATUT_3", "Acces refused");
define("USAGER_STATUT_4", "Incomplete");
define("USAGER_STATUT_9", "Deleted");

?>
