<?php echo TXT_COURRIEL_COLLABORATEUR_INVITATION_BONJOUR ?>


<?php echo $element->get("responsable_invitation") . " " . TXT_COURRIEL_COLLABORATEUR_INVITATION_LIGNE1A  . " " . $element->get("titre") . " " . TXT_COURRIEL_COLLABORATEUR_INVITATION_LIGNE1B ?>.

<?php echo TXT_COURRIEL_COLLABORATEUR_INVITATION_LIGNE2 ?> 

<?php echo URL_DOMAINE . URL_BASE . URL_COLLABORATEUR_INVITATION . $element->get("jeton") ?> 

<?php echo TXT_COURRIEL_COLLABORATEUR_INVITATION_LIGNE3 ?>


<?php echo TXT_COURRIEL_COLLABORATEUR_INVITATION_MERCI ?>


<?php echo TXT_COURRIEL_COLLABORATEUR_INVITATION_SIGNATURE ?>

